function performance = aerodynamicPerformance(aircraft, atm, maximumSpeed_mps)
%AERODYNAMICPERFORMANCE Evaluate aerodynamic performance across airspeed.

    if nargin < 3 || isempty(maximumSpeed_mps)
        if isfield(aircraft, 'aeroSweepMaximumSpeed_mps')
            maximumSpeed_mps = aircraft.aeroSweepMaximumSpeed_mps;
        else
            maximumSpeed_mps = 150 * 0.514444;
        end
    end

    validateattributes(maximumSpeed_mps, {'numeric'}, ...
        {'real', 'finite', 'positive', 'scalar'}, ...
        mfilename, 'maximumSpeed_mps', 3);

    speeds = characteristicSpeeds(aircraft, atm);
    if maximumSpeed_mps <= speeds.stall_mps
        error('aerodynamicPerformance:InvalidMaximumSpeed', ...
            'maximumSpeed_mps must be greater than stall speed.');
    end

    airspeed_mps = linspace(speeds.stall_mps, maximumSpeed_mps, 1000);
    [drag_N, CL, CD] = dragRequired(aircraft, atm, airspeed_mps);
    powerRequired_W = drag_N .* airspeed_mps;

    performance = struct( ...
        'airspeed_mps', airspeed_mps, ...
        'drag_N', drag_N, ...
        'powerRequired_W', powerRequired_W, ...
        'CL', CL, ...
        'CD', CD, ...
        'speeds', speeds, ...
        'weight_N', aircraft.W, ...
        'density_kgpm3', atm.rho);
end
