function corrected = applyPohFieldCorrections( ...
        groundRoll_ft, totalOver50ft_ft, windComponent_kt, ...
        grassAdditionFraction, configurationMultiplier, ...
        maximumTailwind_kt)
%APPLYPOHFIELDCORRECTIONS Apply published field-performance corrections.
%
%   Positive WINDCOMPONENT_KT denotes headwind; negative denotes tailwind.
%   POH wind rules are applied linearly:
%       headwind: decrease 10% per 9 kt
%       tailwind: increase 10% per 2 kt, up to the published 10-kt limit
%
%   Grass correction is an additive fraction of the tabulated ground-roll
%   figure, added to both wind-corrected distances. This follows the POH's
%   literal wording. A configuration multiplier (for example, 1.35 for a
%   flaps-up landing) is applied last.

    validateattributes(groundRoll_ft, {'numeric'}, ...
        {'real', 'finite', 'positive', 'scalar'}, ...
        mfilename, 'groundRoll_ft', 1);
    validateattributes(totalOver50ft_ft, {'numeric'}, ...
        {'real', 'finite', 'positive', 'scalar'}, ...
        mfilename, 'totalOver50ft_ft', 2);
    validateattributes(windComponent_kt, {'numeric'}, ...
        {'real', 'finite', 'scalar'}, ...
        mfilename, 'windComponent_kt', 3);
    validateattributes(grassAdditionFraction, {'numeric'}, ...
        {'real', 'finite', 'nonnegative', 'scalar'}, ...
        mfilename, 'grassAdditionFraction', 4);
    validateattributes(configurationMultiplier, {'numeric'}, ...
        {'real', 'finite', 'positive', 'scalar'}, ...
        mfilename, 'configurationMultiplier', 5);
    validateattributes(maximumTailwind_kt, {'numeric'}, ...
        {'real', 'finite', 'nonnegative', 'scalar'}, ...
        mfilename, 'maximumTailwind_kt', 6);

    if totalOver50ft_ft < groundRoll_ft
        error('applyPohFieldCorrections:InvalidDistances', ...
            'Total distance must not be less than ground roll.');
    end

    if windComponent_kt >= 0
        windCorrectionPercent = -10 * windComponent_kt / 9;
        windDescription = 'headwind correction';
    else
        tailwind_kt = abs(windComponent_kt);
        if tailwind_kt > maximumTailwind_kt
            error('applyPohFieldCorrections:TailwindOutsidePOH', ...
                ['Tailwind component %.1f kt exceeds the published ' ...
                 'POH correction limit of %.1f kt.'], ...
                tailwind_kt, maximumTailwind_kt);
        end
        windCorrectionPercent = 10 * tailwind_kt / 2;
        windDescription = 'tailwind correction';
    end

    windFactor = 1 + windCorrectionPercent / 100;
    if windFactor <= 0
        error('applyPohFieldCorrections:HeadwindCorrectionInvalid', ...
            ['The requested headwind produces a nonpositive distance ' ...
             'factor; the POH rule is not valid for this input.']);
    end

    groundAfterWind_ft = groundRoll_ft * windFactor;
    totalAfterWind_ft = totalOver50ft_ft * windFactor;
    grassAddition_ft = grassAdditionFraction * groundRoll_ft;
    groundAfterSurface_ft = groundAfterWind_ft + grassAddition_ft;
    totalAfterSurface_ft = totalAfterWind_ft + grassAddition_ft;

    corrected = struct( ...
        'baseGroundRoll_ft', groundRoll_ft, ...
        'baseTotalOver50ft_ft', totalOver50ft_ft, ...
        'windComponent_kt', windComponent_kt, ...
        'windCorrectionPercent', windCorrectionPercent, ...
        'windDescription', windDescription, ...
        'windFactor', windFactor, ...
        'groundAfterWind_ft', groundAfterWind_ft, ...
        'totalAfterWind_ft', totalAfterWind_ft, ...
        'grassAdditionFraction', grassAdditionFraction, ...
        'grassAddition_ft', grassAddition_ft, ...
        'configurationMultiplier', configurationMultiplier, ...
        'groundRoll_ft', groundAfterSurface_ft * configurationMultiplier, ...
        'totalOver50ft_ft', ...
            totalAfterSurface_ft * configurationMultiplier);
    corrected.roundedUpGroundRoll_ft = ceil(corrected.groundRoll_ft);
    corrected.roundedUpTotalOver50ft_ft = ...
        ceil(corrected.totalOver50ft_ft);
end
