function speeds = characteristicSpeeds(aircraft, atm)
%CHARACTERISTICSPEEDS Calculate stall, minimum-power, and minimum-drag speeds.
%
%   The unconstrained optima are obtained analytically for the parabolic
%   drag polar. If an optimum lies below stall speed, the physically usable
%   minimum is placed at stall speed.

    requiredFields = {'W', 'S', 'CD0', 'e', 'AR', 'CLmax'};
    for k = 1:numel(requiredFields)
        if ~isfield(aircraft, requiredFields{k})
            error('characteristicSpeeds:MissingAircraftField', ...
                'aircraft.%s is required.', requiredFields{k});
        end
    end
    if ~isfield(atm, 'rho')
        error('characteristicSpeeds:MissingDensity', ...
            'atm.rho is required.');
    end

    [~, inducedDragFactor] = dragPolar(aircraft, 0);
    commonTerm = 4 * inducedDragFactor * aircraft.W^2 / ...
        (atm.rho^2 * aircraft.S^2 * aircraft.CD0);

    Vs_mps = stallSpeed(aircraft, atm);
    VmdTheory_mps = commonTerm^(1/4);
    VmpTheory_mps = (commonTerm / 3)^(1/4);

    Vmd_mps = max(Vs_mps, VmdTheory_mps);
    Vmp_mps = max(Vs_mps, VmpTheory_mps);

    [Dmin_N, CLmd, CDmd] = dragRequired(aircraft, atm, Vmd_mps);
    [PRmin_W, Dmp_N, CLmp, CDmp] = ...
        powerRequired(aircraft, atm, Vmp_mps);

    speeds = struct( ...
        'stall_mps', Vs_mps, ...
        'minimumDrag_mps', Vmd_mps, ...
        'minimumPower_mps', Vmp_mps, ...
        'minimumDragTheory_mps', VmdTheory_mps, ...
        'minimumPowerTheory_mps', VmpTheory_mps, ...
        'minimumDrag_N', Dmin_N, ...
        'minimumPower_W', PRmin_W, ...
        'dragAtMinimumPower_N', Dmp_N, ...
        'CLAtMinimumDrag', CLmd, ...
        'CDAtMinimumDrag', CDmd, ...
        'CLAtMinimumPower', CLmp, ...
        'CDAtMinimumPower', CDmp, ...
        'inducedDragFactor', inducedDragFactor);
end
