function audit = cruiseAccuracyAudit()
%CRUISEACCURACYAUDIT Evaluate drag/propulsion consistency against POH data.
%
%   AUDIT = CRUISEACCURACYAUDIT() evaluates every published operating
%   point in C172S POH Figure 5-8. For each candidate drag polar, the
%   implied installed propeller efficiency is calculated from
%
%       eta_implied = power required / engine brake power.
%
%   A physically credible candidate should produce finite efficiencies
%   between zero and one and a reasonably smooth relationship with advance
%   ratio. This audit does not automatically select or calibrate a model.
%
%   Important identification limitation:
%   POH cruise data constrain the combined drag and propulsive models.
%   They cannot uniquely identify CD0, induced drag, and propeller
%   efficiency without independent aerodynamic or propeller measurements.

    KT_TO_MPS = 0.514444;
    RHO0 = 1.2250;

    aircraft = cessna172();
    data = pohCruiseData();

    candidates = candidateDragPolars(aircraft);
    numberCandidates = numel(candidates);
    pointsPerTemperature = sum(cellfun(@numel, data.rpmGrid));
    numberPoints = pointsPerTemperature * numel(data.deltaISAColumns_C);

    altitude_ft = zeros(numberPoints, 1);
    deltaISA_C = zeros(numberPoints, 1);
    rpm = zeros(numberPoints, 1);
    trueAirspeed_KTAS = zeros(numberPoints, 1);
    percentMCP = zeros(numberPoints, 1);
    fuelFlow_GPH = zeros(numberPoints, 1);
    density_kgpm3 = zeros(numberPoints, 1);
    advanceRatio = zeros(numberPoints, 1);
    liftCoefficient = zeros(numberPoints, 1);
    enginePower_kW = zeros(numberPoints, 1);

    mcpTables = {data.mcpCold_pct, data.mcpISA_pct, data.mcpHot_pct};
    ktasTables = {data.ktasCold, data.ktasISA, data.ktasHot};
    gphTables = {data.gphCold, data.gphISA, data.gphHot};

    pointIndex = 0;
    for temperatureIndex = 1:numel(data.deltaISAColumns_C)
        temperatureOffset_C = data.deltaISAColumns_C(temperatureIndex);
        mcpTable = mcpTables{temperatureIndex};
        ktasTable = ktasTables{temperatureIndex};
        gphTable = gphTables{temperatureIndex};

        for altitudeIndex = 1:numel(data.altitudeGrid_ft)
            atm = atmosphereAtPressureAltitude( ...
                data.altitudeGrid_ft(altitudeIndex), temperatureOffset_C);

            for rpmIndex = 1:numel(data.rpmGrid{altitudeIndex})
                pointIndex = pointIndex + 1;
                altitude_ft(pointIndex) = ...
                    data.altitudeGrid_ft(altitudeIndex);
                deltaISA_C(pointIndex) = temperatureOffset_C;
                rpm(pointIndex) = data.rpmGrid{altitudeIndex}(rpmIndex);
                trueAirspeed_KTAS(pointIndex) = ...
                    ktasTable{altitudeIndex}(rpmIndex);
                percentMCP(pointIndex) = ...
                    mcpTable{altitudeIndex}(rpmIndex);
                fuelFlow_GPH(pointIndex) = ...
                    gphTable{altitudeIndex}(rpmIndex);
                density_kgpm3(pointIndex) = atm.rho;
            end
        end
    end

    trueAirspeed_mps = trueAirspeed_KTAS .* KT_TO_MPS;
    enginePower_W = aircraft.enginePowerSL .* (percentMCP ./ 100);
    enginePower_kW(:) = enginePower_W ./ 1000;
    advanceRatio(:) = trueAirspeed_mps ./ ...
        ((rpm ./ 60) .* aircraft.propDiameter);
    liftCoefficient(:) = 2 .* aircraft.W ./ ...
        (density_kgpm3 .* trueAirspeed_mps.^2 .* aircraft.S);

    etaImplied = zeros(numberPoints, numberCandidates);
    powerRequired_kW = zeros(numberPoints, numberCandidates);
    candidateNames = cell(numberCandidates, 1);
    candidateFormulas = cell(numberCandidates, 1);
    candidateProvenance = cell(numberCandidates, 1);
    meanEtaImplied = zeros(numberCandidates, 1);
    minimumEtaImplied = zeros(numberCandidates, 1);
    maximumEtaImplied = zeros(numberCandidates, 1);
    cubicHoldoutRMSE = zeros(numberCandidates, 1);
    maximumLiftToDragRatio = zeros(numberCandidates, 1);
    bestGlideEstimate_KIAS = zeros(numberCandidates, 1);
    bestGlideErrorFrom68_kt = zeros(numberCandidates, 1);

    for candidateIndex = 1:numberCandidates
        candidate = candidates(candidateIndex);
        dragCoefficient = candidate.CD0 + candidate.k .* ...
            (liftCoefficient - candidate.CL0).^2;
        drag_N = 0.5 .* density_kgpm3 .* trueAirspeed_mps.^2 .* ...
            aircraft.S .* dragCoefficient;
        required_W = drag_N .* trueAirspeed_mps;
        impliedEfficiency = required_W ./ enginePower_W;

        etaImplied(:, candidateIndex) = impliedEfficiency;
        powerRequired_kW(:, candidateIndex) = required_W ./ 1000;

        holdoutRMSE = etaHoldoutRMSE(advanceRatio, impliedEfficiency);
        [maximumLD, bestGlide_KIAS] = maximumLiftToDrag( ...
            candidate, aircraft, RHO0, KT_TO_MPS);

        candidateNames{candidateIndex} = candidate.name;
        candidateFormulas{candidateIndex} = candidate.formula;
        candidateProvenance{candidateIndex} = candidate.provenance;
        meanEtaImplied(candidateIndex) = mean(impliedEfficiency);
        minimumEtaImplied(candidateIndex) = min(impliedEfficiency);
        maximumEtaImplied(candidateIndex) = max(impliedEfficiency);
        cubicHoldoutRMSE(candidateIndex) = holdoutRMSE;
        maximumLiftToDragRatio(candidateIndex) = maximumLD;
        bestGlideEstimate_KIAS(candidateIndex) = bestGlide_KIAS;
        bestGlideErrorFrom68_kt(candidateIndex) = bestGlide_KIAS - 68;
    end

    [proxyEfficiency, ~] = propellerEfficiency( ...
        trueAirspeed_mps, rpm, aircraft.propeller);
    currentRequired_W = powerRequired_kW(:, 1) .* 1000;
    proxyPowerMargin_kW = ...
        (proxyEfficiency .* enginePower_W - currentRequired_W) ./ 1000;

    audit.points = table( ...
        altitude_ft, deltaISA_C, rpm, trueAirspeed_KTAS, percentMCP, ...
        fuelFlow_GPH, ...
        density_kgpm3, advanceRatio, liftCoefficient, enginePower_kW, ...
        powerRequired_kW(:, 1), etaImplied(:, 1), ...
        powerRequired_kW(:, 2), etaImplied(:, 2), ...
        powerRequired_kW(:, 3), etaImplied(:, 3), ...
        proxyEfficiency, proxyPowerMargin_kW, ...
        'VariableNames', { ...
            'Altitude_ft', 'DeltaISA_C', 'RPM', 'POH_KTAS', ...
            'POH_PercentMCP', 'POH_FuelFlow_GPH', ...
            'Density_kgpm3', 'AdvanceRatio', ...
            'LiftCoefficient', 'EnginePower_kW', ...
            'CurrentPolarPowerRequired_kW', 'CurrentPolarEtaImplied', ...
            'ExternalPolarPowerRequired_kW', 'ExternalPolarEtaImplied', ...
            'HaberkornPowerRequired_kW', 'HaberkornEtaImplied', ...
            'CurrentProxyEta', 'CurrentProxyPowerMargin_kW'});

    audit.summary = table( ...
        candidateNames, candidateFormulas, candidateProvenance, ...
        meanEtaImplied, minimumEtaImplied, maximumEtaImplied, ...
        cubicHoldoutRMSE, maximumLiftToDragRatio, bestGlideEstimate_KIAS, ...
        bestGlideErrorFrom68_kt, ...
        'VariableNames', { ...
            'Candidate', 'Formula', 'Provenance', 'MeanEtaImplied', ...
            'MinimumEtaImplied', 'MaximumEtaImplied', ...
            'CubicHoldoutRMSE', 'MaximumLiftToDrag', ...
            'BestGlideEstimate_KIAS', 'BestGlideErrorFrom68_kt'});

    closureTolerance_kW = 2.0;
    audit.currentProxy = struct( ...
        'meanPowerMargin_kW', mean(proxyPowerMargin_kW), ...
        'medianPowerMargin_kW', median(proxyPowerMargin_kW), ...
        'rmsPowerMargin_kW', sqrt(mean(proxyPowerMargin_kW.^2)), ...
        'minimumPowerMargin_kW', min(proxyPowerMargin_kW), ...
        'maximumPowerMargin_kW', max(proxyPowerMargin_kW), ...
        'closureTolerance_kW', closureTolerance_kW, ...
        'passesRMSClosure', ...
            sqrt(mean(proxyPowerMargin_kW.^2)) <= closureTolerance_kW);
    audit.candidates = candidates;
    audit.numberPOHPoints = numberPoints;
    audit.pohSource = data.source;
    audit.referenceBestGlide_KIAS = 68;
    audit.referenceBestGlideNote = ...
        ['POH emergency best-glide speed at 2550 lb; KIAS is used only ' ...
         'as a comparison, not as an exact calibrated-airspeed target.'];
    audit.conclusion = ...
        ['No candidate is selected automatically. Implied efficiency ' ...
         'combines aerodynamic and propulsive-model error.'];
end

function candidates = candidateDragPolars(aircraft)
%CANDIDATEDRAGPOLARS Define traceable comparison models.

    currentK = 1 / (pi * aircraft.e * aircraft.AR);
    externalAR = 7.52;
    externalE = 0.75;

    candidates(1) = struct( ...
        'name', 'Current conventional polar', ...
        'formula', 'CD = 0.027 + k CL^2', ...
        'provenance', 'Current engineering assumptions; not validated', ...
        'CD0', aircraft.CD0, ...
        'CL0', 0, ...
        'k', currentK);

    candidates(2) = struct( ...
        'name', 'External conventional comparison', ...
        'formula', 'CD = 0.031 + k CL^2; e = 0.75, AR = 7.52', ...
        'provenance', ...
            'User-supplied secondary estimate; unverified comparison only', ...
        'CD0', 0.031, ...
        'CL0', 0, ...
        'k', 1 / (pi * externalE * externalAR));

    candidates(3) = struct( ...
        'name', 'Haberkorn shifted polar', ...
        'formula', 'CD = 0.033 + 0.035 (CL - 0.14)^2', ...
        'provenance', ...
            ['Haberkorn TU Graz dissertation Figure A.10; constructed ' ...
             'comparison, not Cessna flight-test validation'], ...
        'CD0', 0.033, ...
        'CL0', 0.14, ...
        'k', 0.035);
end

function rmse = etaHoldoutRMSE(advanceRatio, impliedEfficiency)
%ETAHOLDOUTRMSE Measure one-dimensional eta(J) consistency.
%
%   Alternating points after sorting by J are held out. The metric is a
%   diagnostic only; it is not proof that a candidate polar is correct.

    [~, order] = sort(advanceRatio);
    calibration = order(1:2:end);
    validation = order(2:2:end);
    coefficients = polyfit( ...
        advanceRatio(calibration), impliedEfficiency(calibration), 3);
    prediction = polyval(coefficients, advanceRatio(validation));
    rmse = sqrt(mean((prediction - impliedEfficiency(validation)).^2));
end

function [maximumLD, bestGlide_KIAS] = maximumLiftToDrag( ...
        candidate, aircraft, rho0, ktToMps)
%MAXIMUMLIFTTODRAG Numerically evaluate each possibly shifted polar.

    liftCoefficient = linspace(0.05, 1.8, 20000);
    dragCoefficient = candidate.CD0 + candidate.k .* ...
        (liftCoefficient - candidate.CL0).^2;
    liftToDrag = liftCoefficient ./ dragCoefficient;
    [maximumLD, index] = max(liftToDrag);
    optimumCL = liftCoefficient(index);
    bestGlide_mps = sqrt( ...
        2 * aircraft.W / (rho0 * aircraft.S * optimumCL));
    bestGlide_KIAS = bestGlide_mps / ktToMps;
end
