function model = fitEffectiveCruiseModel(points)
%FITEFFECTIVECRUISEMODEL Calibrate a combined POH cruise-closure model.
%
%   MODEL = FITEFFECTIVECRUISEMODEL() calibrates against all 111 published
%   C172S POH Figure 5-8 operating points assembled by
%   CRUISEACCURACYAUDIT.
%
%   MODEL = FITEFFECTIVECRUISEMODEL(POINTS) uses the supplied audit-point
%   table. This form prevents the audit reporter from recalculating the
%   source data.
%
%   The fitted quantity is
%
%       eta_effective = P_required,current-polar / P_engine,POH
%
%   It is a combined calibration term that absorbs error in the assumed
%   airframe drag polar, installed propeller behavior, and other unmodeled
%   installation effects. It must not be reported as isolated propeller
%   efficiency or used outside the Figure 5-8 reference configuration.
%
%   Candidate forms are evaluated with leave-one-altitude, leave-one-
%   temperature-column, and leave-one-RPM grouped cross-validation. The
%   least-complex candidate satisfying both the 2 kW RMS and 2 kW maximum
%   absolute-error gates is selected. Random point splitting is not used.

    if nargin < 1 || isempty(points)
        audit = cruiseAccuracyAudit();
        points = audit.points;
    end

    requiredVariables = { ...
        'Altitude_ft', 'DeltaISA_C', 'RPM', 'POH_KTAS', ...
        'Density_kgpm3', 'AdvanceRatio', 'EnginePower_kW', ...
        'CurrentPolarEtaImplied'};
    validatePointTable(points, requiredVariables);

    normalization = struct( ...
        'advanceRatioCenter', 0.70, ...
        'rpmCenter', 2400, ...
        'rpmScale', 300, ...
        'densityCenter_kgpm3', 1.00, ...
        'densityScale_kgpm3', 0.20);

    candidateNames = { ...
        'J linear'; ...
        'J quadratic'; ...
        'J cubic'; ...
        'J quadratic + RPM + density'};
    candidateForms = { ...
        'j-linear'; ...
        'j-quadratic'; ...
        'j-cubic'; ...
        'j2-rpm-density'};
    numberCandidates = numel(candidateNames);
    gateLimit_kW = 2.0;

    parameterCount = zeros(numberCandidates, 1);
    calibrationRMS_kW = zeros(numberCandidates, 1);
    calibrationMaxAbs_kW = zeros(numberCandidates, 1);
    altitudeHoldoutRMS_kW = zeros(numberCandidates, 1);
    altitudeHoldoutMaxAbs_kW = zeros(numberCandidates, 1);
    temperatureHoldoutRMS_kW = zeros(numberCandidates, 1);
    temperatureHoldoutMaxAbs_kW = zeros(numberCandidates, 1);
    rpmHoldoutRMS_kW = zeros(numberCandidates, 1);
    rpmHoldoutMaxAbs_kW = zeros(numberCandidates, 1);
    passesGate = false(numberCandidates, 1);
    candidateResults = cell(numberCandidates, 1);

    for candidateIndex = 1:numberCandidates
        form = candidateForms{candidateIndex};
        result = fitCandidate(points, form, normalization);
        candidateResults{candidateIndex} = result;

        parameterCount(candidateIndex) = numel(result.coefficients);
        calibrationRMS_kW(candidateIndex) = ...
            result.calibration.rmsPowerError_kW;
        calibrationMaxAbs_kW(candidateIndex) = ...
            result.calibration.maximumAbsolutePowerError_kW;
        altitudeHoldoutRMS_kW(candidateIndex) = ...
            result.crossValidation.altitude.metrics.rmsPowerError_kW;
        altitudeHoldoutMaxAbs_kW(candidateIndex) = ...
            result.crossValidation.altitude.metrics.maximumAbsolutePowerError_kW;
        temperatureHoldoutRMS_kW(candidateIndex) = ...
            result.crossValidation.temperature.metrics.rmsPowerError_kW;
        temperatureHoldoutMaxAbs_kW(candidateIndex) = ...
            result.crossValidation.temperature.metrics.maximumAbsolutePowerError_kW;
        rpmHoldoutRMS_kW(candidateIndex) = ...
            result.crossValidation.rpm.metrics.rmsPowerError_kW;
        rpmHoldoutMaxAbs_kW(candidateIndex) = ...
            result.crossValidation.rpm.metrics.maximumAbsolutePowerError_kW;

        allRMS = [calibrationRMS_kW(candidateIndex), ...
            altitudeHoldoutRMS_kW(candidateIndex), ...
            temperatureHoldoutRMS_kW(candidateIndex), ...
            rpmHoldoutRMS_kW(candidateIndex)];
        allMaximum = [calibrationMaxAbs_kW(candidateIndex), ...
            altitudeHoldoutMaxAbs_kW(candidateIndex), ...
            temperatureHoldoutMaxAbs_kW(candidateIndex), ...
            rpmHoldoutMaxAbs_kW(candidateIndex)];
        passesGate(candidateIndex) = ...
            all(allRMS <= gateLimit_kW) && ...
            all(allMaximum <= gateLimit_kW);
    end

    selectionTable = table( ...
        candidateNames, candidateForms, parameterCount, ...
        calibrationRMS_kW, calibrationMaxAbs_kW, ...
        altitudeHoldoutRMS_kW, altitudeHoldoutMaxAbs_kW, ...
        temperatureHoldoutRMS_kW, temperatureHoldoutMaxAbs_kW, ...
        rpmHoldoutRMS_kW, rpmHoldoutMaxAbs_kW, passesGate, ...
        'VariableNames', { ...
            'Candidate', 'Form', 'ParameterCount', ...
            'CalibrationRMS_kW', 'CalibrationMaxAbs_kW', ...
            'AltitudeHoldoutRMS_kW', 'AltitudeHoldoutMaxAbs_kW', ...
            'TemperatureHoldoutRMS_kW', 'TemperatureHoldoutMaxAbs_kW', ...
            'RPMHoldoutRMS_kW', 'RPMHoldoutMaxAbs_kW', 'PassesGate'});

    selectedIndex = find(passesGate, 1, 'first');
    if isempty(selectedIndex)
        worstGroupedRMS = max([altitudeHoldoutRMS_kW, ...
            temperatureHoldoutRMS_kW, rpmHoldoutRMS_kW], [], 2);
        [~, selectedIndex] = min(worstGroupedRMS);
        selectionStatus = ...
            'FAIL - no candidate satisfies the 2 kW grouped gate';
    else
        selectionStatus = ...
            'PASS - least-complex candidate satisfying every gate';
    end

    selected = candidateResults{selectedIndex};
    aircraft = cessna172();
    envelope = struct( ...
        'advanceRatio', [min(points.AdvanceRatio), ...
            max(points.AdvanceRatio)], ...
        'rpm', [min(points.RPM), max(points.RPM)], ...
        'density_kgpm3', [min(points.Density_kgpm3), ...
            max(points.Density_kgpm3)], ...
        'pressureAltitude_ft', [min(points.Altitude_ft), ...
            max(points.Altitude_ft)], ...
        'deltaISA_C', [min(points.DeltaISA_C), ...
            max(points.DeltaISA_C)]);

    model = selected;
    model.name = 'POH-calibrated effective installed cruise model';
    model.classification = ...
        ['SEMI-EMPIRICAL/POH-CALIBRATED combined model; ' ...
         'not isolated propeller efficiency'];
    model.referenceConfiguration = ...
        'C172S, 2550 lb, speed fairings installed, Figure 5-8 cruise';
    model.source = ...
        ['C172S POH/AFM 172SPHBUS-02 Figure 5-8 plus current ' ...
         'conventional drag-polar assumption'];
    model.identifiabilityWarning = ...
        ['The coefficients combine assumed airframe drag, installed ' ...
         'propulsion, and POH rounding. They do not identify McCauley ' ...
         'JHA7660 propeller efficiency independently.'];
    model.selectionRule = ...
        ['Select the least-complex candidate with calibration and every ' ...
         'grouped-holdout RMS and maximum absolute power error <= 2 kW.'];
    model.selectionStatus = selectionStatus;
    model.passesCalibrationGate = passesGate(selectedIndex);
    model.gateLimit_kW = gateLimit_kW;
    model.selectionTable = selectionTable;
    model.selectedCandidateIndex = selectedIndex;
    model.normalization = normalization;
    model.trainingEnvelope = envelope;
    model.numberCalibrationPoints = height(points);
    model.propellerDiameter_m = aircraft.propDiameter;
    model.fittedEta = selected.predictedEta;
    model.calibrationPowerError_kW = selected.powerError_kW;
end

function result = fitCandidate(points, form, normalization)
%FITCANDIDATE Fit one form and perform all grouped checks.

    design = designMatrix(points, form, normalization);
    targetEta = points.CurrentPolarEtaImplied;
    coefficients = design \ targetEta;
    predictedEta = design * coefficients;
    powerError_kW = ...
        (predictedEta - targetEta) .* points.EnginePower_kW;

    result = struct( ...
        'form', form, ...
        'formula', formulaForForm(form), ...
        'coefficientNames', {coefficientNamesForForm(form)}, ...
        'coefficients', coefficients, ...
        'predictedEta', predictedEta, ...
        'powerError_kW', powerError_kW, ...
        'calibration', errorMetrics(powerError_kW, ...
            predictedEta - targetEta));
    result.crossValidation = struct( ...
        'altitude', groupedCrossValidation(points, form, ...
            normalization, 'Altitude_ft', 'leave-one-altitude-out'), ...
        'temperature', groupedCrossValidation(points, form, ...
            normalization, 'DeltaISA_C', ...
            'leave-one-temperature-column-out'), ...
        'rpm', groupedCrossValidation(points, form, ...
            normalization, 'RPM', 'leave-one-RPM-out'));
end

function validation = groupedCrossValidation( ...
        points, form, normalization, groupVariable, schemeName)
%GROUPEDCROSSVALIDATION Hold out complete operating-condition groups.

    group = points.(groupVariable);
    groupValues = unique(group);
    numberGroups = numel(groupValues);
    numberPoints = height(points);
    predictedEta = nan(numberPoints, 1);

    numberHeldOut = zeros(numberGroups, 1);
    rmsPowerError_kW = zeros(numberGroups, 1);
    meanAbsolutePowerError_kW = zeros(numberGroups, 1);
    maximumAbsolutePowerError_kW = zeros(numberGroups, 1);
    meanPowerError_kW = zeros(numberGroups, 1);
    etaRMSE = zeros(numberGroups, 1);

    for groupIndex = 1:numberGroups
        validationMask = group == groupValues(groupIndex);
        calibrationMask = ~validationMask;
        calibrationDesign = designMatrix( ...
            points(calibrationMask, :), form, normalization);
        coefficients = calibrationDesign \ ...
            points.CurrentPolarEtaImplied(calibrationMask);
        validationDesign = designMatrix( ...
            points(validationMask, :), form, normalization);
        predictedEta(validationMask) = validationDesign * coefficients;

        etaError = predictedEta(validationMask) - ...
            points.CurrentPolarEtaImplied(validationMask);
        powerError = etaError .* points.EnginePower_kW(validationMask);
        foldMetrics = errorMetrics(powerError, etaError);
        numberHeldOut(groupIndex) = sum(validationMask);
        rmsPowerError_kW(groupIndex) = foldMetrics.rmsPowerError_kW;
        meanAbsolutePowerError_kW(groupIndex) = ...
            foldMetrics.meanAbsolutePowerError_kW;
        maximumAbsolutePowerError_kW(groupIndex) = ...
            foldMetrics.maximumAbsolutePowerError_kW;
        meanPowerError_kW(groupIndex) = foldMetrics.meanPowerError_kW;
        etaRMSE(groupIndex) = foldMetrics.etaRMSE;
    end

    etaError = predictedEta - points.CurrentPolarEtaImplied;
    powerError_kW = etaError .* points.EnginePower_kW;
    scheme = repmat({schemeName}, numberGroups, 1);
    folds = table(scheme, groupValues, numberHeldOut, ...
        rmsPowerError_kW, meanAbsolutePowerError_kW, ...
        maximumAbsolutePowerError_kW, meanPowerError_kW, etaRMSE, ...
        'VariableNames', { ...
            'Scheme', 'GroupValue', 'NumberHeldOut', ...
            'RMSPowerError_kW', 'MeanAbsolutePowerError_kW', ...
            'MaximumAbsolutePowerError_kW', 'MeanPowerError_kW', ...
            'EtaRMSE'});

    validation = struct( ...
        'scheme', schemeName, ...
        'groupVariable', groupVariable, ...
        'predictedEta', predictedEta, ...
        'powerError_kW', powerError_kW, ...
        'metrics', errorMetrics(powerError_kW, etaError), ...
        'folds', folds);
end

function design = designMatrix(points, form, normalization)
%DESIGNMATRIX Construct transparent low-order regression terms.

    xJ = points.AdvanceRatio - normalization.advanceRatioCenter;
    xRPM = (points.RPM - normalization.rpmCenter) ./ ...
        normalization.rpmScale;
    xDensity = (points.Density_kgpm3 - ...
        normalization.densityCenter_kgpm3) ./ ...
        normalization.densityScale_kgpm3;

    switch form
        case 'j-linear'
            design = [ones(height(points), 1), xJ];
        case 'j-quadratic'
            design = [ones(height(points), 1), xJ, xJ.^2];
        case 'j-cubic'
            design = [ones(height(points), 1), xJ, xJ.^2, xJ.^3];
        case 'j2-rpm-density'
            design = [ones(height(points), 1), xJ, xJ.^2, ...
                xRPM, xDensity];
        otherwise
            error('fitEffectiveCruiseModel:UnknownForm', ...
                'Unknown model form: %s.', form);
    end
end

function names = coefficientNamesForForm(form)
    switch form
        case 'j-linear'
            names = {'intercept', 'J-centered'};
        case 'j-quadratic'
            names = {'intercept', 'J-centered', 'J-centered squared'};
        case 'j-cubic'
            names = {'intercept', 'J-centered', ...
                'J-centered squared', 'J-centered cubed'};
        case 'j2-rpm-density'
            names = {'intercept', 'J-centered', ...
                'J-centered squared', 'RPM-normalized', ...
                'density-normalized'};
        otherwise
            error('fitEffectiveCruiseModel:UnknownForm', ...
                'Unknown model form: %s.', form);
    end
end

function formula = formulaForForm(form)
    switch form
        case 'j-linear'
            formula = 'b0 + b1 (J - 0.70)';
        case 'j-quadratic'
            formula = 'b0 + b1 (J - 0.70) + b2 (J - 0.70)^2';
        case 'j-cubic'
            formula = ...
                'b0 + b1 (J - 0.70) + b2 (J - 0.70)^2 + b3 (J - 0.70)^3';
        case 'j2-rpm-density'
            formula = [ ...
                'b0 + b1 (J - 0.70) + b2 (J - 0.70)^2 + ' ...
                'b3 (RPM - 2400)/300 + b4 (rho - 1.00)/0.20'];
        otherwise
            error('fitEffectiveCruiseModel:UnknownForm', ...
                'Unknown model form: %s.', form);
    end
end

function metrics = errorMetrics(powerError_kW, etaError)
    metrics = struct( ...
        'meanPowerError_kW', mean(powerError_kW), ...
        'rmsPowerError_kW', sqrt(mean(powerError_kW.^2)), ...
        'meanAbsolutePowerError_kW', mean(abs(powerError_kW)), ...
        'maximumAbsolutePowerError_kW', max(abs(powerError_kW)), ...
        'etaRMSE', sqrt(mean(etaError.^2)));
end

function validatePointTable(points, requiredVariables)
    if ~istable(points)
        error('fitEffectiveCruiseModel:InvalidPoints', ...
            'points must be the table returned in cruiseAccuracyAudit().');
    end
    missing = requiredVariables(~ismember( ...
        requiredVariables, points.Properties.VariableNames));
    if ~isempty(missing)
        error('fitEffectiveCruiseModel:MissingVariables', ...
            'The point table is missing required variable: %s.', ...
            missing{1});
    end
    if height(points) < 20
        error('fitEffectiveCruiseModel:InsufficientPoints', ...
            'At least 20 calibration points are required.');
    end
end
