function model = fitEffectiveCruiseSpeedModel(points)
%FITEFFECTIVECRUISESPEEDMODEL Fit and validate cruise-speed inversion.
%
%   MODEL = FITEFFECTIVECRUISESPEEDMODEL() uses all 111 C172S POH Figure
%   5-8 points. MODEL = FITEFFECTIVECRUISESPEEDMODEL(POINTS) accepts the
%   audit-point table explicitly.
%
%   The six-term effective-efficiency surface is
%
%     b0 + b1*xJ + b2*xJ^2 + b3*xJ^3 + b4*xRPM + b5*xRho.
%
%   The cubic advance-ratio term is retained because speed inversion
%   requires stable local power-curve slope as well as small pointwise
%   closure error. The model is validated by solving KTAS with complete
%   altitude, temperature-column, and RPM groups held out.

    if nargin < 1 || isempty(points)
        audit = cruiseAccuracyAudit();
        points = audit.points;
    end
    validatePoints(points);

    normalization = struct( ...
        'advanceRatioCenter', 0.70, ...
        'rpmCenter', 2400, ...
        'rpmScale', 300, ...
        'densityCenter_kgpm3', 1.00, ...
        'densityScale_kgpm3', 0.20);
    coefficients = designMatrix(points, normalization) \ ...
        points.CurrentPolarEtaImplied;
    model = buildModel(coefficients, points, normalization);

    fittedEta = designMatrix(points, normalization) * coefficients;
    calibrationPowerError_kW = ...
        (fittedEta - points.CurrentPolarEtaImplied) .* ...
        points.EnginePower_kW;
    model.powerClosure = powerMetrics(calibrationPowerError_kW);

    [predictedKTAS, usedGuardBand] = predictPoints(points, model);
    model.speedCalibration = speedMetrics( ...
        predictedKTAS, points.POH_KTAS, usedGuardBand);
    model.speedCalibration.predictedKTAS = predictedKTAS;

    model.crossValidation = struct( ...
        'altitude', groupedValidation(points, normalization, ...
            'Altitude_ft', 'leave-one-altitude-out'), ...
        'temperature', groupedValidation(points, normalization, ...
            'DeltaISA_C', 'leave-one-temperature-column-out'), ...
        'rpm', groupedValidation(points, normalization, ...
            'RPM', 'leave-one-RPM-out'));

    rmsGate_KTAS = 2.0;
    maximumGate_KTAS = 4.0;
    validations = {model.speedCalibration, ...
        model.crossValidation.altitude.metrics, ...
        model.crossValidation.temperature.metrics, ...
        model.crossValidation.rpm.metrics};
    passes = true;
    for validationIndex = 1:numel(validations)
        metrics = validations{validationIndex};
        passes = passes && metrics.coverageFraction == 1 && ...
            metrics.rmsError_KTAS <= rmsGate_KTAS && ...
            metrics.maximumAbsoluteError_KTAS <= maximumGate_KTAS;
    end
    model.rmsSpeedGate_KTAS = rmsGate_KTAS;
    model.maximumSpeedGate_KTAS = maximumGate_KTAS;
    model.passesSpeedValidation = passes;
    if passes
        model.validationStatus = ...
            'PASS - calibration and every grouped speed holdout satisfy gates';
    else
        model.validationStatus = ...
            'FAIL - speed model is not approved for application output';
    end
end

function validation = groupedValidation( ...
        points, normalization, groupVariable, schemeName)

    group = points.(groupVariable);
    groupValues = unique(group);
    predictedKTAS = nan(height(points), 1);
    usedGuardBand = false(height(points), 1);
    numberGroups = numel(groupValues);
    foldRMS_KTAS = nan(numberGroups, 1);
    foldMaximum_KTAS = nan(numberGroups, 1);
    foldCoverage = zeros(numberGroups, 1);
    numberHeldOut = zeros(numberGroups, 1);

    for groupIndex = 1:numberGroups
        heldOut = group == groupValues(groupIndex);
        calibration = ~heldOut;
        coefficients = designMatrix( ...
            points(calibration, :), normalization) \ ...
            points.CurrentPolarEtaImplied(calibration);
        foldModel = buildModel(coefficients, points, normalization);
        [foldPrediction, foldGuardBand] = predictPoints( ...
            points(heldOut, :), foldModel);
        predictedKTAS(heldOut) = foldPrediction;
        usedGuardBand(heldOut) = foldGuardBand;
        foldMetrics = speedMetrics(foldPrediction, ...
            points.POH_KTAS(heldOut), foldGuardBand);
        numberHeldOut(groupIndex) = sum(heldOut);
        foldRMS_KTAS(groupIndex) = foldMetrics.rmsError_KTAS;
        foldMaximum_KTAS(groupIndex) = ...
            foldMetrics.maximumAbsoluteError_KTAS;
        foldCoverage(groupIndex) = foldMetrics.coverageFraction;
    end

    scheme = repmat({schemeName}, numberGroups, 1);
    folds = table(scheme, groupValues, numberHeldOut, ...
        foldRMS_KTAS, foldMaximum_KTAS, foldCoverage, ...
        'VariableNames', {'Scheme', 'GroupValue', 'NumberHeldOut', ...
            'RMS_KTAS', 'MaximumAbsolute_KTAS', 'CoverageFraction'});
    validation = struct( ...
        'scheme', schemeName, ...
        'groupVariable', groupVariable, ...
        'predictedKTAS', predictedKTAS, ...
        'usedGuardBand', usedGuardBand, ...
        'metrics', speedMetrics(predictedKTAS, ...
            points.POH_KTAS, usedGuardBand), ...
        'folds', folds);
end

function [predictedKTAS, usedGuardBand] = predictPoints(points, model)

    numberPoints = height(points);
    predictedKTAS = nan(numberPoints, 1);
    usedGuardBand = false(numberPoints, 1);
    for pointIndex = 1:numberPoints
        try
            [predictedKTAS(pointIndex), info] = ...
                predictEffectiveCruiseSpeed( ...
                points.Altitude_ft(pointIndex), ...
                points.RPM(pointIndex), ...
                points.DeltaISA_C(pointIndex), model);
            usedGuardBand(pointIndex) = ...
                info.usedAdvanceRatioGuardBand;
        catch ME
            if ~strcmp(ME.identifier, ...
                    'predictEffectiveCruiseSpeed:NoPowerBalance')
                rethrow(ME)
            end
        end
    end
end

function model = buildModel(coefficients, points, normalization)

    aircraft = cessna172();
    model = struct( ...
        'name', 'POH-calibrated effective cruise-speed inversion model', ...
        'form', 'J cubic + RPM + density', ...
        'formula', ['b0 + b1*xJ + b2*xJ^2 + b3*xJ^3 + ' ...
            'b4*xRPM + b5*xRho'], ...
        'coefficients', coefficients, ...
        'coefficientNames', {{'intercept', 'J-centered', ...
            'J-centered squared', 'J-centered cubed', ...
            'RPM-normalized', 'density-normalized'}}, ...
        'normalization', normalization, ...
        'propellerDiameter_m', aircraft.propDiameter, ...
        'observedAdvanceRatioRange', [min(points.AdvanceRatio), ...
            max(points.AdvanceRatio)], ...
        'advanceRatioGuardBand', 0.01, ...
        'rootSearchGridPoints', 500, ...
        'knotToMps', 0.514444, ...
        'referenceConfiguration', ...
            'C172S, 2550 lb, speed fairings installed, POH Figure 5-8', ...
        'classification', ...
            ['SEMI-EMPIRICAL/POH-CALIBRATED speed-inversion model; ' ...
             'not an independent physics prediction'], ...
        'source', ...
            ['C172S POH/AFM 172SPHBUS-02 Figure 5-8 plus current ' ...
             'conventional drag-polar assumption'], ...
        'guardBandNote', ...
            ['A 0.01 advance-ratio search guard band accommodates ' ...
             'regression residual near source-envelope endpoints. ' ...
             'Every use is reported; input-condition extrapolation ' ...
             'remains disabled.']);
end

function design = designMatrix(points, normalization)

    xJ = points.AdvanceRatio - normalization.advanceRatioCenter;
    xRPM = (points.RPM - normalization.rpmCenter) ./ ...
        normalization.rpmScale;
    xDensity = (points.Density_kgpm3 - ...
        normalization.densityCenter_kgpm3) ./ ...
        normalization.densityScale_kgpm3;
    design = [ones(height(points), 1), xJ, xJ.^2, xJ.^3, ...
        xRPM, xDensity];
end

function metrics = speedMetrics(predictedKTAS, referenceKTAS, usedGuardBand)

    valid = isfinite(predictedKTAS);
    error_KTAS = predictedKTAS(valid) - referenceKTAS(valid);
    metrics = struct( ...
        'numberPoints', numel(referenceKTAS), ...
        'numberSolved', sum(valid), ...
        'coverageFraction', sum(valid) / numel(referenceKTAS), ...
        'meanError_KTAS', mean(error_KTAS), ...
        'rmsError_KTAS', sqrt(mean(error_KTAS.^2)), ...
        'meanAbsoluteError_KTAS', mean(abs(error_KTAS)), ...
        'maximumAbsoluteError_KTAS', max(abs(error_KTAS)), ...
        'numberUsingGuardBand', sum(usedGuardBand(valid)));
end

function metrics = powerMetrics(error_kW)

    metrics = struct( ...
        'meanError_kW', mean(error_kW), ...
        'rmsError_kW', sqrt(mean(error_kW.^2)), ...
        'maximumAbsoluteError_kW', max(abs(error_kW)));
end

function validatePoints(points)

    required = {'Altitude_ft', 'DeltaISA_C', 'RPM', 'POH_KTAS', ...
        'Density_kgpm3', 'AdvanceRatio', 'EnginePower_kW', ...
        'CurrentPolarEtaImplied'};
    if ~istable(points) || ...
            ~all(ismember(required, points.Properties.VariableNames))
        error('fitEffectiveCruiseSpeedModel:InvalidPoints', ...
            'points must be the table returned by cruiseAccuracyAudit.');
    end
end
