function result = glideDescentPerformance(aircraft, ...
        startPressureAltitude_ft, terrainPressureAltitude_ft, ...
        deltaISA_C, weight_lb)
%GLIDEDESCENTPERFORMANCE Evaluate C172S glide and descent performance.
%
%   RESULT = GLIDEDESCENTPERFORMANCE(AIRCRAFT, STARTPA_FT,
%   TERRAINPA_FT, DELTAISA_C, WEIGHT_LB) returns:
%     1. The primary POH Figure 3-1 maximum-glide range.
%     2. A descent-time estimate derived from the POH chart and 68 KIAS.
%     3. Best-range and minimum-sink analytical comparisons from the
%        assumed parabolic drag polar CD = CD0 + k*CL^2.
%
%   The analytical comparisons are not POH-calibrated. In particular, the
%   clean-airframe polar does not identify windmilling-propeller drag.

    requiredFields = {'S', 'CD0', 'e', 'AR', 'CLmax', ...
        'maxGrossWeight_lb'};
    for fieldIndex = 1:numel(requiredFields)
        if ~isfield(aircraft, requiredFields{fieldIndex})
            error('glideDescentPerformance:MissingAircraftField', ...
                'aircraft.%s is required.', requiredFields{fieldIndex});
        end
    end

    validateattributes(startPressureAltitude_ft, {'numeric'}, ...
        {'real', 'finite', 'nonnegative', 'scalar'}, mfilename, ...
        'startPressureAltitude_ft', 2);
    validateattributes(terrainPressureAltitude_ft, {'numeric'}, ...
        {'real', 'finite', 'nonnegative', 'scalar'}, mfilename, ...
        'terrainPressureAltitude_ft', 3);
    validateattributes(deltaISA_C, {'numeric'}, ...
        {'real', 'finite', 'scalar'}, mfilename, 'deltaISA_C', 4);
    validateattributes(weight_lb, {'numeric'}, ...
        {'real', 'finite', 'positive', 'scalar'}, mfilename, ...
        'weight_lb', 5);

    maximumAltitude_ft = 12000;
    if isfield(aircraft, 'pohMaximumAltitude_ft')
        maximumAltitude_ft = aircraft.pohMaximumAltitude_ft;
    end
    if startPressureAltitude_ft > maximumAltitude_ft
        error('glideDescentPerformance:AltitudeOutsideModel', ...
            'Starting pressure altitude must not exceed %.0f ft.', ...
            maximumAltitude_ft);
    end
    if terrainPressureAltitude_ft > startPressureAltitude_ft
        error('glideDescentPerformance:TerrainAboveStart', ...
            ['Terrain pressure altitude must not exceed the starting ' ...
             'pressure altitude.']);
    end
    if weight_lb > aircraft.maxGrossWeight_lb
        error('glideDescentPerformance:WeightAboveMaximum', ...
            'Weight must not exceed the %.0f-lb maximum gross weight.', ...
            aircraft.maxGrossWeight_lb);
    end

    LBF_TO_N = 4.4482216152605;
    FT_TO_M = 0.3048;
    NM_TO_M = 1852;
    KT_TO_MPS = 0.514444;
    RHO0 = 1.2250;

    aircraftForCondition = aircraft;
    aircraftForCondition.W = weight_lb * LBF_TO_N;
    heightAboveTerrain_ft = ...
        startPressureAltitude_ft - terrainPressureAltitude_ft;
    heightAboveTerrain_m = heightAboveTerrain_ft * FT_TO_M;

    [~, inducedDragFactor] = dragPolar(aircraftForCondition, 0);
    bestRangeCL = sqrt(aircraftForCondition.CD0 / inducedDragFactor);
    minimumSinkCL = fminbnd( ...
        @(CL) nondimensionalSink(CL, aircraftForCondition.CD0, ...
            inducedDragFactor), ...
        max(1e-5, 1e-4 * aircraftForCondition.CLmax), ...
        aircraftForCondition.CLmax);

    integrationAltitudes_ft = linspace( ...
        terrainPressureAltitude_ft, startPressureAltitude_ft, 201);
    density_kgpm3 = zeros(size(integrationAltitudes_ft));
    for altitudeIndex = 1:numel(integrationAltitudes_ft)
        localAtmosphere = atmosphereAtPressureAltitude( ...
            integrationAltitudes_ft(altitudeIndex), deltaISA_C);
        density_kgpm3(altitudeIndex) = localAtmosphere.rho;
    end

    bestRange = buildAnalyticalStrategy('BEST RANGE', bestRangeCL, ...
        aircraftForCondition, inducedDragFactor, density_kgpm3, ...
        integrationAltitudes_ft, heightAboveTerrain_m);
    minimumSink = buildAnalyticalStrategy('MINIMUM SINK', ...
        minimumSinkCL, aircraftForCondition, inducedDragFactor, ...
        density_kgpm3, integrationAltitudes_ft, ...
        heightAboveTerrain_m);

    poh = pohMaximumGlide(heightAboveTerrain_ft);
    pohGlideAngle_rad = atan(1 / ...
        poh.glideRatio_horizontalPerVertical);
    pohTrueAirspeed_mps = poh.bestGlideSpeed_KIAS * KT_TO_MPS .* ...
        sqrt(RHO0 ./ density_kgpm3);
    pohSinkRate_mps = pohTrueAirspeed_mps .* sin(pohGlideAngle_rad);
    pohDescentTime_s = integrateTime(integrationAltitudes_ft, ...
        pohSinkRate_mps);
    if pohDescentTime_s > 0
        pohAverageSinkRate_mps = heightAboveTerrain_m / pohDescentTime_s;
    else
        pohAverageSinkRate_mps = pohSinkRate_mps(end);
    end
    poh.derivedDescentTime_min = pohDescentTime_s / 60;
    poh.startTrueAirspeed_mps = pohTrueAirspeed_mps(end);
    poh.terrainTrueAirspeed_mps = pohTrueAirspeed_mps(1);
    poh.startSinkRate_mps = pohSinkRate_mps(end);
    poh.averageSinkRate_mps = pohAverageSinkRate_mps;
    poh.timeClassification = ...
        'DERIVED FROM POH CHART; 68 KIAS APPROXIMATED AS 68 KEAS';

    if poh.groundDistance_nm > 0
        rangeDifference_percent = 100 * ...
            (bestRange.range_nm - poh.groundDistance_nm) / ...
            poh.groundDistance_nm;
    else
        rangeDifference_percent = NaN;
    end

    result = struct( ...
        'startPressureAltitude_ft', startPressureAltitude_ft, ...
        'terrainPressureAltitude_ft', terrainPressureAltitude_ft, ...
        'heightAboveTerrain_ft', heightAboveTerrain_ft, ...
        'deltaISA_C', deltaISA_C, ...
        'weight_lb', weight_lb, ...
        'startAtmosphere', atmosphereAtPressureAltitude( ...
            startPressureAltitude_ft, deltaISA_C), ...
        'terrainAtmosphere', atmosphereAtPressureAltitude( ...
            terrainPressureAltitude_ft, deltaISA_C), ...
        'inducedDragFactor', inducedDragFactor, ...
        'poh', poh, ...
        'bestRange', bestRange, ...
        'minimumSink', minimumSink, ...
        'comparison', struct( ...
            'bestRangeDifference_percent', rangeDifference_percent, ...
            'interpretation', ['Difference is diagnostic evidence that ' ...
                'the assumed clean-airframe polar is not a substitute ' ...
                'for the windmilling-propeller POH chart.']), ...
        'classification', ...
            'HYBRID: POH REFERENCE + ANALYTICAL/ASSUMPTION-BASED MODEL', ...
        'analyticalSource', ['AER 416 Part 6, Gliding Flight and Gliding ' ...
            'Range; parabolic drag polar uses project engineering ' ...
            'assumptions CD0 and e'], ...
        'assumptions', {{ ...
            'steady, unaccelerated engine-off glide', ...
            'pressure-altitude difference used as vertical height', ...
            'constant ISA temperature offset through the descent', ...
            'zero wind', ...
            'analytical polar excludes identified windmilling-propeller drag', ...
            '68 KIAS approximated as 68 KEAS only for derived POH time'}});
end

function strategy = buildAnalyticalStrategy(name, CL, aircraft, k, ...
        density_kgpm3, integrationAltitudes_ft, height_m)
    NM_TO_M = 1852;

    CD = aircraft.CD0 + k * CL^2;
    liftToDragRatio = CL / CD;
    glideAngle_rad = atan(CD / CL);
    trueAirspeed_mps = sqrt(2 * aircraft.W * cos(glideAngle_rad) ./ ...
        (density_kgpm3 * aircraft.S * CL));
    sinkRate_mps = trueAirspeed_mps * sin(glideAngle_rad);
    descentTime_s = integrateTime( ...
        integrationAltitudes_ft, sinkRate_mps);
    if descentTime_s > 0
        averageSinkRate_mps = height_m / descentTime_s;
    else
        averageSinkRate_mps = sinkRate_mps(end);
    end

    strategy = struct( ...
        'name', name, ...
        'liftCoefficient', CL, ...
        'dragCoefficient', CD, ...
        'liftToDragRatio', liftToDragRatio, ...
        'glideAngle_deg', rad2deg(glideAngle_rad), ...
        'startTrueAirspeed_mps', trueAirspeed_mps(end), ...
        'terrainTrueAirspeed_mps', trueAirspeed_mps(1), ...
        'startSinkRate_mps', sinkRate_mps(end), ...
        'terrainSinkRate_mps', sinkRate_mps(1), ...
        'averageSinkRate_mps', averageSinkRate_mps, ...
        'range_nm', height_m * liftToDragRatio / NM_TO_M, ...
        'descentTime_min', descentTime_s / 60, ...
        'classification', ...
            'ANALYTICAL - ASSUMED PARABOLIC DRAG POLAR; COMPARISON ONLY');
end

function time_s = integrateTime(altitudes_ft, sinkRate_mps)
    FT_TO_M = 0.3048;
    if altitudes_ft(end) == altitudes_ft(1)
        time_s = 0;
        return
    end
    altitude_m = altitudes_ft * FT_TO_M;
    time_s = trapz(altitude_m, 1 ./ sinkRate_mps);
end

function coefficient = nondimensionalSink(CL, CD0, k)
    CD = CD0 + k * CL^2;
    glideAngle_rad = atan(CD / CL);
    coefficient = sqrt(cos(glideAngle_rad) / CL) * ...
        sin(glideAngle_rad);
end
