function main()
%MAIN Interactive Cessna 172S performance analysis application.

    clc;
    close all;

    aircraft = cessna172();

    fprintf('==================================================\n');
    fprintf('      CESSNA 172S PERFORMANCE ANALYSIS TOOL\n');
    fprintf('==================================================\n\n');
    fprintf('Select analysis mode:\n');
    fprintf('  1 - Aerodynamic performance sweep\n');
    fprintf('  2 - POH cruise performance reference\n');
    fprintf('  3 - POH maximum-rate-climb reference\n');
    fprintf('  4 - Cruise model accuracy audit\n');
    fprintf('  5 - POH short-field takeoff reference\n');
    fprintf('  6 - POH short-field landing reference\n');
    fprintf('  7 - POH range, endurance, and fuel plan\n');
    fprintf('  8 - Glide and descent performance\n');
    fprintf('  9 - Steady-level turn and maneuver performance\n\n');

    mode = promptScalar('Enter selection (1 to 9): ', 1, 9);

    switch mode
        case 1
            runAerodynamicMode(aircraft);
        case 2
            runCruiseMode(aircraft);
        case 3
            runClimbMode();
        case 4
            fprintf('\n--- CRUISE MODEL ACCURACY AUDIT ---\n\n');
            runAccuracyAudit(true);
        case 5
            runTakeoffMode();
        case 6
            runLandingMode();
        case 7
            runMissionFuelMode(aircraft);
        case 8
            runGlideDescentMode(aircraft);
        case 9
            runTurnPerformanceMode(aircraft);
    end
end

function runGlideDescentMode(aircraft)
    KT_TO_MPS = 0.514444;
    MPS_TO_FPM = 196.850393700787;

    fprintf('\n--- GLIDE AND DESCENT PERFORMANCE ---\n\n');
    startPressureAltitude_ft = promptScalar( ...
        'Enter starting pressure altitude (ft, 0 to 12000): ', ...
        0, 12000, 6000);
    terrainPressureAltitude_ft = promptScalar( ...
        sprintf(['Enter terrain pressure altitude (ft, 0 to %.0f; ' ...
            'press Enter for 0): '], startPressureAltitude_ft), ...
        0, startPressureAltitude_ft, 0);
    deltaISA_C = promptScalar( ...
        'Enter ISA temperature offset (deg C, -20 to +20): ', ...
        -20, 20, 0);
    weight_lb = promptScalar( ...
        'Enter aircraft weight (lb, press Enter for 2550): ', ...
        1500, aircraft.maxGrossWeight_lb, aircraft.maxGrossWeight_lb);

    try
        glide = glideDescentPerformance(aircraft, ...
            startPressureAltitude_ft, terrainPressureAltitude_ft, ...
            deltaISA_C, weight_lb);
    catch ME
        if startsWith(ME.identifier, 'glideDescentPerformance') || ...
                startsWith(ME.identifier, 'pohMaximumGlide')
            fprintf('\nMODEL ENVELOPE ERROR:\n%s\n', ME.message);
            return
        end
        rethrow(ME)
    end

    fprintf('\n==================================================\n');
    fprintf('GLIDE AND DESCENT PERFORMANCE\n');
    fprintf('==================================================\n');
    displayAtmosphere(glide.startAtmosphere);
    fprintf('Terrain Pressure Alt.  : %.0f ft\n', ...
        glide.terrainPressureAltitude_ft);
    fprintf('Vertical Height        : %.0f ft\n', ...
        glide.heightAboveTerrain_ft);
    fprintf('Aircraft Weight        : %.0f lb\n', glide.weight_lb);

    fprintf('\nPOH MAXIMUM-GLIDE REFERENCE - FIGURE 3-1\n');
    fprintf('Best-Glide Speed       : %.0f KIAS\n', ...
        glide.poh.bestGlideSpeed_KIAS);
    fprintf('Configuration          : %s\n', glide.poh.configuration);
    fprintf('POH Zero-Wind Range    : %.2f NM\n', ...
        glide.poh.groundDistance_nm);
    fprintf('Chart Glide Ratio      : %.2f:1\n', ...
        glide.poh.glideRatio_horizontalPerVertical);
    fprintf('Chart Glide Angle      : %.2f deg\n', ...
        glide.poh.glideAngle_deg);
    fprintf('Derived Descent Time   : %.2f min [NOT A POH TABLE VALUE]\n', ...
        glide.poh.derivedDescentTime_min);
    fprintf('Start True Airspeed    : %.1f KTAS [68 KIAS approx KEAS]\n', ...
        glide.poh.startTrueAirspeed_mps / KT_TO_MPS);
    fprintf('Average Sink Rate      : %.0f ft/min [DERIVED]\n', ...
        glide.poh.averageSinkRate_mps * MPS_TO_FPM);
    fprintf('Source                 : %s [%s]\n', ...
        glide.poh.source, glide.poh.classification);

    fprintf('\nANALYTICAL BEST-RANGE GLIDE - COMPARISON ONLY\n');
    displayGlideStrategy(glide.bestRange, KT_TO_MPS, MPS_TO_FPM);
    fprintf('Range Difference vs POH: %+.1f %%\n', ...
        glide.comparison.bestRangeDifference_percent);

    fprintf('\nANALYTICAL MINIMUM-SINK GLIDE - COMPARISON ONLY\n');
    displayGlideStrategy(glide.minimumSink, KT_TO_MPS, MPS_TO_FPM);

    fprintf('\nClassification        : %s\n', glide.classification);
    fprintf(['The POH Figure 3-1 result is primary. The analytical results ' ...
        'use the assumed clean-airframe parabolic drag polar and do not ' ...
        'model windmilling-propeller drag. They are not calibrated to the ' ...
        'POH glide chart and must not replace the published 68 KIAS ' ...
        'procedure. Zero wind is retained; no unsupported wind or weight ' ...
        'correction is applied to the POH chart.\n']);
end

function displayGlideStrategy(strategy, KT_TO_MPS, MPS_TO_FPM)
    fprintf('Lift Coefficient       : %.4f\n', strategy.liftCoefficient);
    fprintf('Drag Coefficient       : %.4f\n', strategy.dragCoefficient);
    fprintf('Glide Ratio, L/D       : %.2f:1\n', strategy.liftToDragRatio);
    fprintf('Glide Angle            : %.2f deg\n', ...
        strategy.glideAngle_deg);
    fprintf('Start True Airspeed    : %.1f KTAS\n', ...
        strategy.startTrueAirspeed_mps / KT_TO_MPS);
    fprintf('Start Sink Rate        : %.0f ft/min\n', ...
        strategy.startSinkRate_mps * MPS_TO_FPM);
    fprintf('Zero-Wind Range        : %.2f NM\n', strategy.range_nm);
    fprintf('Integrated Descent Time: %.2f min\n', strategy.descentTime_min);
    fprintf('Classification        : %s\n', strategy.classification);
end

function runTurnPerformanceMode(aircraft)
    M_TO_FT = 1 / 0.3048;
    M_TO_NM = 1 / 1852;

    fprintf('\n--- STEADY-LEVEL TURN AND MANEUVER PERFORMANCE ---\n\n');
    pressureAltitude_ft = promptScalar( ...
        'Enter pressure altitude (ft, 0 to 12000): ', ...
        0, 12000, 0);
    deltaISA_C = promptScalar( ...
        'Enter ISA temperature offset (deg C, -20 to +20): ', ...
        -20, 20, 0);
    weight_lb = promptScalar( ...
        'Enter aircraft weight (lb, 1900 to 2550): ', ...
        1900, aircraft.maxGrossWeight_lb, aircraft.maxGrossWeight_lb);
    airspeed_KCAS = promptScalar( ...
        'Enter calibrated airspeed (KCAS, greater than 0 to 160): ', ...
        eps, 160, 95);
    bankAngle_deg = promptScalar( ...
        'Enter bank angle (deg, 0 to 60): ', 0, 60, 45);

    try
        turn = turnPerformance(aircraft, pressureAltitude_ft, ...
            deltaISA_C, weight_lb, airspeed_KCAS, bankAngle_deg);
    catch ME
        if startsWith(ME.identifier, 'turnPerformance') || ...
                startsWith(ME.identifier, 'pohManeuverLimits')
            fprintf('\nMODEL ENVELOPE ERROR:\n%s\n', ME.message);
            return
        end
        rethrow(ME)
    end

    if turn.turnFeasible
        feasibilityText = ...
            'PASS - requested steady level turn is within modeled limits';
        geometryQualifier = '';
    else
        feasibilityText = ...
            'FAIL - accelerated stall occurs before requested load factor';
        geometryQualifier = ...
            ' [MATHEMATICAL REQUEST; NOT SUSTAINABLE]';
    end

    fprintf('\n==================================================\n');
    fprintf('STEADY-LEVEL TURN AND MANEUVER PERFORMANCE\n');
    fprintf('==================================================\n');
    displayAtmosphere(turn.atmosphere);
    fprintf('Aircraft Weight        : %.0f lb\n', turn.weight_lb);
    fprintf('Selected Airspeed      : %.1f KCAS\n', turn.airspeed_KCAS);
    fprintf('Selected Bank Angle    : %.1f deg\n', turn.bankAngle_deg);

    fprintf('\nPOH NORMAL-CATEGORY LIMITS\n');
    fprintf('Maneuvering Speed, VA  : %.1f KCAS / %.1f KIAS\n', ...
        turn.pohLimits.maneuveringSpeed_KCAS, ...
        turn.pohLimits.maneuveringSpeed_KIAS);
    fprintf('Maximum Structural Cru.: %.0f KCAS / %.0f KIAS\n', ...
        turn.pohLimits.maximumStructuralCruisingSpeed_KCAS, ...
        turn.pohLimits.maximumStructuralCruisingSpeed_KIAS);
    fprintf('Never-Exceed Speed     : %.0f KCAS / %.0f KIAS\n', ...
        turn.pohLimits.neverExceedSpeed_KCAS, ...
        turn.pohLimits.neverExceedSpeed_KIAS);
    fprintf('Flaps-Up Load Factors  : %+.2f / %+.2f g\n', ...
        turn.pohLimits.positiveLoadFactorLimit_g, ...
        turn.pohLimits.negativeLoadFactorLimit_g);
    fprintf('Normal-Category Bank   : not more than %.0f deg\n', ...
        turn.pohLimits.maximumNormalCategoryBankAngle_deg);
    fprintf('VA Data Treatment      : %s\n', ...
        turn.pohLimits.interpolationStatus);
    fprintf('Source                 : %s [%s]\n', ...
        turn.pohLimits.source, turn.pohLimits.classification);

    fprintf('\nANALYTICAL COORDINATED LEVEL TURN\n');
    fprintf('Load Factor            : %.3f g\n', turn.loadFactor_g);
    fprintf('Weight-Adjusted VS1    : %.2f KCAS\n', ...
        turn.levelStallSpeed_KCAS);
    fprintf('Accelerated Stall Speed: %.2f KCAS\n', ...
        turn.acceleratedStallSpeed_KCAS);
    fprintf('True Airspeed          : %.2f KTAS [KCAS approx KEAS]\n', ...
        turn.trueAirspeed_KTAS);
    if isfinite(turn.turnRadius_m)
        fprintf('Turn Radius            : %.0f ft / %.3f NM%s\n', ...
            turn.turnRadius_m * M_TO_FT, ...
            turn.turnRadius_m * M_TO_NM, geometryQualifier);
        fprintf('Turn Rate              : %.2f deg/s%s\n', ...
            turn.turnRate_degps, geometryQualifier);
        fprintf('Time for 360 deg       : %.1f s%s\n', ...
            turn.timeFor360_s, geometryQualifier);
    else
        fprintf('Turn Radius            : infinite (wings level)\n');
        fprintf('Turn Rate              : 0.00 deg/s\n');
        fprintf('Time for 360 deg       : infinite (wings level)\n');
    end
    fprintf('Maximum Permitted Bank : %.2f deg at selected speed\n', ...
        turn.maximumPermittedBankAngle_deg);
    fprintf('Stall-Speed Margin     : %+.2f KCAS\n', ...
        turn.stallSpeedMargin_KCAS);
    fprintf('Turn Status            : %s\n', feasibilityText);
    fprintf('Airspeed Region        : %s\n', turn.airspeedRegion);
    fprintf('Classification         : %s\n', turn.classification);
    fprintf(['\nThe POH limits are primary. Radius, rate, load factor, and ' ...
        'accelerated-stall quantities are analytical results for a steady, ' ...
        'coordinated, constant-altitude turn in still air. KCAS is treated ' ...
        'as KEAS only when deriving TAS. A result above VA does not by ' ...
        'itself prohibit a smooth turn, but full or abrupt control inputs ' ...
        'are not supported there. When status is FAIL, the requested ' ...
        'radius, rate, and time are mathematical geometry only and are not ' ...
        'sustainable level-flight performance. No gust envelope or ' ...
        'utility-category extrapolation is included.\n']);
end

function runMissionFuelMode(aircraft)
    fprintf('\n--- POH RANGE, ENDURANCE, AND FUEL PLAN ---\n\n');
    departureAltitude_ft = promptScalar( ...
        'Enter departure pressure altitude (ft, 0 to 12000): ', ...
        0, 12000, 0);
    minimumCruiseAltitude_ft = max(2000, departureAltitude_ft);
    cruisePrompt = sprintf( ...
        'Enter cruise pressure altitude (ft, %.0f to 12000): ', ...
        minimumCruiseAltitude_ft);
    cruiseAltitude_ft = promptScalar( ...
        cruisePrompt, minimumCruiseAltitude_ft, 12000);
    deltaISA_C = promptScalar( ...
        'Enter ISA temperature offset (deg C, -20 to +20): ', ...
        -20, 20, 0);
    rpm = promptScalar( ...
        'Enter cruise engine speed (RPM, 2100 to 2700): ', ...
        2100, 2700, 2400);
    routeDistance_nm = promptScalar( ...
        'Enter total route distance (NM, 1 to 1000): ', ...
        1, 1000);
    headwindComponent_kt = promptScalar( ...
        ['Enter enroute wind component (kt; + headwind, ' ...
         '- tailwind): '], -100, 100, 0);
    usableFuelOnBoard_USgal = promptScalar( ...
        sprintf(['Enter usable fuel on board (US gal, 0 to %.1f; ' ...
            'press Enter for full): '], aircraft.fuelUsable_USgal), ...
        0, aircraft.fuelUsable_USgal, aircraft.fuelUsable_USgal);
    reserveTime_min = promptScalar( ...
        'Enter reserve time (min, press Enter for 45): ', ...
        0, 180, 45);
    contingencyPercent = promptScalar( ...
        ['Enter trip-fuel contingency (percent, press Enter for 10 ' ...
         'per POH variability warning): '], 0, 50, 10);
    fairingFlag = promptScalar( ...
        'Speed fairings installed? (1 = yes, 0 = no): ', 0, 1, 1);

    try
        plan = pohMissionFuelPlanning( ...
            departureAltitude_ft, cruiseAltitude_ft, deltaISA_C, ...
            rpm, routeDistance_nm, headwindComponent_kt, ...
            usableFuelOnBoard_USgal, reserveTime_min, ...
            contingencyPercent, logical(fairingFlag));
    catch ME
        if startsWith(ME.identifier, 'pohMissionFuelPlanning') || ...
                startsWith(ME.identifier, 'pohClimbFuelPerformance') || ...
                startsWith(ME.identifier, 'pohCruise')
            fprintf('\nMODEL ENVELOPE ERROR:\n%s\n', ME.message);
            return
        end
        rethrow(ME)
    end

    atmosphere = atmosphereAtPressureAltitude( ...
        cruiseAltitude_ft, deltaISA_C);
    if plan.missionFeasible
        feasibilityText = 'PASS - onboard fuel covers rounded plan';
    else
        feasibilityText = 'FAIL - additional usable fuel required';
    end
    if plan.speedFairingsInstalled
        fairingText = 'installed';
    else
        fairingText = 'not installed (-2 KTAS POH correction)';
    end

    fprintf('\n==================================================\n');
    fprintf('POH RANGE, ENDURANCE, AND FUEL PLAN\n');
    fprintf('==================================================\n');
    displayAtmosphere(atmosphere);
    fprintf('Reference Weight      : %.0f lb\n', plan.referenceWeight_lb);
    fprintf('Speed Fairings        : %s\n', fairingText);
    fprintf('Route Distance        : %.1f NM\n', plan.routeDistance_nm);
    fprintf('Wind Component        : %+.1f kt (+ headwind)\n', ...
        plan.headwindComponent_kt);

    fprintf('\nPOH CRUISE CONDITION\n');
    fprintf('Engine Speed          : %.0f RPM\n', plan.rpm);
    fprintf('Power Setting         : %.1f %%MCP\n', plan.cruise.percentMCP);
    fprintf('True Airspeed         : %.1f KTAS\n', ...
        plan.cruiseTrueAirspeed_KTAS);
    fprintf('Cruise Groundspeed    : %.1f kt\n', plan.cruiseGroundSpeed_kt);
    fprintf('Cruise Fuel Flow      : %.2f US gal/h\n', ...
        plan.cruise.fuelFlow_GPH);
    fprintf('Mixture Condition     : %s\n', plan.cruise.mixtureCondition);

    fprintf('\nCLIMB PHASE - FIGURE 5-7\n');
    fprintf('Departure / Cruise PA : %.0f / %.0f ft\n', ...
        plan.departurePressureAltitude_ft, ...
        plan.cruisePressureAltitude_ft);
    fprintf('Standard Time/Fuel/Dist: %.2f min / %.2f gal / %.2f NM\n', ...
        plan.climb.standardTime_min, ...
        plan.climb.standardFuel_USgal, ...
        plan.climb.standardDistance_nm);
    fprintf('Temperature Correction: x%.3f (%s)\n', ...
        plan.climb.temperatureCorrectionFactor, ...
        plan.climb.temperatureCorrectionStatus);
    fprintf('Corrected Time/Fuel/Dist: %.2f min / %.2f gal / %.2f NM\n', ...
        plan.climb.correctedTime_min, ...
        plan.climb.correctedFuel_USgal, ...
        plan.climb.correctedDistance_nm);
    fprintf('Climb Distance Basis  : %s\n', ...
        plan.climb.distanceWindCondition);

    fprintf('\nMISSION FUEL - UNROUNDED\n');
    fprintf('Start/Taxi/Takeoff    : %.2f US gal [POH ALLOWANCE]\n', ...
        plan.startTaxiTakeoffFuel_USgal);
    fprintf('Climb Fuel            : %.2f US gal\n', plan.climbFuel_USgal);
    fprintf('Cruise Distance/Time  : %.2f NM / %.2f h\n', ...
        plan.cruiseDistance_nm, plan.cruiseTime_h);
    fprintf('Cruise Fuel           : %.2f US gal\n', plan.cruiseFuel_USgal);
    fprintf('Nominal Trip Fuel     : %.2f US gal\n', ...
        plan.nominalTripFuel_USgal);
    fprintf('Contingency (%.1f%%)   : %.2f US gal\n', ...
        plan.contingencyPercent, plan.contingencyFuel_USgal);
    fprintf('Reserve (%.0f min)     : %.2f US gal\n', ...
        plan.reserveTime_min, plan.reserveFuel_USgal);
    fprintf('Exact Required Fuel   : %.2f US gal\n', plan.requiredFuel_USgal);

    fprintf('\nCONSERVATIVE COMPONENT-ROUNDED PLAN\n');
    fprintf('Start / Climb / Cruise: %.1f / %.1f / %.1f US gal\n', ...
        plan.planningStartFuel_USgal, ...
        plan.planningClimbFuel_USgal, ...
        plan.planningCruiseFuel_USgal);
    fprintf('Contingency / Reserve : %.1f / %.1f US gal\n', ...
        plan.planningContingencyFuel_USgal, ...
        plan.planningReserveFuel_USgal);
    fprintf('Required Usable Fuel  : %.1f US gal\n', ...
        plan.planningRequiredFuel_USgal);
    fprintf('Usable Fuel On Board  : %.1f / %.1f US gal\n', ...
        plan.usableFuelOnBoard_USgal, plan.usableFuelCapacity_USgal);
    fprintf('Planning Fuel Margin  : %+.1f US gal\n', ...
        plan.planningFuelMargin_USgal);
    fprintf('Fuel Status           : %s\n', feasibilityText);

    fprintf('\nCURRENT-CONDITION CAPABILITY\n');
    fprintf('Maximum Route Range   : %.1f NM\n', ...
        plan.maximumRouteDistance_nm);
    fprintf('Maximum Enroute Time  : %.2f h\n', ...
        plan.maximumEnrouteTime_h);
    fprintf('Policy                : %.0f-min reserve + %.1f%% contingency\n', ...
        plan.reserveTime_min, plan.contingencyPercent);
    fprintf('Classification        : %s\n', plan.classification);
    fprintf('Source                : %s\n', plan.source);
    fprintf(['\nThe range/endurance capability assumes the same altitude, RPM, ' ...
        'temperature, wind component, reserve, and contingency policy. ' ...
        'Climb distance is the POH zero-wind value; no separate descent ' ...
        'fuel credit is taken. This educational reference is not dispatch ' ...
        'or operational flight-planning authorization.\n']);
end

function runTakeoffMode()
    FT_TO_M = 0.3048;

    fprintf('\n--- POH SHORT-FIELD TAKEOFF REFERENCE ---\n\n');
    weight_lb = promptScalar( ...
        'Enter aircraft weight (lb, 2200 to 2550): ', ...
        2200, 2550, 2550);
    pressureAltitude_ft = promptScalar( ...
        'Enter pressure altitude (ft, 0 to 8000): ', 0, 8000);
    oat_C = promptScalar( ...
        'Enter outside-air temperature (deg C, 0 to 40): ', 0, 40);
    windComponent_kt = promptScalar( ...
        ['Enter runway wind component (kt; + headwind, ' ...
         '- tailwind, minimum -10): '], -10, 50, 0);
    surfaceCode = promptScalar( ...
        'Runway surface (1 = paved dry, 2 = dry grass): ', 1, 2, 1);
    if surfaceCode == 1
        runwaySurface = 'paved';
    else
        runwaySurface = 'dry grass';
    end

    takeoff = pohTakeoffPerformance(weight_lb, pressureAltitude_ft, ...
        oat_C, windComponent_kt, runwaySurface);
    isa = atmosphereAtPressureAltitude(pressureAltitude_ft, 0);
    atmosphere = atmosphereAtPressureAltitude( ...
        pressureAltitude_ft, oat_C - isa.isaTemperature_C);

    fprintf('\n==================================================\n');
    fprintf('POH SHORT-FIELD TAKEOFF REFERENCE\n');
    fprintf('==================================================\n');
    displayAtmosphere(atmosphere);
    fprintf('Aircraft Weight       : %.0f lb\n', weight_lb);
    fprintf('Runway Surface        : %s\n', runwaySurface);
    fprintf('Wind Component        : %+.1f kt (+ headwind)\n', ...
        windComponent_kt);
    fprintf('Configuration         : %s\n', takeoff.configuration);
    fprintf('Mixture Condition     : %s\n', takeoff.mixtureCondition);

    fprintf('\nLINEAR POH INTERPOLATION\n');
    fprintf('Lift-Off Speed        : %.1f KIAS\n', ...
        takeoff.interpolated.liftOffSpeed_KIAS);
    fprintf('Speed at 50 ft        : %.1f KIAS\n', ...
        takeoff.interpolated.speedAt50ft_KIAS);
    fprintf('Base Ground Roll      : %.1f ft\n', ...
        takeoff.interpolated.baseGroundRoll_ft);
    fprintf('Base Over-50-ft Dist. : %.1f ft\n', ...
        takeoff.interpolated.baseTotalOver50ft_ft);
    fprintf('Wind Correction       : %+.1f %%\n', ...
        takeoff.interpolated.windCorrectionPercent);
    fprintf('Grass Addition        : %.1f ft\n', ...
        takeoff.interpolated.grassAddition_ft);
    fprintf('Corrected Ground Roll : %d ft (%.0f m) [ROUNDED UP]\n', ...
        takeoff.interpolated.roundedUpGroundRoll_ft, ...
        ceil(takeoff.interpolated.groundRoll_ft * FT_TO_M));
    fprintf('Corrected Over 50 ft  : %d ft (%.0f m) [ROUNDED UP]\n', ...
        takeoff.interpolated.roundedUpTotalOver50ft_ft, ...
        ceil(takeoff.interpolated.totalOver50ft_ft * FT_TO_M));

    fprintf('\nCONSERVATIVE NEXT-HIGHER POH GRID\n');
    fprintf('Selected Grid         : %.0f lb, %.0f ft, %.0f deg C\n', ...
        takeoff.conservativeGrid.weight_lb, ...
        takeoff.conservativeGrid.pressureAltitude_ft, ...
        takeoff.conservativeGrid.oat_C);
    fprintf('Lift-Off / 50-ft Speed: %.0f / %.0f KIAS\n', ...
        takeoff.conservative.liftOffSpeed_KIAS, ...
        takeoff.conservative.speedAt50ft_KIAS);
    fprintf('Base Ground / Over-50 : %.0f / %.0f ft\n', ...
        takeoff.conservative.baseGroundRoll_ft, ...
        takeoff.conservative.baseTotalOver50ft_ft);
    fprintf('Corrected Ground Roll : %d ft (%.0f m) [ROUNDED UP]\n', ...
        takeoff.conservative.roundedUpGroundRoll_ft, ...
        ceil(takeoff.conservative.groundRoll_ft * FT_TO_M));
    fprintf('Corrected Over 50 ft  : %d ft (%.0f m) [ROUNDED UP]\n', ...
        takeoff.conservative.roundedUpTotalOver50ft_ft, ...
        ceil(takeoff.conservative.totalOver50ft_ft * FT_TO_M));
    fprintf('Source                : %s [POH DATA/CORRECTIONS]\n', ...
        takeoff.source);
    fprintf(['\nThese are POH reference calculations, not dispatch or ' ...
        'flight-planning authorization. Apply all current POH limitations, ' ...
        'runway slope/condition effects, and operational safety margins.\n']);
end

function runLandingMode()
    FT_TO_M = 0.3048;

    fprintf('\n--- POH SHORT-FIELD LANDING REFERENCE ---\n\n');
    pressureAltitude_ft = promptScalar( ...
        'Enter pressure altitude (ft, 0 to 8000): ', 0, 8000);
    oat_C = promptScalar( ...
        'Enter outside-air temperature (deg C, 0 to 40): ', 0, 40);
    windComponent_kt = promptScalar( ...
        ['Enter runway wind component (kt; + headwind, ' ...
         '- tailwind, minimum -10): '], -10, 50, 0);
    surfaceCode = promptScalar( ...
        'Runway surface (1 = paved dry, 2 = dry grass): ', 1, 2, 1);
    flapCode = promptScalar( ...
        'Flap configuration (1 = FULL, 2 = UP): ', 1, 2, 1);
    if surfaceCode == 1
        runwaySurface = 'paved';
    else
        runwaySurface = 'dry grass';
    end
    if flapCode == 1
        flapConfiguration = 'full';
    else
        flapConfiguration = 'up';
    end

    landing = pohLandingPerformance(pressureAltitude_ft, oat_C, ...
        windComponent_kt, runwaySurface, flapConfiguration);
    isa = atmosphereAtPressureAltitude(pressureAltitude_ft, 0);
    atmosphere = atmosphereAtPressureAltitude( ...
        pressureAltitude_ft, oat_C - isa.isaTemperature_C);

    fprintf('\n==================================================\n');
    fprintf('POH SHORT-FIELD LANDING REFERENCE\n');
    fprintf('==================================================\n');
    displayAtmosphere(atmosphere);
    fprintf('Reference Weight      : %.0f lb\n', landing.referenceWeight_lb);
    fprintf('Runway Surface        : %s\n', runwaySurface);
    fprintf('Wind Component        : %+.1f kt (+ headwind)\n', ...
        windComponent_kt);
    fprintf('Configuration         : %s\n', landing.configuration);

    fprintf('\nLINEAR POH INTERPOLATION\n');
    fprintf('Speed at 50 ft        : %.1f KIAS\n', ...
        landing.interpolated.speedAt50ft_KIAS);
    fprintf('Base Ground Roll      : %.1f ft\n', ...
        landing.interpolated.baseGroundRoll_ft);
    fprintf('Base Over-50-ft Dist. : %.1f ft\n', ...
        landing.interpolated.baseTotalOver50ft_ft);
    fprintf('Wind Correction       : %+.1f %%\n', ...
        landing.interpolated.windCorrectionPercent);
    fprintf('Grass Addition        : %.1f ft\n', ...
        landing.interpolated.grassAddition_ft);
    fprintf('Configuration Factor  : %.2f\n', ...
        landing.interpolated.configurationMultiplier);
    fprintf('Corrected Ground Roll : %d ft (%.0f m) [ROUNDED UP]\n', ...
        landing.interpolated.roundedUpGroundRoll_ft, ...
        ceil(landing.interpolated.groundRoll_ft * FT_TO_M));
    fprintf('Corrected Over 50 ft  : %d ft (%.0f m) [ROUNDED UP]\n', ...
        landing.interpolated.roundedUpTotalOver50ft_ft, ...
        ceil(landing.interpolated.totalOver50ft_ft * FT_TO_M));

    fprintf('\nCONSERVATIVE NEXT-HIGHER POH GRID\n');
    fprintf('Selected Grid         : %.0f ft, %.0f deg C\n', ...
        landing.conservativeGrid.pressureAltitude_ft, ...
        landing.conservativeGrid.oat_C);
    fprintf('Base Ground / Over-50 : %.0f / %.0f ft\n', ...
        landing.conservative.baseGroundRoll_ft, ...
        landing.conservative.baseTotalOver50ft_ft);
    fprintf('Corrected Ground Roll : %d ft (%.0f m) [ROUNDED UP]\n', ...
        landing.conservative.roundedUpGroundRoll_ft, ...
        ceil(landing.conservative.groundRoll_ft * FT_TO_M));
    fprintf('Corrected Over 50 ft  : %d ft (%.0f m) [ROUNDED UP]\n', ...
        landing.conservative.roundedUpTotalOver50ft_ft, ...
        ceil(landing.conservative.totalOver50ft_ft * FT_TO_M));
    fprintf('Source                : %s [POH DATA/CORRECTIONS]\n', ...
        landing.source);
    fprintf(['\nThese are POH reference calculations, not dispatch or ' ...
        'flight-planning authorization. Apply all current POH limitations, ' ...
        'runway slope/condition effects, and operational safety margins.\n']);
end

function runAerodynamicMode(aircraft)
    LBF_TO_N = 4.4482216152605;
    KT_TO_MPS = 0.514444;

    fprintf('\n--- AERODYNAMIC PERFORMANCE SWEEP ---\n\n');

    weight_lb = promptScalar( ...
        'Enter aircraft weight (lb, press Enter for 2550): ', ...
        1500, aircraft.maxGrossWeight_lb, aircraft.maxGrossWeight_lb);
    pressureAltitude_ft = promptScalar( ...
        'Enter pressure altitude (ft, 0 to 12000): ', 0, 12000);
    deltaISA_C = promptScalar( ...
        'Enter ISA temperature offset (deg C, -20 to +20): ', -20, 20);

    aircraft.W = weight_lb * LBF_TO_N;
    atm = atmosphereAtPressureAltitude(pressureAltitude_ft, deltaISA_C);
    performance = aerodynamicPerformance(aircraft, atm);
    outputFiles = plotAerodynamicPerformance( ...
        aircraft, atm, performance, true);

    speeds = performance.speeds;

    fprintf('\n==================================================\n');
    fprintf('AERODYNAMIC PERFORMANCE RESULTS\n');
    fprintf('==================================================\n');
    displayAtmosphere(atm);
    fprintf('Aircraft Weight       : %.0f lb (%.0f N)\n', ...
        weight_lb, aircraft.W);
    fprintf('Stall Speed            : %.2f KTAS (%.2f m/s)\n', ...
        speeds.stall_mps / KT_TO_MPS, speeds.stall_mps);
    fprintf('Minimum-Power Speed    : %.2f KTAS (%.2f m/s)\n', ...
        speeds.minimumPower_mps / KT_TO_MPS, ...
        speeds.minimumPower_mps);
    fprintf('Minimum Power Required : %.2f kW\n', ...
        speeds.minimumPower_W / 1000);
    fprintf('Minimum-Drag Speed     : %.2f KTAS (%.2f m/s)\n', ...
        speeds.minimumDrag_mps / KT_TO_MPS, ...
        speeds.minimumDrag_mps);
    fprintf('Minimum Drag           : %.1f N\n', ...
        speeds.minimumDrag_N);
    fprintf('Induced Drag Factor, k : %.5f\n', ...
        speeds.inducedDragFactor);
    fprintf('\nSaved figures:\n  %s\n  %s\n', ...
        outputFiles.dragPlot, outputFiles.powerPlot);
end

function runCruiseMode(aircraft)
    fprintf('\n--- POH CRUISE PERFORMANCE REFERENCE ---\n\n');

    pressureAltitude_ft = promptScalar( ...
        'Enter pressure altitude (ft, 2000 to 12000): ', 2000, 12000);
    deltaISA_C = promptScalar( ...
        'Enter ISA temperature offset (deg C, -20 to +20): ', -20, 20);
    rpm = promptScalar('Enter engine speed (RPM, 2100 to 2700): ', ...
        2100, 2700);
    weight_lb = promptScalar( ...
        'Enter aircraft weight (lb, press Enter for 2550): ', ...
        1500, aircraft.maxGrossWeight_lb, aircraft.maxGrossWeight_lb);
    fairingFlag = promptScalar( ...
        'Speed fairings installed? (1 = yes, 0 = no): ', 0, 1, 1);
    speedFairingsInstalled = logical(fairingFlag);

    try
        cruise = pohCruisePerformance( ...
            pressureAltitude_ft, rpm, deltaISA_C, weight_lb, ...
            speedFairingsInstalled);
    catch ME
        if startsWith(ME.identifier, 'pohCruise')
            fprintf('\nMODEL ENVELOPE ERROR:\n%s\n', ME.message);
            return
        end
        rethrow(ME)
    end

    atm = atmosphereAtPressureAltitude(pressureAltitude_ft, deltaISA_C);

    fprintf('\n==================================================\n');
    fprintf('POH CRUISE PERFORMANCE REFERENCE\n');
    fprintf('==================================================\n');
    displayAtmosphere(atm);
    fprintf('Engine Speed           : %.0f RPM\n', rpm);
    fprintf('POH Power Setting      : %.1f %%MCP [POH INTERPOLATION]\n', ...
        cruise.percentMCP);
    fprintf('POH True Airspeed      : %.1f KTAS [2550 lb, fairings]\n', ...
        cruise.referenceKTAS);
    fprintf('POH Fuel Flow          : %.2f US gal/h\n', ...
        cruise.fuelFlow_GPH);
    fprintf('Mixture Condition      : %s\n', cruise.mixtureCondition);
    fprintf('Selected Weight        : %.0f lb\n', weight_lb);
    if speedFairingsInstalled
        fairingText = 'installed';
    else
        fairingText = 'not installed (-2 KTAS POH correction)';
    end
    fprintf('Speed Fairings         : %s\n', fairingText);
    fprintf('2550-lb Fairing-Adj.   : %.1f KTAS\n', ...
        cruise.fairingAdjustedReferenceKTAS);
    if cruise.weightCorrectionAvailable
        fprintf('Selected-Config Speed  : %.1f KTAS\n', ...
            cruise.selectedConfigurationKTAS);
        if cruise.weightCorrectionApplied
            fprintf('Weight Speed Increment : %+.2f KTAS [POH APPROXIMATION]\n', ...
                cruise.weightCorrection_KTAS);
        end
    else
        fprintf('Selected-Config Speed  : unavailable\n');
    end
    fprintf('Weight Correction      : %s\n', cruise.weightCorrectionStatus);
    fprintf('Correction Basis       : %s\n', cruise.weightCorrectionRule);
    fprintf('Weight-Corr. Source    : %s\n', ...
        cruise.weightCorrectionSource);
    fprintf('Interpolation          : %s\n', cruise.interpolationMethod);
    fprintf('Source                 : %s [POH DATA/INTERPOLATION]\n', ...
        cruise.source);

    speedModel = getValidatedCruiseSpeedModel();
    [predictedKTAS, prediction] = predictEffectiveCruiseSpeed( ...
        pressureAltitude_ft, rpm, deltaISA_C, speedModel);
    predictionError_KTAS = predictedKTAS - cruise.referenceKTAS;
    groupedRMS_KTAS = [ ...
        speedModel.crossValidation.altitude.metrics.rmsError_KTAS, ...
        speedModel.crossValidation.temperature.metrics.rmsError_KTAS, ...
        speedModel.crossValidation.rpm.metrics.rmsError_KTAS];
    groupedMaximum_KTAS = [ ...
        speedModel.crossValidation.altitude.metrics.maximumAbsoluteError_KTAS, ...
        speedModel.crossValidation.temperature.metrics.maximumAbsoluteError_KTAS, ...
        speedModel.crossValidation.rpm.metrics.maximumAbsoluteError_KTAS];

    fprintf('\n--------------------------------------------------\n');
    fprintf('SEMI-EMPIRICAL CRUISE-SPEED PREDICTION\n');
    fprintf('Reference Condition    : 2550 lb, speed fairings installed\n');
    fprintf('Predicted True Airspeed: %.2f KTAS (%.2f m/s)\n', ...
        predictedKTAS, prediction.speed_mps);
    fprintf('POH Reference Airspeed : %.2f KTAS\n', cruise.referenceKTAS);
    fprintf('Prediction Error       : %+.2f KTAS\n', ...
        predictionError_KTAS);
    fprintf('Effective Eta          : %.4f [COMBINED CALIBRATED TERM]\n', ...
        prediction.effectiveEta);
    fprintf('Advance Ratio          : %.4f\n', prediction.advanceRatio);
    fprintf('Engine Brake Power     : %.2f kW\n', ...
        prediction.enginePower_W / 1000);
    fprintf('Power Required         : %.2f kW\n', ...
        prediction.powerRequired_W / 1000);
    fprintf('Power-Balance Residual : %+.6f kW\n', ...
        prediction.powerBalanceResidual_W / 1000);
    fprintf('Drag / CL / CD         : %.1f N / %.3f / %.4f\n', ...
        prediction.drag_N, prediction.liftCoefficient, ...
        prediction.dragCoefficient);
    if prediction.usedAdvanceRatioGuardBand
        advanceRatioStatus = ...
            '0.01 guard band used [REPORTED LOWER-CONFIDENCE EDGE RESULT]';
    else
        advanceRatioStatus = 'inside observed POH calibration range';
    end
    fprintf('Advance-Ratio Status   : %s\n', advanceRatioStatus);
    fprintf('Worst Grouped CV RMS   : %.3f KTAS (gate %.1f KTAS)\n', ...
        max(groupedRMS_KTAS), speedModel.rmsSpeedGate_KTAS);
    fprintf('Worst Held-Out Error   : %.3f KTAS (gate %.1f KTAS)\n', ...
        max(groupedMaximum_KTAS), speedModel.maximumSpeedGate_KTAS);
    fprintf('Validation Status      : %s\n', ...
        speedModel.validationStatus);
    fprintf('Classification         : %s\n', speedModel.classification);
    fprintf(['\nThe POH block remains the primary result. The prediction is ' ...
        'validated only for the 2550-lb, fairings-installed Figure 5-8 ' ...
        'reference configuration. Selected-weight and no-fairing ' ...
        'corrections above remain POH approximations and are not applied ' ...
        'to the semi-empirical model. The failed independent eta(J) proxy ' ...
        'remains available in accuracy-audit mode 4.\n']);
end

function model = getValidatedCruiseSpeedModel()
%GETVALIDATEDCRUISESPEEDMODEL Cache the validated model within MATLAB.

    persistent cachedModel
    if isempty(cachedModel)
        cachedModel = fitEffectiveCruiseSpeedModel();
    end
    if ~cachedModel.passesSpeedValidation
        error('main:CruiseSpeedModelFailedValidation', ...
            ['The semi-empirical cruise-speed model failed its validation ' ...
             'gate and cannot be shown in the interactive tool.']);
    end
    model = cachedModel;
end

function runClimbMode()
    KT_TO_MPS = 0.514444;

    fprintf('\n--- POH MAXIMUM-RATE-CLIMB REFERENCE ---\n\n');
    pressureAltitude_ft = promptScalar( ...
        'Enter pressure altitude (ft, 0 to 12000): ', 0, 12000);

    isaAtAltitude = atmosphereAtPressureAltitude(pressureAltitude_ft, 0);
    maximumOAT_C = 40;
    if pressureAltitude_ft > 10000
        maximumOAT_C = 20;
    end
    minimumDeltaISA_C = -20 - isaAtAltitude.isaTemperature_C;
    maximumDeltaISA_C = maximumOAT_C - isaAtAltitude.isaTemperature_C;

    deltaPrompt = sprintf( ...
        'Enter ISA offset (deg C, %.1f to %+.1f for POH data): ', ...
        minimumDeltaISA_C, maximumDeltaISA_C);
    deltaISA_C = promptScalar(deltaPrompt, ...
        minimumDeltaISA_C, maximumDeltaISA_C);

    climb = pohClimbPerformance(pressureAltitude_ft, deltaISA_C);

    fprintf('\n==================================================\n');
    fprintf('POH MAXIMUM-RATE-CLIMB REFERENCE\n');
    fprintf('==================================================\n');
    displayAtmosphere(climb.atmosphere);
    fprintf('Reference Weight       : %.0f lb\n', ...
        climb.referenceWeight_lb);
    fprintf('Configuration          : %s\n', climb.configuration);
    fprintf('Mixture Condition      : %s\n', climb.mixtureCondition);
    fprintf('Best-Rate Climb Speed  : %.1f KIAS\n', ...
        climb.climbSpeed_KIAS);
    fprintf('Estimated True Speed   : %.1f KTAS (%.2f m/s) [KIAS approx EAS]\n', ...
        climb.climbSpeed_TAS_mps / KT_TO_MPS, ...
        climb.climbSpeed_TAS_mps);
    fprintf('POH Rate of Climb      : %.1f ft/min (%.3f m/s)\n', ...
        climb.rateOfClimb_fpm, climb.rateOfClimb_mps);
    fprintf('Source                 : %s [POH DATA/INTERPOLATION]\n', ...
        climb.source);
    fprintf(['\nThis result is an interpolation of published POH data, ' ...
        'not an independent climb prediction.\n']);

    sweep = climbAltitudeSweep();
    climbPlotFile = plotPohClimbEnvelope(sweep, true);
    fprintf('\nSaved POH climb-envelope figure:\n  %s\n', climbPlotFile);
end

function displayAtmosphere(atm)
    fprintf('Pressure Altitude     : %.0f ft\n', ...
        atm.pressureAltitude_ft);
    fprintf('ISA Offset            : %+.1f deg C\n', atm.deltaISA_C);
    fprintf('Outside Temperature   : %.2f deg C\n', atm.temperature_C);
    fprintf('Pressure              : %.1f Pa\n', atm.P);
    fprintf('Density               : %.4f kg/m^3\n', atm.rho);
end
