function files = plotAerodynamicPerformance( ...
        aircraft, atm, performance, saveFigures)
%PLOTAERODYNAMICPERFORMANCE Plot drag and power-required curves.

    if nargin < 4 || isempty(saveFigures)
        saveFigures = false;
    end

    KT_TO_MPS = 0.514444;
    LBF_TO_N = 4.4482216152605;

    speed_ktas = performance.airspeed_mps / KT_TO_MPS;
    Vs_ktas = performance.speeds.stall_mps / KT_TO_MPS;
    Vmd_ktas = performance.speeds.minimumDrag_mps / KT_TO_MPS;
    Vmp_ktas = performance.speeds.minimumPower_mps / KT_TO_MPS;

    altitude_ft = 0;
    deltaISA_C = 0;
    if isfield(atm, 'pressureAltitude_ft')
        altitude_ft = atm.pressureAltitude_ft;
    end
    if isfield(atm, 'deltaISA_C')
        deltaISA_C = atm.deltaISA_C;
    end
    weight_lb = aircraft.W / LBF_TO_N;

    curveColor = [0.0000, 0.4470, 0.7410];
    markerColor = [0.8500, 0.3250, 0.0980];
    referenceColor = [0.25, 0.25, 0.25];

    dragFigure = figure('Color', 'w', 'Name', 'Drag Required', ...
        'Position', [100, 100, 1100, 700]);
    dragAxes = axes(dragFigure);
    styleAxes(dragAxes);
    plot(dragAxes, speed_ktas, performance.drag_N, ...
        'Color', curveColor, 'LineWidth', 2.4, ...
        'DisplayName', 'Drag required');
    hold on;
    plot(dragAxes, Vmd_ktas, performance.speeds.minimumDrag_N, 'o', ...
        'Color', markerColor, 'MarkerFaceColor', 'w', ...
        'MarkerSize', 9, 'LineWidth', 1.8, ...
        'DisplayName', sprintf('Minimum drag: %.1f KTAS', Vmd_ktas));
    xline(dragAxes, Vs_ktas, '--', sprintf('V_S = %.1f KTAS', Vs_ktas), ...
        'Color', referenceColor, 'LineWidth', 1.3, ...
        'LabelVerticalAlignment', 'middle', 'HandleVisibility', 'off');
    grid on;
    xlabel(dragAxes, 'True Airspeed (KTAS)', 'Color', 'k');
    ylabel(dragAxes, 'Drag Required (N)', 'Color', 'k');
    title(dragAxes, sprintf('%s Drag - %.0f ft, ISA %+.0f C, %.0f lb', ...
        aircraft.name, altitude_ft, deltaISA_C, weight_lb), 'Color', 'k');
    dragLegend = legend(dragAxes, 'Location', 'best');
    styleLegend(dragLegend);

    powerFigure = figure('Color', 'w', 'Name', 'Power Required', ...
        'Position', [140, 140, 1100, 700]);
    powerAxes = axes(powerFigure);
    styleAxes(powerAxes);
    plot(powerAxes, speed_ktas, performance.powerRequired_W / 1000, ...
        'Color', curveColor, 'LineWidth', 2.4, ...
        'DisplayName', 'Power required');
    hold on;
    plot(powerAxes, Vmp_ktas, performance.speeds.minimumPower_W / 1000, 'o', ...
        'Color', markerColor, 'MarkerFaceColor', 'w', ...
        'MarkerSize', 9, 'LineWidth', 1.8, ...
        'DisplayName', sprintf('Minimum power: %.1f KTAS', Vmp_ktas));
    xline(powerAxes, Vs_ktas, '--', ...
        sprintf('V_S = %.1f KTAS', Vs_ktas), ...
        'Color', referenceColor, 'LineWidth', 1.3, ...
        'LabelVerticalAlignment', 'middle', 'HandleVisibility', 'off');
    grid on;
    xlabel(powerAxes, 'True Airspeed (KTAS)', 'Color', 'k');
    ylabel(powerAxes, 'Power Required (kW)', 'Color', 'k');
    title(powerAxes, sprintf( ...
        '%s Power Required - %.0f ft, ISA %+.0f C, %.0f lb', ...
        aircraft.name, altitude_ft, deltaISA_C, weight_lb), 'Color', 'k');
    powerLegend = legend(powerAxes, 'Location', 'best');
    styleLegend(powerLegend);

    files = struct('dragPlot', '', 'powerPlot', '');
    if saveFigures
        projectDirectory = fileparts(mfilename('fullpath'));
        resultsDirectory = fullfile(projectDirectory, 'results');
        if ~exist(resultsDirectory, 'dir')
            mkdir(resultsDirectory);
        end

        conditionTag = sprintf('%05.0fft_%04.0flb_ISA%+03.0fC', ...
            altitude_ft, weight_lb, deltaISA_C);
        files.dragPlot = fullfile(resultsDirectory, ...
            ['drag_' conditionTag '.png']);
        files.powerPlot = fullfile(resultsDirectory, ...
            ['power_required_' conditionTag '.png']);

        exportgraphics(dragFigure, files.dragPlot, ...
            'Resolution', 300, 'BackgroundColor', 'white');
        exportgraphics(powerFigure, files.powerPlot, ...
            'Resolution', 300, 'BackgroundColor', 'white');
    end
end

function styleAxes(ax)
    set(ax, ...
        'Color', 'w', ...
        'XColor', 'k', ...
        'YColor', 'k', ...
        'GridColor', [0.75, 0.75, 0.75], ...
        'GridAlpha', 0.45, ...
        'FontName', 'Arial', ...
        'FontSize', 11, ...
        'LineWidth', 1.0, ...
        'Box', 'on');
end

function styleLegend(legendHandle)
    set(legendHandle, ...
        'Color', 'w', ...
        'TextColor', 'k', ...
        'EdgeColor', [0.35, 0.35, 0.35]);
end
