function climb = pohClimbPerformance(pressureAltitude_ft, deltaISA_C)
%POHCLIMBPERFORMANCE Interpolate C172S maximum-rate-climb POH data.
%
%   CLIMB = POHCLIMBPERFORMANCE(PRESSUREALTITUDE_FT, DELTAISA_C)
%   interpolates Figure 5-6 of the C172S POH at 2550 lb. The table uses
%   actual outside-air temperature, so DELTAISA_C is converted internally.
%
%   This function is a POH reference tool, not an independent climb model.

    if nargin < 2 || isempty(deltaISA_C)
        deltaISA_C = 0;
    end

    validateattributes(pressureAltitude_ft, {'numeric'}, ...
        {'real', 'finite', 'scalar', '>=', 0, '<=', 12000}, ...
        mfilename, 'pressureAltitude_ft', 1);
    validateattributes(deltaISA_C, {'numeric'}, ...
        {'real', 'finite', 'scalar'}, ...
        mfilename, 'deltaISA_C', 2);

    altitudeGrid_ft = [0, 2000, 4000, 6000, 8000, 10000, 12000];
    climbSpeed_KIAS = [74, 73, 73, 73, 72, 72, 72];
    temperatureGrid_C = [-20, 0, 20, 40];
    rateOfClimb_fpm = [ ...
        855, 785, 710, 645; ...
        760, 695, 625, 560; ...
        685, 620, 555, 495; ...
        575, 515, 450, 390; ...
        465, 405, 345, 285; ...
        360, 300, 240, 180; ...
        255, 195, 135, NaN];

    atm = atmosphereAtPressureAltitude(pressureAltitude_ft, deltaISA_C);
    outsideAirTemperature_C = atm.temperature_C;

    [referenceRateOfClimb_fpm, validOATRange_C] = interpolateClimbRate( ...
        pressureAltitude_ft, outsideAirTemperature_C, ...
        altitudeGrid_ft, temperatureGrid_C, rateOfClimb_fpm);

    referenceClimbSpeed_KIAS = interp1( ...
        altitudeGrid_ft, climbSpeed_KIAS, pressureAltitude_ft, 'linear');

    % At C172 climb speeds, KIAS is treated as equivalent airspeed. This is
    % converted to an estimated true airspeed using the density ratio.
    RHO0 = 1.225;
    KT_TO_MPS = 0.514444;
    referenceClimbSpeed_mps = referenceClimbSpeed_KIAS * KT_TO_MPS * ...
        sqrt(RHO0 / atm.rho);

    climb = struct( ...
        'source', 'C172S POH Figure 5-6', ...
        'configuration', 'Flaps up, full throttle', ...
        'mixtureCondition', ...
            'Mixture leaned above 3000 ft pressure altitude for maximum RPM', ...
        'referenceWeight_lb', 2550, ...
        'pressureAltitude_ft', pressureAltitude_ft, ...
        'deltaISA_C', deltaISA_C, ...
        'outsideAirTemperature_C', outsideAirTemperature_C, ...
        'validOATRange_C', validOATRange_C, ...
        'climbSpeed_KIAS', referenceClimbSpeed_KIAS, ...
        'climbSpeed_TAS_mps', referenceClimbSpeed_mps, ...
        'rateOfClimb_fpm', referenceRateOfClimb_fpm, ...
        'rateOfClimb_mps', referenceRateOfClimb_fpm * 0.00508, ...
        'atmosphere', atm);
end

function [roc_fpm, validTemperatureRange_C] = interpolateClimbRate( ...
        altitude_ft, temperature_C, altitudeGrid_ft, ...
        temperatureGrid_C, rocTable_fpm)
%INTERPOLATECLIMBRATE Bilinear interpolation without extrapolation.

    lowerIndex = find(altitudeGrid_ft <= altitude_ft, 1, 'last');
    upperIndex = find(altitudeGrid_ft >= altitude_ft, 1, 'first');
    rowIndices = unique([lowerIndex, upperIndex]);

    rowValues = zeros(size(rowIndices));
    minimumValidTemperature_C = -Inf;
    maximumValidTemperature_C = Inf;

    for k = 1:numel(rowIndices)
        row = rowIndices(k);
        valid = isfinite(rocTable_fpm(row, :));
        validTemperatures_C = temperatureGrid_C(valid);
        validRates_fpm = rocTable_fpm(row, valid);

        minimumValidTemperature_C = max( ...
            minimumValidTemperature_C, min(validTemperatures_C));
        maximumValidTemperature_C = min( ...
            maximumValidTemperature_C, max(validTemperatures_C));

        if temperature_C < min(validTemperatures_C) || ...
                temperature_C > max(validTemperatures_C)
            error('pohClimbPerformance:TemperatureOutsidePOH', ...
                ['The requested OAT of %.1f deg C is outside the POH ' ...
                 'range available near %.0f ft (%.0f to %.0f deg C).'], ...
                temperature_C, altitude_ft, min(validTemperatures_C), ...
                max(validTemperatures_C));
        end

        rowValues(k) = interp1(validTemperatures_C, validRates_fpm, ...
            temperature_C, 'linear');
    end

    validTemperatureRange_C = [minimumValidTemperature_C, ...
        maximumValidTemperature_C];

    if lowerIndex == upperIndex
        roc_fpm = rowValues(1);
    else
        roc_fpm = interp1(altitudeGrid_ft(rowIndices), rowValues, ...
            altitude_ft, 'linear');
    end
end
