function climb = pohClimbFuelPerformance( ...
        departurePressureAltitude_ft, cruisePressureAltitude_ft, ...
        deltaISA_C)
%POHCLIMBFUELPERFORMANCE Interpolate POH time, fuel, and distance to climb.
%
%   CLIMB = POHCLIMBFUELPERFORMANCE(DEPARTUREALTITUDE_FT,
%   CRUISEALTITUDE_FT, DELTAISA_C) differences the Figure 5-7 cumulative
%   values at the two pressure altitudes. Linear interpolation is used
%   between published 1000-ft rows; values are never extrapolated.
%
%   Figure 5-7 instructs increasing time, fuel, and distance by 10 percent
%   for each 10 C above standard. The POH does not publish a corresponding
%   reduction below standard, so this function takes no cold-day credit.
%   Distance remains the POH zero-wind climb distance.

    validateattributes(departurePressureAltitude_ft, {'numeric'}, ...
        {'real', 'finite', 'scalar'}, mfilename, ...
        'departurePressureAltitude_ft', 1);
    validateattributes(cruisePressureAltitude_ft, {'numeric'}, ...
        {'real', 'finite', 'scalar'}, mfilename, ...
        'cruisePressureAltitude_ft', 2);
    validateattributes(deltaISA_C, {'numeric'}, ...
        {'real', 'finite', 'scalar'}, mfilename, 'deltaISA_C', 3);

    data = pohClimbFuelData();
    minimumAltitude_ft = data.pressureAltitude_ft(1);
    maximumAltitude_ft = data.pressureAltitude_ft(end);
    if departurePressureAltitude_ft < minimumAltitude_ft || ...
            departurePressureAltitude_ft > maximumAltitude_ft
        error('pohClimbFuelPerformance:DepartureOutsidePOH', ...
            'Departure pressure altitude must be from 0 to 12000 ft.');
    end
    if cruisePressureAltitude_ft < minimumAltitude_ft || ...
            cruisePressureAltitude_ft > maximumAltitude_ft
        error('pohClimbFuelPerformance:CruiseOutsidePOH', ...
            'Cruise pressure altitude must be from 0 to 12000 ft.');
    end
    if cruisePressureAltitude_ft < departurePressureAltitude_ft
        error('pohClimbFuelPerformance:DescendingRoute', ...
            ['Cruise pressure altitude must be at or above the departure ' ...
             'pressure altitude for a climb calculation.']);
    end

    altitudeGrid = data.pressureAltitude_ft;
    departureTime_min = interp1(altitudeGrid, ...
        data.timeFromSeaLevel_min, departurePressureAltitude_ft, 'linear');
    cruiseTime_min = interp1(altitudeGrid, ...
        data.timeFromSeaLevel_min, cruisePressureAltitude_ft, 'linear');
    departureFuel_USgal = interp1(altitudeGrid, ...
        data.fuelFromSeaLevel_USgal, departurePressureAltitude_ft, 'linear');
    cruiseFuel_USgal = interp1(altitudeGrid, ...
        data.fuelFromSeaLevel_USgal, cruisePressureAltitude_ft, 'linear');
    departureDistance_nm = interp1(altitudeGrid, ...
        data.distanceFromSeaLevel_nm, departurePressureAltitude_ft, 'linear');
    cruiseDistance_nm = interp1(altitudeGrid, ...
        data.distanceFromSeaLevel_nm, cruisePressureAltitude_ft, 'linear');

    standardTime_min = cruiseTime_min - departureTime_min;
    standardFuel_USgal = cruiseFuel_USgal - departureFuel_USgal;
    standardDistance_nm = cruiseDistance_nm - departureDistance_nm;

    positiveDeltaISA_C = max(deltaISA_C, 0);
    temperatureCorrectionFactor = 1 + ...
        positiveDeltaISA_C * data.hotDayCorrectionPer10C / 10;
    correctedTime_min = standardTime_min * temperatureCorrectionFactor;
    correctedFuel_USgal = standardFuel_USgal * temperatureCorrectionFactor;
    correctedDistance_nm = ...
        standardDistance_nm * temperatureCorrectionFactor;

    if deltaISA_C > 0
        correctionStatus = sprintf( ...
            'POH hot-day correction applied: +%.1f%%', ...
            (temperatureCorrectionFactor - 1) * 100);
    else
        correctionStatus = ...
            'No correction: POH publishes no reduction at/below ISA';
    end

    climb = struct( ...
        'departurePressureAltitude_ft', departurePressureAltitude_ft, ...
        'cruisePressureAltitude_ft', cruisePressureAltitude_ft, ...
        'deltaISA_C', deltaISA_C, ...
        'referenceWeight_lb', data.referenceWeight_lb, ...
        'configuration', data.configuration, ...
        'mixtureCondition', data.mixtureCondition, ...
        'standardTime_min', standardTime_min, ...
        'standardFuel_USgal', standardFuel_USgal, ...
        'standardDistance_nm', standardDistance_nm, ...
        'temperatureCorrectionFactor', temperatureCorrectionFactor, ...
        'temperatureCorrectionStatus', correctionStatus, ...
        'correctedTime_min', correctedTime_min, ...
        'correctedFuel_USgal', correctedFuel_USgal, ...
        'correctedDistance_nm', correctedDistance_nm, ...
        'planningTime_min', roundUpToTenth(correctedTime_min), ...
        'planningFuel_USgal', roundUpToTenth(correctedFuel_USgal), ...
        'planningDistance_nm', ceil(correctedDistance_nm), ...
        'distanceWindCondition', data.distanceWindCondition, ...
        'startTaxiTakeoffAllowance_USgal', ...
            data.startTaxiTakeoffAllowance_USgal, ...
        'interpolationMethod', 'linear interpolation; no extrapolation', ...
        'classification', 'POH DATA/INTERPOLATION AND PUBLISHED CORRECTION', ...
        'source', data.source);
end

function roundedValue = roundUpToTenth(value)
%ROUNDUPTOTENTH Round a nonnegative planning value upward to 0.1.

    roundedValue = ceil((value - 1e-12) * 10) / 10;
end
