function landing = pohLandingPerformance( ...
        pressureAltitude_ft, oat_C, windComponent_kt, ...
        runwaySurface, flapConfiguration)
%POHLANDINGPERFORMANCE POH-backed C172S short-field landing reference.
%
%   LANDING = POHLANDINGPERFORMANCE(ALTITUDE_FT, OAT_C, WIND_KT,
%   SURFACE, FLAPS) interpolates C172S POH Figure 5-11 without
%   extrapolation. Positive WIND_KT denotes headwind and negative WIND_KT
%   denotes tailwind. SURFACE is 'paved' or 'dry grass'. FLAPS is 'full'
%   or 'up'. The POH flaps-up 35-percent distance and +9-KIAS corrections
%   are applied when requested.

    if nargin < 3 || isempty(windComponent_kt)
        windComponent_kt = 0;
    end
    if nargin < 4 || isempty(runwaySurface)
        runwaySurface = 'paved';
    end
    if nargin < 5 || isempty(flapConfiguration)
        flapConfiguration = 'full';
    end

    data = pohLandingData();
    validateattributes(pressureAltitude_ft, {'numeric'}, ...
        {'real', 'finite', 'scalar', '>=', min(data.altitudeGrid_ft), ...
         '<=', max(data.altitudeGrid_ft)}, ...
        mfilename, 'pressureAltitude_ft', 1);
    validateattributes(oat_C, {'numeric'}, ...
        {'real', 'finite', 'scalar', '>=', min(data.temperatureGrid_C), ...
         '<=', max(data.temperatureGrid_C)}, mfilename, 'oat_C', 2);
    validateattributes(windComponent_kt, {'numeric'}, ...
        {'real', 'finite', 'scalar'}, mfilename, 'windComponent_kt', 3);
    runwaySurface = validatestring(runwaySurface, ...
        {'paved', 'dry grass'}, mfilename, 'runwaySurface', 4);
    flapConfiguration = validatestring(flapConfiguration, ...
        {'full', 'up'}, mfilename, 'flapConfiguration', 5);

    interpolatedGround_ft = interp2( ...
        data.temperatureGrid_C, data.altitudeGrid_ft, ...
        data.groundRoll_ft, oat_C, pressureAltitude_ft, 'linear');
    interpolatedTotal_ft = interp2( ...
        data.temperatureGrid_C, data.altitudeGrid_ft, ...
        data.totalOver50ft_ft, oat_C, pressureAltitude_ft, 'linear');

    altitudeIndex = find( ...
        data.altitudeGrid_ft >= pressureAltitude_ft, 1, 'first');
    temperatureIndex = find( ...
        data.temperatureGrid_C >= oat_C, 1, 'first');
    conservativeGround_ft = data.groundRoll_ft( ...
        altitudeIndex, temperatureIndex);
    conservativeTotal_ft = data.totalOver50ft_ft( ...
        altitudeIndex, temperatureIndex);

    if strcmp(runwaySurface, 'dry grass')
        grassFraction = data.grassAdditionFractionOfGroundRoll;
    else
        grassFraction = 0;
    end
    if strcmp(flapConfiguration, 'up')
        configurationMultiplier = data.flapsUpDistanceMultiplier;
        speedAt50ft_KIAS = data.speedAt50ft_KIAS + ...
            data.flapsUpSpeedIncrement_KIAS;
        configuration = 'Flaps UP, power idle, maximum braking';
    else
        configurationMultiplier = 1;
        speedAt50ft_KIAS = data.speedAt50ft_KIAS;
        configuration = data.configuration;
    end

    interpolated = applyPohFieldCorrections( ...
        interpolatedGround_ft, interpolatedTotal_ft, ...
        windComponent_kt, grassFraction, configurationMultiplier, ...
        data.maximumPublishedTailwind_kt);
    interpolated.speedAt50ft_KIAS = speedAt50ft_KIAS;
    conservative = applyPohFieldCorrections( ...
        conservativeGround_ft, conservativeTotal_ft, ...
        windComponent_kt, grassFraction, configurationMultiplier, ...
        data.maximumPublishedTailwind_kt);
    conservative.speedAt50ft_KIAS = speedAt50ft_KIAS;

    landing = struct();
    landing.referenceWeight_lb = data.referenceWeight_lb;
    landing.pressureAltitude_ft = pressureAltitude_ft;
    landing.oat_C = oat_C;
    landing.windComponent_kt = windComponent_kt;
    landing.runwaySurface = runwaySurface;
    landing.flapConfiguration = flapConfiguration;
    landing.configuration = configuration;
    landing.interpolated = interpolated;
    landing.conservative = conservative;
    landing.conservativeGrid = struct( ...
        'pressureAltitude_ft', data.altitudeGrid_ft(altitudeIndex), ...
        'oat_C', data.temperatureGrid_C(temperatureIndex));
    landing.interpolationMethod = ...
        'linear in OAT and pressure altitude; no extrapolation';
    landing.conservativeMethod = ...
        'next-higher published altitude and temperature';
    landing.windCorrectionRule = ...
        'headwind -10% per 9 kt; tailwind +10% per 2 kt (maximum 10 kt)';
    landing.surfaceCorrectionRule = ...
        'dry grass: add 45% of tabulated ground roll to both distances';
    landing.flapsUpCorrectionRule = ...
        'flaps up: add 9 KIAS and allow 35% longer distances';
    landing.source = data.source;
end
