function limits = pohManeuverLimits(weight_lb)
%POHMANEUVERLIMITS Return published C172S normal-category maneuver limits.
%
%   LIMITS = POHMANEUVERLIMITS(WEIGHT_LB) returns the POH maneuvering-speed
%   table and normal-category operating/load limits. VA is linearly
%   interpolated only between the published 1900, 2200, and 2550 lb rows.
%   Extrapolation is deliberately rejected.

    validateattributes(weight_lb, {'numeric'}, ...
        {'real', 'finite', 'scalar'}, mfilename, 'weight_lb', 1);

    tableWeight_lb = [1900, 2200, 2550];
    tableVa_KCAS = [88, 95, 102];
    tableVa_KIAS = [90, 98, 105];

    if weight_lb < tableWeight_lb(1) || weight_lb > tableWeight_lb(end)
        error('pohManeuverLimits:WeightOutsideTable', ...
            ['Weight must be within the published normal-category VA ' ...
             'table range of %.0f to %.0f lb; extrapolation is not used.'], ...
            tableWeight_lb(1), tableWeight_lb(end));
    end

    maneuveringSpeed_KCAS = interp1( ...
        tableWeight_lb, tableVa_KCAS, weight_lb, 'linear');
    maneuveringSpeed_KIAS = interp1( ...
        tableWeight_lb, tableVa_KIAS, weight_lb, 'linear');

    if any(weight_lb == tableWeight_lb)
        interpolationStatus = 'PUBLISHED POH TABLE VALUE';
        classification = 'POH DATA/TABLE VALUE';
    else
        interpolationStatus = ...
            'LINEAR INTERPOLATION BETWEEN PUBLISHED POH TABLE VALUES';
        classification = 'POH DATA/LINEAR INTERPOLATION';
    end

    limits = struct( ...
        'category', 'NORMAL', ...
        'weight_lb', weight_lb, ...
        'tableWeight_lb', tableWeight_lb, ...
        'tableManeuveringSpeed_KCAS', tableVa_KCAS, ...
        'tableManeuveringSpeed_KIAS', tableVa_KIAS, ...
        'maneuveringSpeed_KCAS', maneuveringSpeed_KCAS, ...
        'maneuveringSpeed_KIAS', maneuveringSpeed_KIAS, ...
        'maximumStructuralCruisingSpeed_KCAS', 126, ...
        'maximumStructuralCruisingSpeed_KIAS', 129, ...
        'neverExceedSpeed_KCAS', 160, ...
        'neverExceedSpeed_KIAS', 163, ...
        'positiveLoadFactorLimit_g', 3.8, ...
        'negativeLoadFactorLimit_g', -1.52, ...
        'flapsDownPositiveLoadFactorLimit_g', 3.0, ...
        'maximumNormalCategoryBankAngle_deg', 60, ...
        'recommendedSteepTurnEntrySpeed_KIAS', 95, ...
        'interpolationStatus', interpolationStatus, ...
        'classification', classification, ...
        'source', ['Cessna 172S POH/AFM 172SPHBUS-02, Revision 4, ' ...
            'Section 2, Figure 2-1 and pages 2-8 and 2-10'], ...
        'scopeNote', ['Normal category only. The POH states that normal-' ...
            'category turns must not exceed 60 degrees of bank.']);
end
