function glide = pohMaximumGlide(heightAboveTerrain_ft)
%POHMAXIMUMGLIDE Interpolate the C172S POH maximum-glide chart.
%
%   GLIDE = POHMAXIMUMGLIDE(HEIGHTABOVETERRAIN_FT) returns the zero-wind
%   ground distance from Cessna 172S POH Figure 3-1. The published chart is
%   for 68 KIAS, a windmilling propeller, and flaps up. No wind or weight
%   correction is introduced because Figure 3-1 does not publish one.

    validateattributes(heightAboveTerrain_ft, {'numeric'}, ...
        {'real', 'finite', 'nonnegative'}, mfilename, ...
        'heightAboveTerrain_ft', 1);
    if any(heightAboveTerrain_ft(:) > 12000)
        error('pohMaximumGlide:OutsideChart', ...
            ['Height above terrain must be within the Figure 3-1 chart ' ...
             'range of 0 to 12000 ft.']);
    end

    NM_TO_FT = 6076.1154855643;
    chartHeight_ft = (0:2000:12000).';
    chartDistance_nm = (0:3:18).';

    groundDistance_nm = interp1(chartHeight_ft, chartDistance_nm, ...
        heightAboveTerrain_ft, 'linear');
    chartGlideRatio = chartDistance_nm(end) * NM_TO_FT / ...
        chartHeight_ft(end);

    glide = struct( ...
        'heightAboveTerrain_ft', heightAboveTerrain_ft, ...
        'groundDistance_nm', groundDistance_nm, ...
        'rangePer1000ft_nm', 1.5, ...
        'glideRatio_horizontalPerVertical', chartGlideRatio, ...
        'glideAngle_deg', atand(1 / chartGlideRatio), ...
        'bestGlideSpeed_KIAS', 68, ...
        'configuration', ...
            'propeller windmilling, flaps up, zero wind', ...
        'weightBasis', ...
            'not stated on Figure 3-1; no weight correction applied', ...
        'interpolationMethod', ...
            'linear interpolation of Figure 3-1 chart coordinates', ...
        'classification', 'POH DATA/FIGURE INTERPOLATION', ...
        'source', ['Cessna 172S POH/AFM 172SPHBUS-02, Revision 4, ' ...
            'Figure 3-1 Maximum Glide'], ...
        'chartHeight_ft', chartHeight_ft, ...
        'chartDistance_nm', chartDistance_nm);
end
