function plan = pohMissionFuelPlanning( ...
        departurePressureAltitude_ft, cruisePressureAltitude_ft, ...
        deltaISA_C, rpm, routeDistance_nm, headwindComponent_kt, ...
        usableFuelOnBoard_USgal, reserveTime_min, ...
        contingencyPercent, speedFairingsInstalled)
%POHMISSIONFUELPLANNING Build a phase-aware C172S POH fuel plan.
%
%   PLAN = POHMISSIONFUELPLANNING(DEPARTUREALTITUDE_FT,
%   CRUISEALTITUDE_FT, DELTAISA_C, RPM, ROUTEDISTANCE_NM,
%   HEADWINDCOMPONENT_KT, USABLEFUELONBOARD_USGAL, RESERVETIME_MIN,
%   CONTINGENCYPERCENT, SPEEDFAIRINGSINSTALLED) combines:
%       - Figure 5-7 climb time/fuel/distance;
%       - Figure 5-8 cruise KTAS and fuel flow;
%       - the published 1.4-gallon start/taxi/takeoff allowance;
%       - reserve fuel at the selected cruise fuel flow; and
%       - a user-selected contingency percentage.
%
%   Positive wind is a headwind and reduces cruise groundspeed. The climb
%   distance remains the Figure 5-7 zero-wind value, matching the POH sample
%   calculation. All results use the 2550-lb POH reference configuration.
%   The non-climb enroute distance is charged at cruise fuel flow; descent is
%   not modeled as a separate lower-fuel-flow phase.

    if nargin < 10 || isempty(speedFairingsInstalled)
        speedFairingsInstalled = true;
    end

    validateattributes(routeDistance_nm, {'numeric'}, ...
        {'real', 'finite', 'scalar', 'nonnegative'}, ...
        mfilename, 'routeDistance_nm', 5);
    validateattributes(headwindComponent_kt, {'numeric'}, ...
        {'real', 'finite', 'scalar'}, ...
        mfilename, 'headwindComponent_kt', 6);
    validateattributes(usableFuelOnBoard_USgal, {'numeric'}, ...
        {'real', 'finite', 'scalar', 'nonnegative'}, ...
        mfilename, 'usableFuelOnBoard_USgal', 7);
    validateattributes(reserveTime_min, {'numeric'}, ...
        {'real', 'finite', 'scalar', 'nonnegative'}, ...
        mfilename, 'reserveTime_min', 8);
    validateattributes(contingencyPercent, {'numeric'}, ...
        {'real', 'finite', 'scalar', 'nonnegative'}, ...
        mfilename, 'contingencyPercent', 9);
    validateattributes(speedFairingsInstalled, {'logical', 'numeric'}, ...
        {'scalar'}, mfilename, 'speedFairingsInstalled', 10);
    if isnumeric(speedFairingsInstalled) && ...
            ~ismember(speedFairingsInstalled, [0, 1])
        error('pohMissionFuelPlanning:InvalidFairingFlag', ...
            'speedFairingsInstalled must be true/false or 1/0.');
    end
    speedFairingsInstalled = logical(speedFairingsInstalled);

    aircraft = cessna172();
    if usableFuelOnBoard_USgal > aircraft.fuelUsable_USgal
        error('pohMissionFuelPlanning:FuelAboveUsableCapacity', ...
            ['Usable fuel on board cannot exceed the published %.1f-US-gal ' ...
             'usable capacity.'], aircraft.fuelUsable_USgal);
    end

    climb = pohClimbFuelPerformance( ...
        departurePressureAltitude_ft, cruisePressureAltitude_ft, ...
        deltaISA_C);
    cruise = pohCruisePerformance( ...
        cruisePressureAltitude_ft, rpm, deltaISA_C, ...
        aircraft.maxGrossWeight_lb, speedFairingsInstalled);
    cruiseKTAS = cruise.selectedConfigurationKTAS;
    cruiseGroundSpeed_kt = cruiseKTAS - headwindComponent_kt;
    if cruiseGroundSpeed_kt <= 0
        error('pohMissionFuelPlanning:NonpositiveGroundSpeed', ...
            ['Headwind component must be lower than the selected %.1f-KTAS ' ...
             'cruise speed.'], cruiseKTAS);
    end
    if routeDistance_nm + 1e-12 < climb.correctedDistance_nm
        error('pohMissionFuelPlanning:RouteShorterThanClimbDistance', ...
            ['Route distance %.1f NM is shorter than the corrected POH ' ...
             'zero-wind climb distance %.1f NM. Select a lower cruise ' ...
             'altitude or a longer route.'], ...
            routeDistance_nm, climb.correctedDistance_nm);
    end

    cruiseDistance_nm = routeDistance_nm - climb.correctedDistance_nm;
    cruiseTime_h = cruiseDistance_nm / cruiseGroundSpeed_kt;
    cruiseFuel_USgal = cruiseTime_h * cruise.fuelFlow_GPH;

    startTaxiTakeoffFuel_USgal = ...
        climb.startTaxiTakeoffAllowance_USgal;
    nominalTripFuel_USgal = startTaxiTakeoffFuel_USgal + ...
        climb.correctedFuel_USgal + cruiseFuel_USgal;
    contingencyFuel_USgal = ...
        nominalTripFuel_USgal * contingencyPercent / 100;
    reserveFuel_USgal = cruise.fuelFlow_GPH * reserveTime_min / 60;
    requiredFuel_USgal = nominalTripFuel_USgal + ...
        contingencyFuel_USgal + reserveFuel_USgal;

    planningStartFuel_USgal = roundUpToTenth(startTaxiTakeoffFuel_USgal);
    planningClimbFuel_USgal = roundUpToTenth(climb.correctedFuel_USgal);
    planningCruiseFuel_USgal = roundUpToTenth(cruiseFuel_USgal);
    planningContingencyFuel_USgal = roundUpToTenth(contingencyFuel_USgal);
    planningReserveFuel_USgal = roundUpToTenth(reserveFuel_USgal);
    planningRequiredFuel_USgal = planningStartFuel_USgal + ...
        planningClimbFuel_USgal + planningCruiseFuel_USgal + ...
        planningContingencyFuel_USgal + planningReserveFuel_USgal;

    nominalLandingFuel_USgal = ...
        usableFuelOnBoard_USgal - nominalTripFuel_USgal;
    protectedLandingFuel_USgal = nominalLandingFuel_USgal - ...
        contingencyFuel_USgal;
    planningFuelMargin_USgal = ...
        usableFuelOnBoard_USgal - planningRequiredFuel_USgal;
    missionFeasible = planningFuelMargin_USgal >= -1e-12;

    contingencyFraction = contingencyPercent / 100;
    tripFuelAvailableBeforeContingency_USgal = max(0, ...
        (usableFuelOnBoard_USgal - reserveFuel_USgal) / ...
        (1 + contingencyFraction));
    cruiseFuelAvailable_USgal = tripFuelAvailableBeforeContingency_USgal - ...
        startTaxiTakeoffFuel_USgal - climb.correctedFuel_USgal;
    if cruiseFuelAvailable_USgal > 0
        maximumCruiseTime_h = cruiseFuelAvailable_USgal / ...
            cruise.fuelFlow_GPH;
        maximumRouteDistance_nm = climb.correctedDistance_nm + ...
            maximumCruiseTime_h * cruiseGroundSpeed_kt;
        maximumEnrouteTime_h = ...
            climb.correctedTime_min / 60 + maximumCruiseTime_h;
    else
        maximumCruiseTime_h = 0;
        maximumRouteDistance_nm = 0;
        maximumEnrouteTime_h = 0;
    end

    plan = struct( ...
        'referenceWeight_lb', aircraft.maxGrossWeight_lb, ...
        'speedFairingsInstalled', speedFairingsInstalled, ...
        'departurePressureAltitude_ft', departurePressureAltitude_ft, ...
        'cruisePressureAltitude_ft', cruisePressureAltitude_ft, ...
        'deltaISA_C', deltaISA_C, ...
        'rpm', rpm, ...
        'routeDistance_nm', routeDistance_nm, ...
        'headwindComponent_kt', headwindComponent_kt, ...
        'usableFuelCapacity_USgal', aircraft.fuelUsable_USgal, ...
        'usableFuelOnBoard_USgal', usableFuelOnBoard_USgal, ...
        'reserveTime_min', reserveTime_min, ...
        'contingencyPercent', contingencyPercent, ...
        'climb', climb, ...
        'cruise', cruise, ...
        'cruiseTrueAirspeed_KTAS', cruiseKTAS, ...
        'cruiseGroundSpeed_kt', cruiseGroundSpeed_kt, ...
        'cruiseDistance_nm', cruiseDistance_nm, ...
        'cruiseTime_h', cruiseTime_h, ...
        'startTaxiTakeoffFuel_USgal', startTaxiTakeoffFuel_USgal, ...
        'climbFuel_USgal', climb.correctedFuel_USgal, ...
        'cruiseFuel_USgal', cruiseFuel_USgal, ...
        'nominalTripFuel_USgal', nominalTripFuel_USgal, ...
        'contingencyFuel_USgal', contingencyFuel_USgal, ...
        'reserveFuel_USgal', reserveFuel_USgal, ...
        'requiredFuel_USgal', requiredFuel_USgal, ...
        'planningStartFuel_USgal', planningStartFuel_USgal, ...
        'planningClimbFuel_USgal', planningClimbFuel_USgal, ...
        'planningCruiseFuel_USgal', planningCruiseFuel_USgal, ...
        'planningContingencyFuel_USgal', planningContingencyFuel_USgal, ...
        'planningReserveFuel_USgal', planningReserveFuel_USgal, ...
        'planningRequiredFuel_USgal', planningRequiredFuel_USgal, ...
        'nominalLandingFuel_USgal', nominalLandingFuel_USgal, ...
        'protectedLandingFuel_USgal', protectedLandingFuel_USgal, ...
        'planningFuelMargin_USgal', planningFuelMargin_USgal, ...
        'missionFeasible', missionFeasible, ...
        'maximumCruiseTime_h', maximumCruiseTime_h, ...
        'maximumEnrouteTime_h', maximumEnrouteTime_h, ...
        'maximumRouteDistance_nm', maximumRouteDistance_nm, ...
        'roundingPolicy', ...
            'individual planning fuel components rounded upward to 0.1 US gal', ...
        'windMethod', ...
            ['cruise GS = POH KTAS - headwind; Figure 5-7 climb distance ' ...
             'retained at published zero-wind value'], ...
        'descentMethod', ...
            ['non-climb enroute distance charged at cruise fuel flow; ' ...
             'no separate descent credit'], ...
        'classification', ...
            ['POH-BASED PHASE FUEL PLAN with user reserve/contingency; ' ...
             'not dispatch authorization'], ...
        'source', ...
            ['C172S POH/AFM 172SPHBUS-02 Figures 5-7 and 5-8, ' ...
             'Section 1 fuel capacity, and Section 5 sample method']);
end

function roundedValue = roundUpToTenth(value)
%ROUNDUPTOTENTH Round a nonnegative planning value upward to 0.1.

    roundedValue = ceil((value - 1e-12) * 10) / 10;
end
