function profile = pohRangeEnduranceProfile( ...
    cruisePressureAltitude_ft, targetPercentMCP)
%POHRANGEENDURANCEPROFILE Reconstruct the POH range/endurance profile.
%
%   PROFILE = POHRANGEENDURANCEPROFILE(ALTITUDE_FT, TARGETPERCENTMCP)
%   combines the published Figure 5-7 normal-climb data with a Figure 5-8
%   cruise operating point to reconstruct the conditions of Figures 5-9
%   and 5-10:
%       - 2550 lb reference weight;
%       - standard temperature;
%       - zero wind;
%       - 53 US gal usable fuel;
%       - recommended lean mixture;
%       - 45-minute reserve at the selected cruise fuel flow; and
%       - speed fairings installed for the range calculation.
%
%   The result includes start/taxi/takeoff fuel, climb fuel/distance/time,
%   cruise fuel, reserve fuel, total range, and total endurance. It is a
%   POH cross-chart reconstruction, not an independent flight-test model.

validateattributes(cruisePressureAltitude_ft, {'numeric'}, ...
    {'real', 'finite', 'scalar'}, mfilename, ...
    'cruisePressureAltitude_ft', 1);
validateattributes(targetPercentMCP, {'numeric'}, ...
    {'real', 'finite', 'scalar', 'positive'}, mfilename, ...
    'targetPercentMCP', 2);

aircraft = cessna172();
departurePressureAltitude_ft = 0;
deltaISA_C = 0;
reserveTime_min = 45;
headwindComponent_kt = 0;

climb = pohClimbFuelPerformance( ...
    departurePressureAltitude_ft, cruisePressureAltitude_ft, ...
    deltaISA_C);
cruise = pohCruiseAtPower( ...
    cruisePressureAltitude_ft, targetPercentMCP, deltaISA_C);

startTaxiTakeoffFuel_USgal = ...
    climb.startTaxiTakeoffAllowance_USgal;
reserveFuel_USgal = cruise.fuelFlow_GPH * reserveTime_min / 60;
cruiseFuelAvailable_USgal = aircraft.fuelUsable_USgal - ...
    startTaxiTakeoffFuel_USgal - climb.correctedFuel_USgal - ...
    reserveFuel_USgal;
if cruiseFuelAvailable_USgal <= 0
    error('pohRangeEnduranceProfile:NoCruiseFuelAvailable', ...
        ['The published usable fuel is insufficient after the ground, ' ...
        'climb, and reserve allowances at this condition.']);
end

cruiseTime_h = cruiseFuelAvailable_USgal / cruise.fuelFlow_GPH;
range_nm = climb.correctedDistance_nm + ...
    cruiseTime_h * cruise.trueAirspeed_KTAS;
endurance_h = climb.correctedTime_min / 60 + cruiseTime_h;

profile = struct( ...
    'referenceWeight_lb', aircraft.maxGrossWeight_lb, ...
    'usableFuel_USgal', aircraft.fuelUsable_USgal, ...
    'speedFairingsInstalled', true, ...
    'departurePressureAltitude_ft', ...
    departurePressureAltitude_ft, ...
    'cruisePressureAltitude_ft', cruisePressureAltitude_ft, ...
    'deltaISA_C', deltaISA_C, ...
    'headwindComponent_kt', headwindComponent_kt, ...
    'reserveTime_min', reserveTime_min, ...
    'targetPercentMCP', targetPercentMCP, ...
    'solvedRPM', cruise.solvedRPM, ...
    'trueAirspeed_KTAS', cruise.trueAirspeed_KTAS, ...
    'fuelFlow_GPH', cruise.fuelFlow_GPH, ...
    'startTaxiTakeoffFuel_USgal', ...
    startTaxiTakeoffFuel_USgal, ...
    'climbFuel_USgal', climb.correctedFuel_USgal, ...
    'climbDistance_nm', climb.correctedDistance_nm, ...
    'climbTime_min', climb.correctedTime_min, ...
    'reserveFuel_USgal', reserveFuel_USgal, ...
    'cruiseFuelAvailable_USgal', cruiseFuelAvailable_USgal, ...
    'cruiseTime_h', cruiseTime_h, ...
    'range_nm', range_nm, ...
    'endurance_h', endurance_h, ...
    'climb', climb, ...
    'cruise', cruise, ...
    'classification', ...
    ['POH CROSS-CHART RECONSTRUCTION; Figures 5-7 and 5-8 ' ...
    'compared with Figures 5-9 and 5-10; not independent ' ...
    'flight-test validation'], ...
    'source', ...
    ['C172S POH Figures 5-7 through 5-10; 2550 lb, ISA, ' ...
    'zero wind, 53 US gal usable, 45-minute reserve']);
end