function takeoff = pohTakeoffPerformance( ...
        weight_lb, pressureAltitude_ft, oat_C, ...
        windComponent_kt, runwaySurface)
%POHTAKEOFFPERFORMANCE POH-backed C172S short-field takeoff reference.
%
%   TAKEOFF = POHTAKEOFFPERFORMANCE(WEIGHT_LB, ALTITUDE_FT, OAT_C,
%   WIND_KT, SURFACE) interpolates C172S POH Figure 5-5 without
%   extrapolation. Positive WIND_KT denotes headwind and negative WIND_KT
%   denotes tailwind. SURFACE is 'paved' or 'dry grass'.
%
%   The output includes both a linearly interpolated result and the POH
%   manual's conservative next-higher weight/altitude/temperature grid
%   result. Published wind and dry-grass corrections are applied to both.

    if nargin < 4 || isempty(windComponent_kt)
        windComponent_kt = 0;
    end
    if nargin < 5 || isempty(runwaySurface)
        runwaySurface = 'paved';
    end

    data = pohTakeoffData();
    validateattributes(weight_lb, {'numeric'}, ...
        {'real', 'finite', 'scalar', '>=', min(data.weightGrid_lb), ...
         '<=', max(data.weightGrid_lb)}, mfilename, 'weight_lb', 1);
    validateattributes(pressureAltitude_ft, {'numeric'}, ...
        {'real', 'finite', 'scalar', '>=', min(data.altitudeGrid_ft), ...
         '<=', max(data.altitudeGrid_ft)}, ...
        mfilename, 'pressureAltitude_ft', 2);
    validateattributes(oat_C, {'numeric'}, ...
        {'real', 'finite', 'scalar', '>=', min(data.temperatureGrid_C), ...
         '<=', max(data.temperatureGrid_C)}, mfilename, 'oat_C', 3);
    validateattributes(windComponent_kt, {'numeric'}, ...
        {'real', 'finite', 'scalar'}, mfilename, 'windComponent_kt', 4);
    runwaySurface = validatestring(runwaySurface, ...
        {'paved', 'dry grass'}, mfilename, 'runwaySurface', 5);

    numberWeights = numel(data.weightGrid_lb);
    groundByWeight_ft = zeros(1, numberWeights);
    totalByWeight_ft = zeros(1, numberWeights);
    for weightIndex = 1:numberWeights
        groundByWeight_ft(weightIndex) = interp2( ...
            data.temperatureGrid_C, data.altitudeGrid_ft, ...
            data.groundRoll_ft{weightIndex}, oat_C, ...
            pressureAltitude_ft, 'linear');
        totalByWeight_ft(weightIndex) = interp2( ...
            data.temperatureGrid_C, data.altitudeGrid_ft, ...
            data.totalOver50ft_ft{weightIndex}, oat_C, ...
            pressureAltitude_ft, 'linear');
    end

    interpolatedGround_ft = interp1(data.weightGrid_lb, ...
        groundByWeight_ft, weight_lb, 'linear');
    interpolatedTotal_ft = interp1(data.weightGrid_lb, ...
        totalByWeight_ft, weight_lb, 'linear');
    interpolatedLiftOff_KIAS = interp1(data.weightGrid_lb, ...
        data.liftOffSpeed_KIAS, weight_lb, 'linear');
    interpolatedAt50ft_KIAS = interp1(data.weightGrid_lb, ...
        data.speedAt50ft_KIAS, weight_lb, 'linear');

    weightIndex = find(data.weightGrid_lb >= weight_lb, 1, 'first');
    altitudeIndex = find( ...
        data.altitudeGrid_ft >= pressureAltitude_ft, 1, 'first');
    temperatureIndex = find( ...
        data.temperatureGrid_C >= oat_C, 1, 'first');
    conservativeGround_ft = data.groundRoll_ft{weightIndex}( ...
        altitudeIndex, temperatureIndex);
    conservativeTotal_ft = data.totalOver50ft_ft{weightIndex}( ...
        altitudeIndex, temperatureIndex);

    if strcmp(runwaySurface, 'dry grass')
        grassFraction = data.grassAdditionFractionOfGroundRoll;
    else
        grassFraction = 0;
    end

    interpolated = applyPohFieldCorrections( ...
        interpolatedGround_ft, interpolatedTotal_ft, ...
        windComponent_kt, grassFraction, 1, ...
        data.maximumPublishedTailwind_kt);
    interpolated.liftOffSpeed_KIAS = interpolatedLiftOff_KIAS;
    interpolated.speedAt50ft_KIAS = interpolatedAt50ft_KIAS;

    conservative = applyPohFieldCorrections( ...
        conservativeGround_ft, conservativeTotal_ft, ...
        windComponent_kt, grassFraction, 1, ...
        data.maximumPublishedTailwind_kt);
    conservative.liftOffSpeed_KIAS = ...
        data.liftOffSpeed_KIAS(weightIndex);
    conservative.speedAt50ft_KIAS = ...
        data.speedAt50ft_KIAS(weightIndex);

    if pressureAltitude_ft > 3000
        mixtureCondition = 'lean for maximum RPM before takeoff';
    else
        mixtureCondition = 'full rich (unless required for smooth operation)';
    end

    takeoff = struct();
    takeoff.weight_lb = weight_lb;
    takeoff.pressureAltitude_ft = pressureAltitude_ft;
    takeoff.oat_C = oat_C;
    takeoff.windComponent_kt = windComponent_kt;
    takeoff.runwaySurface = runwaySurface;
    takeoff.interpolated = interpolated;
    takeoff.conservative = conservative;
    takeoff.conservativeGrid = struct( ...
        'weight_lb', data.weightGrid_lb(weightIndex), ...
        'pressureAltitude_ft', data.altitudeGrid_ft(altitudeIndex), ...
        'oat_C', data.temperatureGrid_C(temperatureIndex));
    takeoff.configuration = data.configuration;
    takeoff.mixtureCondition = mixtureCondition;
    takeoff.interpolationMethod = ...
        'linear in OAT, pressure altitude, and weight; no extrapolation';
    takeoff.conservativeMethod = ...
        'next-higher published weight, altitude, and temperature';
    takeoff.windCorrectionRule = ...
        'headwind -10% per 9 kt; tailwind +10% per 2 kt (maximum 10 kt)';
    takeoff.surfaceCorrectionRule = ...
        'dry grass: add 15% of tabulated ground roll to both distances';
    takeoff.source = data.source;
end
