function [speed_KTAS, info] = predictEffectiveCruiseSpeed( ...
        pressureAltitude_ft, rpm, deltaISA_C, model)
%PREDICTEFFECTIVECRUISESPEED Solve calibrated cruise power balance.
%
%   SPEED_KTAS = PREDICTEFFECTIVECRUISESPEED(ALTITUDE_FT, RPM,
%   DELTAISA_C, MODEL) predicts C172S cruise true airspeed by solving
%
%       eta_effective(V, RPM, rho) P_engine = P_required(V, rho).
%
%   MODEL must be returned by FITEFFECTIVECRUISESPEEDMODEL. The function
%   uses the POH percent-MCP mapping for engine brake power, but it does not
%   use the POH KTAS value while solving for speed.
%
%   Applicability is limited to the Figure 5-8 reference configuration:
%   2550 lb, speed fairings installed, and the published altitude,
%   temperature, and RPM envelope. This is a semi-empirical POH-calibrated
%   prediction, not an independently identified aircraft/propeller model.

    if nargin < 4 || isempty(model)
        model = fitEffectiveCruiseSpeedModel();
    end
    validateSpeedModel(model);
    validateattributes(pressureAltitude_ft, {'numeric'}, ...
        {'real', 'finite', 'scalar'}, mfilename, ...
        'pressureAltitude_ft', 1);
    validateattributes(rpm, {'numeric'}, ...
        {'real', 'finite', 'scalar'}, mfilename, 'rpm', 2);
    validateattributes(deltaISA_C, {'numeric'}, ...
        {'real', 'finite', 'scalar'}, mfilename, 'deltaISA_C', 3);

    aircraft = cessna172();
    atmosphere = atmosphereAtPressureAltitude( ...
        pressureAltitude_ft, deltaISA_C);
    try
        [enginePower_W, engineInfo] = enginePowerAvailable( ...
            pressureAltitude_ft, rpm, deltaISA_C, aircraft.engine);
    catch ME
        if startsWith(ME.identifier, 'enginePowerAvailable:')
            error('predictEffectiveCruiseSpeed:OutsidePOHEnvelope', ...
                '%s', ME.message);
        end
        rethrow(ME)
    end

    rotationRate_rps = rpm / 60;
    observedJ = model.observedAdvanceRatioRange;
    guardBand = model.advanceRatioGuardBand;
    searchJ = [observedJ(1) - guardBand, observedJ(2) + guardBand];
    searchSpeed_mps = searchJ .* rotationRate_rps .* ...
        model.propellerDiameter_m;
    speedGrid_mps = linspace(searchSpeed_mps(1), ...
        searchSpeed_mps(2), model.rootSearchGridPoints);
    residualGrid_W = arrayfun(@(speed) powerBalanceResidual( ...
        speed, rpm, atmosphere, enginePower_W, aircraft, model), ...
        speedGrid_mps);

    exactTolerance_W = 1e-7;
    exactIndex = find(abs(residualGrid_W) <= exactTolerance_W, 1);
    signChangeIndex = find( ...
        residualGrid_W(1:end-1) .* residualGrid_W(2:end) < 0);

    if ~isempty(exactIndex)
        speed_mps = speedGrid_mps(exactIndex);
        numberRoots = 1;
    elseif isempty(signChangeIndex)
        error('predictEffectiveCruiseSpeed:NoPowerBalance', ...
            ['No cruise power-balance root exists inside the calibrated ' ...
             'advance-ratio range plus the documented %.3f guard band.'], ...
            guardBand);
    elseif numel(signChangeIndex) > 1
        error('predictEffectiveCruiseSpeed:AmbiguousPowerBalance', ...
            ['More than one cruise root exists inside the permitted ' ...
             'speed-inversion range. The result is rejected.']);
    else
        bracket = speedGrid_mps(signChangeIndex + [0, 1]);
        speed_mps = fzero(@(speed) powerBalanceResidual( ...
            speed, rpm, atmosphere, enginePower_W, aircraft, model), ...
            bracket);
        numberRoots = 1;
    end

    effectiveEta = evaluateSpeedModelEta( ...
        speed_mps, rpm, atmosphere.rho, model);
    [requiredPower_W, drag_N, CL, CD] = powerRequired( ...
        aircraft, atmosphere, speed_mps);
    availablePower_W = effectiveEta * enginePower_W;
    residual_W = availablePower_W - requiredPower_W;
    advanceRatio = speed_mps / ...
        (rotationRate_rps * model.propellerDiameter_m);
    insideObservedJ = advanceRatio >= observedJ(1) && ...
        advanceRatio <= observedJ(2);

    speed_KTAS = speed_mps / model.knotToMps;
    if nargout > 1
        info = struct( ...
            'speed_mps', speed_mps, ...
            'speed_KTAS', speed_KTAS, ...
            'advanceRatio', advanceRatio, ...
            'effectiveEta', effectiveEta, ...
            'enginePower_W', enginePower_W, ...
            'percentMCP', engineInfo.percentMCP, ...
            'powerAvailable_W', availablePower_W, ...
            'powerRequired_W', requiredPower_W, ...
            'powerBalanceResidual_W', residual_W, ...
            'drag_N', drag_N, ...
            'liftCoefficient', CL, ...
            'dragCoefficient', CD, ...
            'insideObservedAdvanceRatioRange', insideObservedJ, ...
            'usedAdvanceRatioGuardBand', ~insideObservedJ, ...
            'advanceRatioSearchRange', searchJ, ...
            'numberRoots', numberRoots, ...
            'classification', model.classification, ...
            'referenceConfiguration', model.referenceConfiguration);
    end
end

function residual_W = powerBalanceResidual( ...
        speed_mps, rpm, atmosphere, enginePower_W, aircraft, model)

    eta = evaluateSpeedModelEta(speed_mps, rpm, atmosphere.rho, model);
    requiredPower_W = powerRequired(aircraft, atmosphere, speed_mps);
    residual_W = eta * enginePower_W - requiredPower_W;
end

function eta = evaluateSpeedModelEta(speed_mps, rpm, density, model)

    n = model.normalization;
    J = speed_mps / ((rpm / 60) * model.propellerDiameter_m);
    xJ = J - n.advanceRatioCenter;
    xRPM = (rpm - n.rpmCenter) / n.rpmScale;
    xDensity = (density - n.densityCenter_kgpm3) / ...
        n.densityScale_kgpm3;
    terms = [1, xJ, xJ^2, xJ^3, xRPM, xDensity];
    eta = terms * model.coefficients;
    if ~isfinite(eta) || eta <= 0 || eta >= 1
        error('predictEffectiveCruiseSpeed:NonphysicalEfficiency', ...
            ['Speed model returned eta_effective = %.4f. The result is ' ...
             'rejected rather than clipped.'], eta);
    end
end

function validateSpeedModel(model)

    if ~isstruct(model) || ~isscalar(model)
        error('predictEffectiveCruiseSpeed:InvalidModel', ...
            'model must be returned by fitEffectiveCruiseSpeedModel.');
    end
    requiredFields = { ...
        'coefficients', 'normalization', 'propellerDiameter_m', ...
        'observedAdvanceRatioRange', 'advanceRatioGuardBand', ...
        'rootSearchGridPoints', 'knotToMps', 'classification', ...
        'referenceConfiguration'};
    for fieldIndex = 1:numel(requiredFields)
        if ~isfield(model, requiredFields{fieldIndex})
            error('predictEffectiveCruiseSpeed:InvalidModel', ...
                'model is missing required field: %s.', ...
                requiredFields{fieldIndex});
        end
    end
    if numel(model.coefficients) ~= 6
        error('predictEffectiveCruiseSpeed:InvalidModel', ...
            'The speed-inversion model must contain six coefficients.');
    end
end
