function summary = runAllValidations()
%RUNALLVALIDATIONS Run every validated C172S project test suite.
%
%   SUMMARY = RUNALLVALIDATIONS() executes all validated project suites,
%   verifies that MATLAB resolves each validator from this project folder,
%   checks the reported pass counts, and returns a summary structure.
%
%   Expected validated checkpoint:
%       runValidation                       55/55
%       runEffectiveModelValidation         12/12
%       runEffectiveCruiseSpeedValidation   14/14
%       runMissionFuelValidation            26/26
%       runRangeEnduranceProfileValidation  15/15
%       runGlideDescentValidation           22/22
%       runTurnPerformanceValidation        30/30
%       Total                              174/174

    projectFolder = fileparts(mfilename('fullpath'));
    addpath(projectFolder, '-begin');
    rehash;

    suites = struct( ...
        'functionName', { ...
            'runValidation', ...
            'runEffectiveModelValidation', ...
            'runEffectiveCruiseSpeedValidation', ...
            'runMissionFuelValidation', ...
            'runRangeEnduranceProfileValidation', ...
            'runGlideDescentValidation', ...
            'runTurnPerformanceValidation'}, ...
        'description', { ...
            'Core atmosphere, POH, takeoff, landing, and audit checks', ...
            'POH-calibrated effective-power model checks', ...
            'POH-calibrated cruise-speed inversion checks', ...
            'POH climb, range, endurance, and fuel-plan checks', ...
            'POH Figures 5-9/5-10 cross-chart consistency checks', ...
            'POH Figure 3-1 and analytical glide/descent checks', ...
            'POH maneuver limits and analytical level-turn checks'}, ...
        'expectedChecks', {55, 12, 14, 26, 15, 22, 30});

    fprintf('============================================================\n');
    fprintf('C172S COMPLETE PROJECT VALIDATION\n');
    fprintf('============================================================\n');
    fprintf('Project folder: %s\n\n', projectFolder);

    numberSuites = numel(suites);
    suiteNames = cell(numberSuites, 1);
    passedChecks = zeros(numberSuites, 1);
    totalChecks = zeros(numberSuites, 1);
    elapsedSeconds = zeros(numberSuites, 1);

    for suiteIndex = 1:numberSuites
        suite = suites(suiteIndex);
        suiteNames{suiteIndex} = suite.functionName;
        assertResolvedFromProjectFolder( ...
            suite.functionName, projectFolder);

        fprintf('Running %s (%s)...\n\n', ...
            suite.functionName, suite.description);
        timerStart = tic;
        try
            suiteOutput = evalc(sprintf('%s();', suite.functionName));
        catch ME
            fprintf(2, '[FAIL] %s terminated with %s\n', ...
                suite.functionName, ME.identifier);
            fprintf(2, '%s\n', ME.message);
            rethrow(ME);
        end
        elapsedSeconds(suiteIndex) = toc(timerStart);
        fprintf('%s', suiteOutput);

        [passedCount, totalCount] = parseReportedResult( ...
            suiteOutput, suite.functionName);
        passedChecks(suiteIndex) = passedCount;
        totalChecks(suiteIndex) = totalCount;

        if totalCount ~= suite.expectedChecks
            error('runAllValidations:UnexpectedCheckCount', ...
                ['%s reported %d checks, but this checkpoint expects %d. ' ...
                 'Confirm that the current validator file is installed.'], ...
                suite.functionName, totalCount, suite.expectedChecks);
        end
        if passedCount ~= totalCount
            error('runAllValidations:SuiteFailed', ...
                '%s reported %d/%d checks passed.', ...
                suite.functionName, passedCount, totalCount);
        end
        fprintf('[SUITE PASS] %s completed in %.2f s.\n\n', ...
            suite.functionName, elapsedSeconds(suiteIndex));
    end

    totalPassed = sum(passedChecks);
    totalExpected = sum(totalChecks);
    fprintf('============================================================\n');
    fprintf('COMPLETE VALIDATION SUMMARY\n');
    fprintf('============================================================\n');
    for suiteIndex = 1:numberSuites
        fprintf('%-38s %2d/%2d PASS  (%6.2f s)\n', ...
            suiteNames{suiteIndex}, ...
            passedChecks(suiteIndex), totalChecks(suiteIndex), ...
            elapsedSeconds(suiteIndex));
    end
    fprintf('------------------------------------------------------------\n');
    fprintf('%-38s %3d/%3d PASS\n', ...
        'Validated project checkpoint', totalPassed, totalExpected);
    fprintf('============================================================\n');
    fprintf(['Scope note: this result validates documented POH ' ...
        'interpolation and analytical/semi-empirical models within their ' ...
        'stated envelopes. It does not independently identify the aircraft ' ...
        'drag polar, windmilling-propeller drag, McCauley propeller map, ' ...
        'or a gust envelope.\n']);

    summary = struct( ...
        'projectFolder', projectFolder, ...
        'suiteNames', {suiteNames}, ...
        'passedChecks', passedChecks, ...
        'totalChecks', totalChecks, ...
        'elapsedSeconds', elapsedSeconds, ...
        'totalPassed', totalPassed, ...
        'totalChecksExpected', totalExpected, ...
        'status', 'PASS', ...
        'scope', ['Validated within documented POH and calibration ' ...
            'envelopes; analytical graphics and turn results are internal ' ...
            'model-consistency checks, not independent flight-test ' ...
            'validation or drag, propeller, or gust-envelope identification.']);
end

function assertResolvedFromProjectFolder(functionName, projectFolder)
%ASSERTRESOLVEDFROMPROJECTFOLDER Prevent stale MATLAB-path duplicates.

    resolvedFile = which(functionName);
    if isempty(resolvedFile)
        error('runAllValidations:MissingValidator', ...
            '%s.m is not available on the MATLAB path.', functionName);
    end

    expectedFile = fullfile(projectFolder, [functionName '.m']);
    resolvedNormalized = normalizePath(resolvedFile);
    expectedNormalized = normalizePath(expectedFile);
    if ispc
        filesMatch = strcmpi(resolvedNormalized, expectedNormalized);
    else
        filesMatch = strcmp(resolvedNormalized, expectedNormalized);
    end
    if ~filesMatch
        error('runAllValidations:PathConflict', ...
            ['MATLAB resolved %s to:\n  %s\nExpected:\n  %s\n' ...
             'Remove or move the duplicate file, then run rehash.'], ...
            functionName, resolvedFile, expectedFile);
    end
end

function normalized = normalizePath(pathText)
%NORMALIZEPATH Use one separator and remove trailing separators.

    normalized = strrep(char(pathText), '\', '/');
    while numel(normalized) > 1 && normalized(end) == '/'
        normalized(end) = [];
    end
end

function [passedCount, totalCount] = parseReportedResult( ...
        suiteOutput, functionName)
%PARSEREPORTEDRESULT Extract the final "Result: N/N checks passed" line.

    tokens = regexp(suiteOutput, ...
        'Result:\s*(\d+)\s*/\s*(\d+)\s+checks passed\.', ...
        'tokens');
    if isempty(tokens)
        error('runAllValidations:MissingResultLine', ...
            '%s did not report a recognizable validation result.', ...
            functionName);
    end
    finalTokens = tokens{end};
    passedCount = str2double(finalTokens{1});
    totalCount = str2double(finalTokens{2});
end
