function audit = runAccuracyAudit(saveOutputs)
%RUNACCURACYAUDIT Run and report the C172S cruise accuracy gate.
%
%   RUNACCURACYAUDIT() evaluates all 111 published C172S POH Figure 5-8
%   cruise points, prints a candidate-polar comparison, calibrates the
%   combined effective installed model with grouped cross-validation, and
%   saves traceable CSV, MAT, and PNG results.
%
%   AUDIT = RUNACCURACYAUDIT(FALSE) returns the calculations without
%   writing output files or creating a figure.

    if nargin < 1 || isempty(saveOutputs)
        saveOutputs = true;
    end
    validateattributes(saveOutputs, {'logical', 'numeric'}, ...
        {'scalar'}, mfilename, 'saveOutputs', 1);
    saveOutputs = logical(saveOutputs);

    audit = cruiseAccuracyAudit();
    audit.effectiveModel = fitEffectiveCruiseModel(audit.points);

    fprintf('============================================================\n');
    fprintf('C172S CRUISE ACCURACY GATE\n');
    fprintf('============================================================\n');
    fprintf('POH source points evaluated : %d\n', audit.numberPOHPoints);
    fprintf('Source                      : %s\n', audit.pohSource);
    fprintf('Reference configuration     : 2550 lb, speed fairings installed\n');
    fprintf('Identification method       : eta_implied = P_required / P_engine\n\n');

    fprintf('Candidate drag-polar diagnostics:\n');
    fprintf(['%-34s %9s %9s %9s %10s %8s %9s\n'], ...
        'Candidate', 'Mean eta', 'Eta min', 'Eta max', ...
        'Holdout', 'L/Dmax', 'V_BG');
    fprintf('%s\n', repmat('-', 1, 94));
    for k = 1:height(audit.summary)
        fprintf('%-34s %9.3f %9.3f %9.3f %10.4f %8.2f %8.1f\n', ...
            audit.summary.Candidate{k}, ...
            audit.summary.MeanEtaImplied(k), ...
            audit.summary.MinimumEtaImplied(k), ...
            audit.summary.MaximumEtaImplied(k), ...
            audit.summary.CubicHoldoutRMSE(k), ...
            audit.summary.MaximumLiftToDrag(k), ...
            audit.summary.BestGlideEstimate_KIAS(k));
    end

    proxy = audit.currentProxy;
    fprintf('\nCurrent eta(J) proxy closure against POH cruise speeds:\n');
    fprintf('  Mean power margin          : %+8.2f kW\n', ...
        proxy.meanPowerMargin_kW);
    fprintf('  RMS power margin           : %8.2f kW\n', ...
        proxy.rmsPowerMargin_kW);
    fprintf('  Power-margin range         : %+8.2f to %+.2f kW\n', ...
        proxy.minimumPowerMargin_kW, proxy.maximumPowerMargin_kW);
    fprintf('  Provisional RMS tolerance  : %8.2f kW\n', ...
        proxy.closureTolerance_kW);

    if proxy.passesRMSClosure
        fprintf('  Accuracy-gate status       : PASS\n');
    else
        fprintf('  Accuracy-gate status       : FAIL - model requires calibration\n');
    end

    model = audit.effectiveModel;
    fprintf('\nPOH-calibrated combined effective model:\n');
    fprintf('  Classification             : %s\n', ...
        model.classification);
    fprintf('  Selected form              : %s\n', ...
        model.selectionTable.Candidate{model.selectedCandidateIndex});
    fprintf('  Formula                    : %s\n', model.formula);
    for coefficientIndex = 1:numel(model.coefficients)
        fprintf('  %-27s: %+.8f\n', ...
            model.coefficientNames{coefficientIndex}, ...
            model.coefficients(coefficientIndex));
    end
    fprintf('  Calibration RMS / max      : %.3f / %.3f kW\n', ...
        model.calibration.rmsPowerError_kW, ...
        model.calibration.maximumAbsolutePowerError_kW);
    printCrossValidation('Altitude-block', ...
        model.crossValidation.altitude.metrics);
    printCrossValidation('Temperature-block', ...
        model.crossValidation.temperature.metrics);
    printCrossValidation('RPM-block', ...
        model.crossValidation.rpm.metrics);
    fprintf('  Effective-model gate       : %s\n', ...
        model.selectionStatus);

    fprintf('\nEngineering interpretation:\n');
    fprintf(['  The implied efficiency includes errors from both the drag polar\n' ...
        '  and the propeller model. A low holdout error shows consistency,\n' ...
        '  not proof that a candidate is physically correct.\n']);
    fprintf('  %s\n', audit.conclusion);
    fprintf(['  The calibrated term is permitted only as a combined POH closure\n' ...
        '  model. It is not an independently identified propeller map.\n']);

    audit.outputFiles = struct( ...
        'summaryCSV', '', 'pointsCSV', '', 'figurePNG', '', ...
        'effectiveModelSelectionCSV', '', ...
        'effectiveModelCVFoldsCSV', '', 'effectiveModelMAT', '');
    if ~saveOutputs
        return
    end

    projectDirectory = fileparts(mfilename('fullpath'));
    resultsDirectory = fullfile(projectDirectory, 'results');
    if ~exist(resultsDirectory, 'dir')
        mkdir(resultsDirectory);
    end

    audit.outputFiles.summaryCSV = fullfile( ...
        resultsDirectory, 'accuracy_audit_summary.csv');
    audit.outputFiles.pointsCSV = fullfile( ...
        resultsDirectory, 'accuracy_audit_points.csv');
    audit.outputFiles.figurePNG = fullfile( ...
        resultsDirectory, 'accuracy_audit_cruise_closure.png');
    audit.outputFiles.effectiveModelSelectionCSV = fullfile( ...
        resultsDirectory, 'effective_model_selection.csv');
    audit.outputFiles.effectiveModelCVFoldsCSV = fullfile( ...
        resultsDirectory, 'effective_model_grouped_cv_folds.csv');
    audit.outputFiles.effectiveModelMAT = fullfile( ...
        resultsDirectory, 'effective_installed_model.mat');

    writetable(audit.summary, audit.outputFiles.summaryCSV);
    writetable(audit.points, audit.outputFiles.pointsCSV);
    writetable(model.selectionTable, ...
        audit.outputFiles.effectiveModelSelectionCSV);
    groupedFolds = [ ...
        model.crossValidation.altitude.folds; ...
        model.crossValidation.temperature.folds; ...
        model.crossValidation.rpm.folds];
    writetable(groupedFolds, audit.outputFiles.effectiveModelCVFoldsCSV);
    save(audit.outputFiles.effectiveModelMAT, 'model');
    createAuditFigure(audit, audit.outputFiles.figurePNG);

    fprintf('\nSaved accuracy-audit outputs:\n');
    fprintf('  %s\n', audit.outputFiles.summaryCSV);
    fprintf('  %s\n', audit.outputFiles.pointsCSV);
    fprintf('  %s\n', audit.outputFiles.figurePNG);
    fprintf('  %s\n', audit.outputFiles.effectiveModelSelectionCSV);
    fprintf('  %s\n', audit.outputFiles.effectiveModelCVFoldsCSV);
    fprintf('  %s\n', audit.outputFiles.effectiveModelMAT);
end

function printCrossValidation(label, metrics)
%PRINTCROSSVALIDATION Print one grouped validation summary.

    fprintf('  %-27s: RMS %.3f kW; max %.3f kW\n', ...
        [label ' CV'], metrics.rmsPowerError_kW, ...
        metrics.maximumAbsolutePowerError_kW);
end

function createAuditFigure(audit, outputFile)
%CREATEAUDITFIGURE Plot implied efficiency and present-model closure.

    colors = [ ...
        0.0000, 0.4470, 0.7410; ...
        0.8500, 0.3250, 0.0980; ...
        0.4660, 0.6740, 0.1880];

    auditFigure = figure('Color', 'w', ...
        'Name', 'C172S Cruise Accuracy Gate', ...
        'Position', [50, 100, 1700, 650]);
    layout = tiledlayout(auditFigure, 1, 3, ...
        'Padding', 'compact', 'TileSpacing', 'compact');

    etaAxes = nexttile(layout, 1);
    hold(etaAxes, 'on');
    etaFields = { ...
        'CurrentPolarEtaImplied', ...
        'ExternalPolarEtaImplied', ...
        'HaberkornEtaImplied'};
    for k = 1:numel(etaFields)
        scatter(etaAxes, audit.points.AdvanceRatio, ...
            audit.points.(etaFields{k}), 22, colors(k, :), ...
            'filled', 'MarkerFaceAlpha', 0.48, ...
            'DisplayName', audit.summary.Candidate{k});
    end

    [sortedJ, order] = sort(audit.points.AdvanceRatio);
    plot(etaAxes, sortedJ, audit.points.CurrentProxyEta(order), ...
        'k-', 'LineWidth', 2.2, ...
        'DisplayName', 'Current assumed eta(J) proxy');
    styleAxes(etaAxes);
    grid(etaAxes, 'on');
    xlabel(etaAxes, 'Advance Ratio, J', 'Color', 'k');
    ylabel(etaAxes, 'Implied Effective Efficiency', 'Color', 'k');
    title(etaAxes, 'Combined Efficiency Required to Reproduce POH KTAS', ...
        'Color', 'k');
    etaLegend = legend(etaAxes, 'Location', 'best');
    styleLegend(etaLegend);

    marginAxes = nexttile(layout, 2);
    scatter(marginAxes, audit.points.AdvanceRatio, ...
        audit.points.CurrentProxyPowerMargin_kW, 24, ...
        audit.points.Altitude_ft, 'filled');
    hold(marginAxes, 'on');
    yline(marginAxes, 0, '--k', 'Zero closure error', ...
        'LineWidth', 1.6);
    styleAxes(marginAxes);
    grid(marginAxes, 'on');
    xlabel(marginAxes, 'Advance Ratio, J', 'Color', 'k');
    ylabel(marginAxes, 'Current-Model Power Margin (kW)', 'Color', 'k');
    title(marginAxes, 'Current Drag + eta(J) Closure Error', 'Color', 'k');
    marginColorbar = colorbar(marginAxes);
    marginColorbar.Label.String = 'Pressure Altitude (ft)';
    marginColorbar.Color = 'k';

    calibratedAxes = nexttile(layout, 3);
    calibratedError_kW = ...
        audit.effectiveModel.crossValidation.altitude.powerError_kW;
    scatter(calibratedAxes, audit.points.AdvanceRatio, ...
        calibratedError_kW, 24, audit.points.Altitude_ft, 'filled');
    hold(calibratedAxes, 'on');
    yline(calibratedAxes, 0, '--k', 'Zero closure error', ...
        'LineWidth', 1.6);
    yline(calibratedAxes, audit.effectiveModel.gateLimit_kW, ':r', ...
        '+2 kW gate', 'LineWidth', 1.2);
    yline(calibratedAxes, -audit.effectiveModel.gateLimit_kW, ':r', ...
        '-2 kW gate', 'LineWidth', 1.2);
    styleAxes(calibratedAxes);
    grid(calibratedAxes, 'on');
    xlabel(calibratedAxes, 'Advance Ratio, J', 'Color', 'k');
    ylabel(calibratedAxes, 'Held-Out Power Error (kW)', 'Color', 'k');
    title(calibratedAxes, ...
        'Effective Model: Leave-One-Altitude-Out', 'Color', 'k');
    calibratedColorbar = colorbar(calibratedAxes);
    calibratedColorbar.Label.String = 'Held-Out Pressure Altitude (ft)';
    calibratedColorbar.Color = 'k';

    title(layout, ...
        'Cessna 172S Cruise Accuracy Gate - 111 POH Figure 5-8 Points', ...
        'Color', 'k', 'FontWeight', 'bold');

    exportgraphics(auditFigure, outputFile, ...
        'Resolution', 300, 'BackgroundColor', 'white');
end

function styleAxes(ax)
    set(ax, ...
        'Color', 'w', ...
        'XColor', 'k', ...
        'YColor', 'k', ...
        'GridColor', [0.75, 0.75, 0.75], ...
        'GridAlpha', 0.45, ...
        'FontName', 'Arial', ...
        'FontSize', 11, ...
        'LineWidth', 1.0, ...
        'Box', 'on');
end

function styleLegend(legendHandle)
    set(legendHandle, ...
        'Color', 'w', ...
        'TextColor', 'k', ...
        'EdgeColor', [0.35, 0.35, 0.35]);
end
