function runEffectiveModelValidation()
%RUNEFFECTIVEMODELVALIDATION Validate the POH-calibrated cruise model.
%
%   This validator is intentionally separate from runValidation.m so the
%   original 55-check project validation remains unchanged. Together,
%   runValidation (55 checks) and this function (12 checks) provide the
%   complete 67-check validation set.

    KT_TO_MPS = 0.514444;
    testNames = {};
    passed = [];
    details = {};

    audit = cruiseAccuracyAudit();
    model = fitEffectiveCruiseModel(audit.points);
    selectedCandidate = model.selectionTable.Candidate{ ...
        model.selectedCandidateIndex};

    testNames{end + 1} = ...
        'Effective cruise model selects the documented five-term form';
    passed(end + 1) = strcmp(selectedCandidate, ...
        'J quadratic + RPM + density');
    details{end + 1} = sprintf('selected candidate: %s', ...
        selectedCandidate);

    [testNames, passed, details] = addUpperBoundCheck( ...
        testNames, passed, details, ...
        'Calibration RMS power closure', ...
        model.calibration.rmsPowerError_kW, ...
        model.gateLimit_kW, 'kW');
    [testNames, passed, details] = addUpperBoundCheck( ...
        testNames, passed, details, ...
        'Calibration maximum power closure', ...
        model.calibration.maximumAbsolutePowerError_kW, ...
        model.gateLimit_kW, 'kW');

    validationSchemes = { ...
        'altitude-block', model.crossValidation.altitude; ...
        'temperature-block', model.crossValidation.temperature; ...
        'RPM-block', model.crossValidation.rpm};
    for schemeIndex = 1:size(validationSchemes, 1)
        schemeName = validationSchemes{schemeIndex, 1};
        scheme = validationSchemes{schemeIndex, 2};
        [testNames, passed, details] = addUpperBoundCheck( ...
            testNames, passed, details, ...
            sprintf('%s CV RMS power closure', schemeName), ...
            scheme.metrics.rmsPowerError_kW, ...
            model.gateLimit_kW, 'kW');
        [testNames, passed, details] = addUpperBoundCheck( ...
            testNames, passed, details, ...
            sprintf('%s CV maximum power closure', schemeName), ...
            scheme.metrics.maximumAbsolutePowerError_kW, ...
            model.gateLimit_kW, 'kW');
    end

    calibrationSpeed_mps = audit.points.POH_KTAS .* KT_TO_MPS;
    evaluatedEta = effectiveInstalledEfficiency( ...
        calibrationSpeed_mps, audit.points.RPM, ...
        audit.points.Density_kgpm3, model);
    [testNames, passed, details] = addCheck( ...
        testNames, passed, details, ...
        'Evaluator reproduces fitted calibration values', ...
        max(abs(evaluatedEta - model.fittedEta)), 0, 1e-12, '-');

    rejectedExtrapolation = false;
    try
        effectiveInstalledEfficiency(20, 2400, 1.0, model);
    catch ME
        rejectedExtrapolation = strcmp(ME.identifier, ...
            'effectiveInstalledEfficiency:OutsideCalibrationEnvelope');
    end
    testNames{end + 1} = ...
        'Effective model rejects calibration-envelope extrapolation';
    passed(end + 1) = rejectedExtrapolation;
    details{end + 1} = ...
        'Expected rejection outside the calibrated advance-ratio range';

    testNames{end + 1} = ...
        'Effective model is labelled as combined, not propeller efficiency';
    passed(end + 1) = contains(model.classification, ...
        'not isolated propeller efficiency');
    details{end + 1} = model.classification;

    fprintf('==================================================\n');
    fprintf('C172 EFFECTIVE CRUISE MODEL VALIDATION\n');
    fprintf('==================================================\n');
    for testIndex = 1:numel(testNames)
        if passed(testIndex)
            status = 'PASS';
        else
            status = 'FAIL';
        end
        fprintf('[%s] %s - %s\n', ...
            status, testNames{testIndex}, details{testIndex});
    end

    numberPassed = sum(passed);
    fprintf('\nResult: %d/%d checks passed.\n', ...
        numberPassed, numel(passed));
    fprintf(['Combined project validation: runValidation provides 55 ' ...
        'checks; this function provides 12 additional checks.\n']);

    if numberPassed ~= numel(passed)
        error('runEffectiveModelValidation:Failed', ...
            '%d effective-model checks failed.', ...
            numel(passed) - numberPassed);
    end
end

function [names, passed, details] = addCheck( ...
        names, passed, details, name, actual, expected, tolerance, unit)

    names{end + 1} = name;
    passed(end + 1) = isfinite(actual) && ...
        abs(actual - expected) <= tolerance;
    details{end + 1} = sprintf( ...
        'actual %.6g %s, expected %.6g +/- %.3g %s', ...
        actual, unit, expected, tolerance, unit);
end

function [names, passed, details] = addUpperBoundCheck( ...
        names, passed, details, name, actual, upperBound, unit)

    names{end + 1} = name;
    passed(end + 1) = isfinite(actual) && actual <= upperBound;
    details{end + 1} = sprintf( ...
        'actual %.6g %s, required <= %.6g %s', ...
        actual, unit, upperBound, unit);
end
