function runEffectiveCruiseSpeedValidation()
%RUNEFFECTIVECRUISESPEEDVALIDATION Validate predicted cruise KTAS.

    model = fitEffectiveCruiseSpeedModel();
    names = {};
    passed = [];
    details = {};

    validations = { ...
        'calibration', model.speedCalibration; ...
        'altitude-block CV', model.crossValidation.altitude.metrics; ...
        'temperature-block CV', model.crossValidation.temperature.metrics; ...
        'RPM-block CV', model.crossValidation.rpm.metrics};
    for validationIndex = 1:size(validations, 1)
        label = validations{validationIndex, 1};
        metrics = validations{validationIndex, 2};
        [names, passed, details] = addMinimumCheck( ...
            names, passed, details, [label ' solution coverage'], ...
            metrics.coverageFraction, 1.0, '-');
        [names, passed, details] = addMaximumCheck( ...
            names, passed, details, [label ' RMS speed error'], ...
            metrics.rmsError_KTAS, model.rmsSpeedGate_KTAS, 'KTAS');
        [names, passed, details] = addMaximumCheck( ...
            names, passed, details, [label ' maximum speed error'], ...
            metrics.maximumAbsoluteError_KTAS, ...
            model.maximumSpeedGate_KTAS, 'KTAS');
    end

    rejectedOutsideEnvelope = false;
    try
        predictEffectiveCruiseSpeed(1000, 2400, 0, model);
    catch ME
        rejectedOutsideEnvelope = strcmp(ME.identifier, ...
            'predictEffectiveCruiseSpeed:OutsidePOHEnvelope');
    end
    names{end + 1} = 'Speed solver rejects conditions outside POH envelope';
    passed(end + 1) = rejectedOutsideEnvelope;
    details{end + 1} = 'Expected rejection below 2000-ft cruise table';

    names{end + 1} = ...
        'Speed solver is labelled semi-empirical, not independent physics';
    passed(end + 1) = contains(model.classification, ...
        'not an independent physics prediction');
    details{end + 1} = model.classification;

    fprintf('==================================================\n');
    fprintf('C172 EFFECTIVE CRUISE-SPEED VALIDATION\n');
    fprintf('==================================================\n');
    fprintf('Model form: %s\n', model.form);
    fprintf('Observed J range: %.4f to %.4f; guard band: %.3f\n\n', ...
        model.observedAdvanceRatioRange(1), ...
        model.observedAdvanceRatioRange(2), ...
        model.advanceRatioGuardBand);
    for testIndex = 1:numel(names)
        if passed(testIndex)
            status = 'PASS';
        else
            status = 'FAIL';
        end
        fprintf('[%s] %s - %s\n', ...
            status, names{testIndex}, details{testIndex});
    end
    fprintf('\nGuard-band use (calibration/alt/temp/RPM): %d / %d / %d / %d points\n', ...
        model.speedCalibration.numberUsingGuardBand, ...
        model.crossValidation.altitude.metrics.numberUsingGuardBand, ...
        model.crossValidation.temperature.metrics.numberUsingGuardBand, ...
        model.crossValidation.rpm.metrics.numberUsingGuardBand);
    numberPassed = sum(passed);
    fprintf('Result: %d/%d checks passed.\n', ...
        numberPassed, numel(passed));
    fprintf('Status: %s\n', model.validationStatus);

    if numberPassed ~= numel(passed)
        error('runEffectiveCruiseSpeedValidation:Failed', ...
            '%d cruise-speed checks failed.', ...
            numel(passed) - numberPassed);
    end
end

function [names, passed, details] = addMaximumCheck( ...
        names, passed, details, name, actual, limit, unit)

    names{end + 1} = name;
    passed(end + 1) = isfinite(actual) && actual <= limit;
    details{end + 1} = sprintf( ...
        'actual %.6g %s, required <= %.6g %s', ...
        actual, unit, limit, unit);
end

function [names, passed, details] = addMinimumCheck( ...
        names, passed, details, name, actual, limit, unit)

    names{end + 1} = name;
    passed(end + 1) = isfinite(actual) && actual >= limit;
    details{end + 1} = sprintf( ...
        'actual %.6g %s, required >= %.6g %s', ...
        actual, unit, limit, unit);
end
