function summary = runGlideDescentValidation()
%RUNGLIDEDESCENTVALIDATION Validate POH and analytical glide calculations.

    NM_TO_FT = 6076.1154855643;
    FT_TO_M = 0.3048;
    NM_TO_M = 1852;

    aircraft = cessna172();
    poh2000 = pohMaximumGlide(2000);
    poh6000 = pohMaximumGlide(6000);
    poh12000 = pohMaximumGlide(12000);
    nominal = glideDescentPerformance( ...
        aircraft, 6000, 0, 0, 2550);
    lighter = glideDescentPerformance( ...
        aircraft, 6000, 0, 0, 2200);
    elevated = glideDescentPerformance( ...
        aircraft, 10000, 4000, 0, 2550);

    [~, k] = dragPolar(aircraft, 0);
    expectedBestRangeCL = sqrt(aircraft.CD0 / k);
    expectedBestRangeLD = 1 / (2 * sqrt(aircraft.CD0 * k));
    expectedRange_nm = nominal.heightAboveTerrain_ft * FT_TO_M * ...
        expectedBestRangeLD / NM_TO_M;
    expectedWeightSpeedRatio = sqrt(2200 / 2550);

    testNames = { ...
        'POH Figure 3-1: 2000 ft gives 3 NM', ...
        'POH Figure 3-1: 6000 ft gives 9 NM', ...
        'POH Figure 3-1: 12000 ft gives 18 NM', ...
        'POH chart glide ratio matches endpoint geometry', ...
        'POH chart glide angle is consistent with glide ratio', ...
        'POH result is classified as figure interpolation', ...
        'POH rejects height above chart envelope', ...
        'POH rejects negative height', ...
        'Best-range CL equals sqrt(CD0/k)', ...
        'Best-range CD equals 2*CD0', ...
        'Best-range L/D matches parabolic-polar optimum', ...
        'Best-range glide angle is consistent with L/D', ...
        'Analytical range equals height times L/D', ...
        'Hybrid result preserves the POH 6000-ft range', ...
        'Minimum-sink CL exceeds best-range CL', ...
        'Minimum-sink strategy reduces sink rate', ...
        'Airspeed scales with square root of weight', ...
        'Optimum analytical range is weight independent', ...
        'Higher pressure altitude increases optimum TAS', ...
        'Analytical range is not silently calibrated to POH', ...
        'Terrain above start altitude is rejected', ...
        'Weight above maximum gross is rejected'};

    tests = { ...
        @() assertNear(poh2000.groundDistance_nm, 3, 1e-12), ...
        @() assertNear(poh6000.groundDistance_nm, 9, 1e-12), ...
        @() assertNear(poh12000.groundDistance_nm, 18, 1e-12), ...
        @() assertNear(poh12000.glideRatio_horizontalPerVertical, ...
            18 * NM_TO_FT / 12000, 1e-12), ...
        @() assertNear(poh12000.glideAngle_deg, ...
            atand(1 / poh12000.glideRatio_horizontalPerVertical), 1e-12), ...
        @() assertTrue(strcmp(poh6000.classification, ...
            'POH DATA/FIGURE INTERPOLATION')), ...
        @() assertError(@() pohMaximumGlide(12001), ...
            'pohMaximumGlide:OutsideChart'), ...
        @() assertAnyError(@() pohMaximumGlide(-1)), ...
        @() assertNear(nominal.bestRange.liftCoefficient, ...
            expectedBestRangeCL, 1e-10), ...
        @() assertNear(nominal.bestRange.dragCoefficient, ...
            2 * aircraft.CD0, 1e-10), ...
        @() assertNear(nominal.bestRange.liftToDragRatio, ...
            expectedBestRangeLD, 1e-10), ...
        @() assertNear(nominal.bestRange.glideAngle_deg, ...
            atand(1 / nominal.bestRange.liftToDragRatio), 1e-10), ...
        @() assertNear(nominal.bestRange.range_nm, expectedRange_nm, 1e-10), ...
        @() assertNear(nominal.poh.groundDistance_nm, 9, 1e-12), ...
        @() assertTrue(nominal.minimumSink.liftCoefficient > ...
            nominal.bestRange.liftCoefficient), ...
        @() assertTrue(nominal.minimumSink.startSinkRate_mps < ...
            nominal.bestRange.startSinkRate_mps), ...
        @() assertNear(lighter.bestRange.startTrueAirspeed_mps / ...
            nominal.bestRange.startTrueAirspeed_mps, ...
            expectedWeightSpeedRatio, 2e-6), ...
        @() assertNear(lighter.bestRange.range_nm, ...
            nominal.bestRange.range_nm, 1e-10), ...
        @() assertTrue(elevated.bestRange.startTrueAirspeed_mps > ...
            nominal.bestRange.startTrueAirspeed_mps), ...
        @() assertTrue(nominal.bestRange.range_nm > ...
            nominal.poh.groundDistance_nm && ...
            nominal.comparison.bestRangeDifference_percent > 0), ...
        @() assertError(@() glideDescentPerformance( ...
            aircraft, 4000, 5000, 0, 2550), ...
            'glideDescentPerformance:TerrainAboveStart'), ...
        @() assertError(@() glideDescentPerformance( ...
            aircraft, 4000, 0, 0, 2551), ...
            'glideDescentPerformance:WeightAboveMaximum')};

    passedChecks = 0;
    totalChecks = numel(tests);
    fprintf('============================================================\n');
    fprintf('C172S GLIDE AND DESCENT VALIDATION\n');
    fprintf('============================================================\n');
    for testIndex = 1:totalChecks
        try
            tests{testIndex}();
            passedChecks = passedChecks + 1;
            fprintf('[PASS] %s\n', testNames{testIndex});
        catch ME
            fprintf(2, '[FAIL] %s\n', testNames{testIndex});
            fprintf(2, '       %s\n', ME.message);
        end
    end

    fprintf('------------------------------------------------------------\n');
    fprintf('Result: %d/%d checks passed.\n', passedChecks, totalChecks);
    fprintf(['Scope: POH Figure 3-1 chart reproduction and internal ' ...
        'analytical consistency. This is not independent flight-test ' ...
        'validation of the drag polar or windmilling-propeller drag.\n']);

    summary = struct( ...
        'passedChecks', passedChecks, ...
        'totalChecks', totalChecks, ...
        'status', ternary(passedChecks == totalChecks, 'PASS', 'FAIL'));
    if passedChecks ~= totalChecks
        error('runGlideDescentValidation:ChecksFailed', ...
            '%d of %d glide/descent checks failed.', ...
            totalChecks - passedChecks, totalChecks);
    end
end

function assertNear(actual, expected, tolerance)
    if ~(isfinite(actual) && abs(actual - expected) <= tolerance)
        error('runGlideDescentValidation:NotNear', ...
            'Expected %.15g +/- %.3g, received %.15g.', ...
            expected, tolerance, actual);
    end
end

function assertTrue(condition)
    if ~isscalar(condition) || ~condition
        error('runGlideDescentValidation:AssertionFailed', ...
            'Expected condition to be true.');
    end
end

function assertError(functionHandle, expectedIdentifier)
    try
        functionHandle();
    catch ME
        if strcmp(ME.identifier, expectedIdentifier)
            return
        end
        error('runGlideDescentValidation:WrongError', ...
            'Expected %s, received %s.', expectedIdentifier, ME.identifier);
    end
    error('runGlideDescentValidation:MissingError', ...
        'Expected error %s was not raised.', expectedIdentifier);
end

function assertAnyError(functionHandle)
    try
        functionHandle();
    catch
        return
    end
    error('runGlideDescentValidation:MissingError', ...
        'Expected an error, but none was raised.');
end

function value = ternary(condition, trueValue, falseValue)
    if condition
        value = trueValue;
    else
        value = falseValue;
    end
end
