function runMissionFuelValidation()
%RUNMISSIONFUELVALIDATION Validate POH climb and mission-fuel calculations.

    names = {};
    passed = [];
    details = {};
    data = pohClimbFuelData();

    [names, passed, details] = addCheck(names, passed, details, ...
        'Complete POH Figure 5-7 point count', ...
        numel(data.pressureAltitude_ft), 13, 0, 'points');

    maximumTimeError = 0;
    maximumFuelError = 0;
    maximumDistanceError = 0;
    for index = 1:numel(data.pressureAltitude_ft)
        point = pohClimbFuelPerformance( ...
            0, data.pressureAltitude_ft(index), 0);
        maximumTimeError = max(maximumTimeError, ...
            abs(point.standardTime_min - data.timeFromSeaLevel_min(index)));
        maximumFuelError = max(maximumFuelError, ...
            abs(point.standardFuel_USgal - ...
                data.fuelFromSeaLevel_USgal(index)));
        maximumDistanceError = max(maximumDistanceError, ...
            abs(point.standardDistance_nm - ...
                data.distanceFromSeaLevel_nm(index)));
    end
    [names, passed, details] = addCheck(names, passed, details, ...
        'All POH climb-time grid points reproduce exactly', ...
        maximumTimeError, 0, 1e-12, 'min');
    [names, passed, details] = addCheck(names, passed, details, ...
        'All POH climb-fuel grid points reproduce exactly', ...
        maximumFuelError, 0, 1e-12, 'US gal');
    [names, passed, details] = addCheck(names, passed, details, ...
        'All POH climb-distance grid points reproduce exactly', ...
        maximumDistanceError, 0, 1e-12, 'NM');

    sampleClimb = pohClimbFuelPerformance(2000, 8000, 0);
    [names, passed, details] = addCheck(names, passed, details, ...
        'POH sample climb time: 2000 to 8000 ft', ...
        sampleClimb.standardTime_min, 11, 1e-12, 'min');
    [names, passed, details] = addCheck(names, passed, details, ...
        'POH sample climb fuel: 2000 to 8000 ft', ...
        sampleClimb.standardFuel_USgal, 2.2, 1e-12, 'US gal');
    [names, passed, details] = addCheck(names, passed, details, ...
        'POH sample climb distance: 2000 to 8000 ft', ...
        sampleClimb.standardDistance_nm, 15, 1e-12, 'NM');

    hotClimb = pohClimbFuelPerformance(2000, 8000, 16);
    [names, passed, details] = addCheck(names, passed, details, ...
        'POH hot-day climb correction factor at ISA +16 C', ...
        hotClimb.temperatureCorrectionFactor, 1.16, 1e-12, '-');
    [names, passed, details] = addCheck(names, passed, details, ...
        'Unrounded hot-day climb fuel', ...
        hotClimb.correctedFuel_USgal, 2.552, 1e-12, 'US gal');
    [names, passed, details] = addCheck(names, passed, details, ...
        'Hot-day climb fuel rounds upward to POH sample value', ...
        hotClimb.planningFuel_USgal, 2.6, 1e-12, 'US gal');

    coldClimb = pohClimbFuelPerformance(2000, 8000, -20);
    [names, passed, details] = addCheck(names, passed, details, ...
        'No unsupported cold-day climb credit', ...
        coldClimb.temperatureCorrectionFactor, 1.0, 1e-12, '-');
    [names, passed, details] = addCheck(names, passed, details, ...
        'POH start/taxi/takeoff fuel allowance', ...
        data.startTaxiTakeoffAllowance_USgal, 1.4, 1e-12, 'US gal');

    aircraft = cessna172();
    [names, passed, details] = addCheck(names, passed, details, ...
        'Published total fuel capacity', ...
        aircraft.fuelTotal_USgal, 56, 1e-12, 'US gal');
    [names, passed, details] = addCheck(names, passed, details, ...
        'Published usable fuel capacity', ...
        aircraft.fuelUsable_USgal, 53, 1e-12, 'US gal');

    mission = pohMissionFuelPlanning( ...
        0, 4000, 0, 2400, 300, 10, 53, 45, 10, true);
    [names, passed, details] = addCheck(names, passed, details, ...
        'Mission cruise true airspeed from POH', ...
        mission.cruiseTrueAirspeed_KTAS, 109, 1e-12, 'KTAS');
    [names, passed, details] = addCheck(names, passed, details, ...
        'Mission cruise fuel flow from POH', ...
        mission.cruise.fuelFlow_GPH, 8.5, 1e-12, 'US gal/h');
    [names, passed, details] = addCheck(names, passed, details, ...
        'Mission cruise groundspeed with 10-kt headwind', ...
        mission.cruiseGroundSpeed_kt, 99, 1e-12, 'kt');
    [names, passed, details] = addCheck(names, passed, details, ...
        'Mission nominal trip fuel', ...
        mission.nominalTripFuel_USgal, 27.9707070707071, ...
        1e-10, 'US gal');
    [names, passed, details] = addCheck(names, passed, details, ...
        'Mission exact required fuel including contingency and reserve', ...
        mission.requiredFuel_USgal, 37.1427777777778, ...
        1e-10, 'US gal');
    [names, passed, details] = addCheck(names, passed, details, ...
        'Mission component-rounded planning fuel', ...
        mission.planningRequiredFuel_USgal, 37.2, 1e-12, 'US gal');
    [names, passed, details] = addCheck(names, passed, details, ...
        'Mission maximum range under selected policy', ...
        mission.maximumRouteDistance_nm, 467.9, 1e-10, 'NM');

    names{end + 1} = 'Mission fuel status passes with full usable fuel';
    passed(end + 1) = mission.missionFeasible;
    details{end + 1} = sprintf('planning margin %.3f US gal', ...
        mission.planningFuelMargin_USgal);

    rejectedDescendingRoute = false;
    try
        pohClimbFuelPerformance(5000, 4000, 0);
    catch ME
        rejectedDescendingRoute = strcmp(ME.identifier, ...
            'pohClimbFuelPerformance:DescendingRoute');
    end
    names{end + 1} = 'Climb planner rejects departure above cruise altitude';
    passed(end + 1) = rejectedDescendingRoute;
    details{end + 1} = 'Expected model-envelope rejection';

    rejectedWind = false;
    try
        pohMissionFuelPlanning(0, 4000, 0, 2400, ...
            300, 109, 53, 45, 10, true);
    catch ME
        rejectedWind = strcmp(ME.identifier, ...
            'pohMissionFuelPlanning:NonpositiveGroundSpeed');
    end
    names{end + 1} = 'Mission planner rejects nonpositive groundspeed';
    passed(end + 1) = rejectedWind;
    details{end + 1} = 'Expected wind-envelope rejection';

    rejectedFuel = false;
    try
        pohMissionFuelPlanning(0, 4000, 0, 2400, ...
            300, 0, 54, 45, 10, true);
    catch ME
        rejectedFuel = strcmp(ME.identifier, ...
            'pohMissionFuelPlanning:FuelAboveUsableCapacity');
    end
    names{end + 1} = 'Mission planner rejects fuel above usable capacity';
    passed(end + 1) = rejectedFuel;
    details{end + 1} = 'Expected published-capacity rejection';

    names{end + 1} = 'Mission model is labelled POH-based, not dispatch';
    passed(end + 1) = contains(mission.classification, ...
        'not dispatch authorization');
    details{end + 1} = mission.classification;

    fprintf('==================================================\n');
    fprintf('C172 POH MISSION-FUEL VALIDATION\n');
    fprintf('==================================================\n');
    for testIndex = 1:numel(names)
        if passed(testIndex)
            status = 'PASS';
        else
            status = 'FAIL';
        end
        fprintf('[%s] %s - %s\n', ...
            status, names{testIndex}, details{testIndex});
    end
    numberPassed = sum(passed);
    fprintf('\nResult: %d/%d checks passed.\n', ...
        numberPassed, numel(passed));
    if numberPassed ~= numel(passed)
        error('runMissionFuelValidation:Failed', ...
            '%d mission-fuel checks failed.', numel(passed) - numberPassed);
    end
end

function [names, passed, details] = addCheck( ...
        names, passed, details, name, actual, expected, tolerance, unit)

    names{end + 1} = name;
    passed(end + 1) = isfinite(actual) && ...
        abs(actual - expected) <= tolerance;
    details{end + 1} = sprintf( ...
        'actual %.8g %s, expected %.8g +/- %.3g %s', ...
        actual, unit, expected, tolerance, unit);
end
