function runRangeEnduranceProfileValidation()
%RUNRANGEENDURANCEPROFILEVALIDATION Audit POH cross-chart consistency.
%
%   This suite reconstructs Figures 5-9 and 5-10 from the centralized
%   Figure 5-7 climb data and Figure 5-8 cruise data, then compares the
%   results with digitized line-center readings from the published profile
%   graphics. The comparison checks integration consistency; it is not an
%   independent validation using a separate flight-test dataset.

    names = {};
    passed = [];
    details = {};
    data = pohRangeEnduranceProfileData();

    [names, passed, details] = addEqualityCheck( ...
        names, passed, details, ...
        'Figure 5-9/5-10 usable-fuel condition', ...
        data.usableFuel_USgal, 53, 1e-12, 'US gal');
    [names, passed, details] = addEqualityCheck( ...
        names, passed, details, ...
        'Figure 5-9/5-10 reserve condition', ...
        data.reserveTime_min, 45, 1e-12, 'min');

    numberComparisonPoints = sum(data.figure58ComparisonMask(:));
    [names, passed, details] = addEqualityCheck( ...
        names, passed, details, ...
        'No-extrapolation POH profile comparison-point count', ...
        numberComparisonPoints, 20, 0, 'points');

    anchorSetting = pohCruiseAtPower(6000, 65, 0);
    [names, passed, details] = addEqualityCheck( ...
        names, passed, details, ...
        'Figure 5-8 inversion anchor RPM: 6000 ft, 65 percent MCP', ...
        anchorSetting.solvedRPM, 2500, 1e-8, 'RPM');
    [names, passed, details] = addEqualityCheck( ...
        names, passed, details, ...
        'Figure 5-8 inversion anchor airspeed', ...
        anchorSetting.trueAirspeed_KTAS, 114, 1e-10, 'KTAS');
    [names, passed, details] = addEqualityCheck( ...
        names, passed, details, ...
        'Figure 5-8 inversion anchor fuel flow', ...
        anchorSetting.fuelFlow_GPH, 9.0, 1e-10, 'US gal/h');

    anchorProfile = pohRangeEnduranceProfile(6000, 65);
    [names, passed, details] = addEqualityCheck( ...
        names, passed, details, ...
        'Reconstructed range anchor: 6000 ft, 65 percent MCP', ...
        anchorProfile.range_nm, 553.233333333333, 1e-9, 'NM');
    [names, passed, details] = addEqualityCheck( ...
        names, passed, details, ...
        'Reconstructed endurance anchor: 6000 ft, 65 percent MCP', ...
        anchorProfile.endurance_h, 4.90555555555556, 1e-10, 'h');

    rangeErrors_nm = zeros(numberComparisonPoints, 1);
    enduranceErrors_h = zeros(numberComparisonPoints, 1);
    pointIndex = 0;
    for altitudeIndex = 1:numel(data.altitudeGrid_ft)
        for powerIndex = 1:numel(data.powerLevels_pct)
            if ~data.figure58ComparisonMask(altitudeIndex, powerIndex)
                continue
            end
            pointIndex = pointIndex + 1;
            profile = pohRangeEnduranceProfile( ...
                data.altitudeGrid_ft(altitudeIndex), ...
                data.powerLevels_pct(powerIndex));
            rangeErrors_nm(pointIndex) = profile.range_nm - ...
                data.range_nm(altitudeIndex, powerIndex);
            enduranceErrors_h(pointIndex) = profile.endurance_h - ...
                data.endurance_h(altitudeIndex, powerIndex);
        end
    end

    rangeRMS_nm = sqrt(mean(rangeErrors_nm .^ 2));
    rangeMaximum_nm = max(abs(rangeErrors_nm));
    enduranceRMS_h = sqrt(mean(enduranceErrors_h .^ 2));
    enduranceMaximum_h = max(abs(enduranceErrors_h));
    [names, passed, details] = addUpperBoundCheck( ...
        names, passed, details, ...
        'Figure 5-9 digitized-profile RMS range closure', ...
        rangeRMS_nm, data.rangeGateRMS_nm, 'NM');
    [names, passed, details] = addUpperBoundCheck( ...
        names, passed, details, ...
        'Figure 5-9 digitized-profile maximum range closure', ...
        rangeMaximum_nm, data.rangeGateMaximum_nm, 'NM');
    [names, passed, details] = addUpperBoundCheck( ...
        names, passed, details, ...
        'Figure 5-10 digitized-profile RMS endurance closure', ...
        enduranceRMS_h, data.enduranceGateRMS_h, 'h');
    [names, passed, details] = addUpperBoundCheck( ...
        names, passed, details, ...
        'Figure 5-10 digitized-profile maximum endurance closure', ...
        enduranceMaximum_h, data.enduranceGateMaximum_h, 'h');

    rejectedUnavailablePower = false;
    try
        pohCruiseAtPower(10000, 75, 0);
    catch ME
        rejectedUnavailablePower = strcmp(ME.identifier, ...
            'pohCruiseAtPower:PowerOutsidePOH');
    end
    names{end + 1} = ...
        'Power inversion rejects unavailable fixed-power condition';
    passed(end + 1) = rejectedUnavailablePower;
    details{end + 1} = ...
        'Expected rejection of 75 percent MCP at 10000 ft';

    rejectedSeaLevelCruise = false;
    try
        pohRangeEnduranceProfile(0, 65);
    catch ME
        rejectedSeaLevelCruise = strcmp(ME.identifier, ...
            'pohCruiseAtPower:AltitudeOutsidePOH');
    end
    names{end + 1} = ...
        'Profile reconstruction does not extend Figure 5-8 below 2000 ft';
    passed(end + 1) = rejectedSeaLevelCruise;
    details{end + 1} = ...
        'Expected no-extrapolation altitude rejection';

    names{end + 1} = ...
        'Profile audit is labelled cross-chart, not independent validation';
    passed(end + 1) = contains(anchorProfile.classification, ...
        'not independent flight-test validation');
    details{end + 1} = anchorProfile.classification;

    fprintf('==================================================\n');
    fprintf('C172 POH RANGE/ENDURANCE PROFILE VALIDATION\n');
    fprintf('==================================================\n');
    fprintf('Comparison points: %d\n', numberComparisonPoints);
    fprintf(['Reference type: digitized Figures 5-9/5-10 graphical ' ...
        'line-center readings\n\n']);
    for testIndex = 1:numel(names)
        if passed(testIndex)
            status = 'PASS';
        else
            status = 'FAIL';
        end
        fprintf('[%s] %s - %s\n', ...
            status, names{testIndex}, details{testIndex});
    end

    numberPassed = sum(passed);
    fprintf('\nResult: %d/%d checks passed.\n', ...
        numberPassed, numel(passed));
    fprintf(['Scope: POH cross-chart consistency only; the profile ' ...
        'graphics are not an independent flight-test dataset.\n']);
    if numberPassed ~= numel(passed)
        error('runRangeEnduranceProfileValidation:Failed', ...
            '%d range/endurance profile checks failed.', ...
            numel(passed) - numberPassed);
    end
end

function [names, passed, details] = addEqualityCheck( ...
        names, passed, details, name, actual, expected, tolerance, unit)

    names{end + 1} = name;
    passed(end + 1) = isfinite(actual) && ...
        abs(actual - expected) <= tolerance;
    details{end + 1} = sprintf( ...
        'actual %.8g %s, expected %.8g +/- %.3g %s', ...
        actual, unit, expected, tolerance, unit);
end

function [names, passed, details] = addUpperBoundCheck( ...
        names, passed, details, name, actual, limit, unit)

    names{end + 1} = name;
    passed(end + 1) = isfinite(actual) && actual <= limit;
    details{end + 1} = sprintf( ...
        'actual %.8g %s, required <= %.8g %s', ...
        actual, unit, limit, unit);
end