function summary = runTurnPerformanceValidation()
%RUNTURNPERFORMANCEVALIDATION Validate Mode 9 maneuver/turn calculations.

    RHO0 = 1.2250;
    G_MPS2 = 9.80665;

    aircraft = cessna172();
    limits1900 = pohManeuverLimits(1900);
    limits2200 = pohManeuverLimits(2200);
    limits2550 = pohManeuverLimits(2550);
    limits2375 = pohManeuverLimits(2375);

    wingsLevel = turnPerformance(aircraft, 0, 0, 2550, 95, 0);
    nominal = turnPerformance(aircraft, 0, 0, 2550, 95, 45);
    sixtyDegree = turnPerformance(aircraft, 0, 0, 2550, 95, 60);
    highAltitude = turnPerformance(aircraft, 10000, 0, 2550, 95, 45);
    lighter = turnPerformance(aircraft, 0, 0, 2200, 95, 45);
    slow = turnPerformance(aircraft, 0, 0, 2550, 60, 60);
    aboveVa = turnPerformance(aircraft, 0, 0, 2550, 110, 45);
    aboveVno = turnPerformance(aircraft, 0, 0, 2550, 130, 45);

    expectedRadius_m = nominal.trueAirspeed_mps^2 / ...
        (G_MPS2 * tand(nominal.bankAngle_deg));
    expectedTurnRate_degps = rad2deg( ...
        G_MPS2 * tand(nominal.bankAngle_deg) / ...
        nominal.trueAirspeed_mps);
    expectedTimeFor360_s = 360 / expectedTurnRate_degps;
    expectedSeaLevelTAS_KTAS = 95 * sqrt(RHO0 / nominal.atmosphere.rho);
    expectedSlowBank_deg = acosd(1 / ...
        (slow.airspeed_KCAS / slow.levelStallSpeed_KCAS)^2);

    testNames = { ...
        'POH VA row at 1900 lb reproduces 88 KCAS / 90 KIAS', ...
        'POH VA row at 2200 lb reproduces 95 KCAS / 98 KIAS', ...
        'POH VA row at 2550 lb reproduces 102 KCAS / 105 KIAS', ...
        'VA is linearly interpolated inside the published table', ...
        'POH VNO reproduces 126 KCAS / 129 KIAS', ...
        'POH VNE reproduces 160 KCAS / 163 KIAS', ...
        'Normal-category flaps-up load limits are +3.8 / -1.52 g', ...
        'POH bank boundary and steep-turn entry speed are preserved', ...
        'POH result distinguishes exact data from interpolation', ...
        'VA provider rejects extrapolation below 1900 lb', ...
        'VA provider rejects extrapolation above 2550 lb', ...
        'Wings-level case has n=1 and no finite turn', ...
        'A 60-degree level turn has load factor 2', ...
        '2550-lb flaps-up level stall speed is 53 KCAS', ...
        'Accelerated stall speed follows VS times sqrt(n)', ...
        'Turn radius follows V_TAS squared over g tan(bank)', ...
        'Turn rate follows g tan(bank) over V_TAS', ...
        'Time for 360 degrees is consistent with turn rate', ...
        'Nominal 95-KCAS 45-degree turn is stall-feasible', ...
        'A 60-KCAS 60-degree turn is correctly stall-infeasible', ...
        'Maximum permitted bank honors the stall boundary', ...
        'KCAS-to-TAS conversion uses density and KCAS approx KEAS', ...
        'Higher altitude increases radius at fixed KCAS and bank', ...
        'Higher altitude reduces turn rate at fixed KCAS and bank', ...
        'Weight-adjusted stall speed follows square-root scaling', ...
        'Airspeed above weight-adjusted VA is flagged', ...
        'Airspeed above VNO is flagged as the caution range', ...
        'Bank angle above 60 degrees is rejected', ...
        'Airspeed above 160 KCAS VNE is rejected', ...
        'Altitude and temperature model envelopes are enforced'};

    tests = { ...
        @() assertVectorNear([limits1900.maneuveringSpeed_KCAS, ...
            limits1900.maneuveringSpeed_KIAS], [88, 90], 1e-12), ...
        @() assertVectorNear([limits2200.maneuveringSpeed_KCAS, ...
            limits2200.maneuveringSpeed_KIAS], [95, 98], 1e-12), ...
        @() assertVectorNear([limits2550.maneuveringSpeed_KCAS, ...
            limits2550.maneuveringSpeed_KIAS], [102, 105], 1e-12), ...
        @() assertVectorNear([limits2375.maneuveringSpeed_KCAS, ...
            limits2375.maneuveringSpeed_KIAS], [98.5, 101.5], 1e-12), ...
        @() assertVectorNear([ ...
            limits2550.maximumStructuralCruisingSpeed_KCAS, ...
            limits2550.maximumStructuralCruisingSpeed_KIAS], ...
            [126, 129], 1e-12), ...
        @() assertVectorNear([limits2550.neverExceedSpeed_KCAS, ...
            limits2550.neverExceedSpeed_KIAS], [160, 163], 1e-12), ...
        @() assertVectorNear([limits2550.positiveLoadFactorLimit_g, ...
            limits2550.negativeLoadFactorLimit_g], [3.8, -1.52], 1e-12), ...
        @() assertVectorNear([ ...
            limits2550.maximumNormalCategoryBankAngle_deg, ...
            limits2550.recommendedSteepTurnEntrySpeed_KIAS], ...
            [60, 95], 1e-12), ...
        @() assertTrue(strcmp(limits2550.classification, ...
            'POH DATA/TABLE VALUE') && ...
            strcmp(limits2375.classification, ...
                'POH DATA/LINEAR INTERPOLATION') && ...
            contains(limits2375.interpolationStatus, ...
                'LINEAR INTERPOLATION')), ...
        @() assertError(@() pohManeuverLimits(1899), ...
            'pohManeuverLimits:WeightOutsideTable'), ...
        @() assertError(@() pohManeuverLimits(2551), ...
            'pohManeuverLimits:WeightOutsideTable'), ...
        @() assertTrue(wingsLevel.loadFactor_g == 1 && ...
            isinf(wingsLevel.turnRadius_m) && ...
            wingsLevel.turnRate_degps == 0 && ...
            isinf(wingsLevel.timeFor360_s)), ...
        @() assertNear(sixtyDegree.loadFactor_g, 2, 1e-12), ...
        @() assertNear(nominal.levelStallSpeed_KCAS, 53, 1e-12), ...
        @() assertNear(sixtyDegree.acceleratedStallSpeed_KCAS, ...
            53 * sqrt(2), 1e-12), ...
        @() assertNear(nominal.turnRadius_m, expectedRadius_m, 1e-10), ...
        @() assertNear(nominal.turnRate_degps, ...
            expectedTurnRate_degps, 1e-12), ...
        @() assertNear(nominal.timeFor360_s, ...
            expectedTimeFor360_s, 1e-12), ...
        @() assertTrue(nominal.turnFeasible && ...
            nominal.stallSpeedMargin_KCAS > 0), ...
        @() assertTrue(~slow.turnFeasible && slow.stallSpeedMargin_KCAS < 0), ...
        @() assertNear(slow.maximumPermittedBankAngle_deg, ...
            expectedSlowBank_deg, 1e-12), ...
        @() assertNear(nominal.trueAirspeed_KTAS, ...
            expectedSeaLevelTAS_KTAS, 1e-12), ...
        @() assertTrue(highAltitude.turnRadius_m > nominal.turnRadius_m), ...
        @() assertTrue(highAltitude.turnRate_degps < ...
            nominal.turnRate_degps), ...
        @() assertNear(lighter.levelStallSpeed_KCAS / ...
            nominal.levelStallSpeed_KCAS, sqrt(2200 / 2550), 1e-12), ...
        @() assertTrue(aboveVa.aboveManeuveringSpeed && ...
            ~aboveVa.aboveMaximumStructuralCruisingSpeed && ...
            contains(aboveVa.airspeedRegion, 'ABOVE VA')), ...
        @() assertTrue(aboveVno.aboveManeuveringSpeed && ...
            aboveVno.aboveMaximumStructuralCruisingSpeed && ...
            contains(aboveVno.airspeedRegion, 'ABOVE VNO')), ...
        @() assertError(@() turnPerformance( ...
            aircraft, 0, 0, 2550, 95, 60.1), ...
            'turnPerformance:BankAngleOutsideNormalCategory'), ...
        @() assertError(@() turnPerformance( ...
            aircraft, 0, 0, 2550, 160.1, 45), ...
            'turnPerformance:AirspeedAboveVNE'), ...
        @() assertEnvelopeErrors(aircraft)};

    passedChecks = 0;
    totalChecks = numel(tests);
    fprintf('============================================================\n');
    fprintf('C172S TURN AND MANEUVER PERFORMANCE VALIDATION\n');
    fprintf('============================================================\n');
    for testIndex = 1:totalChecks
        try
            tests{testIndex}();
            passedChecks = passedChecks + 1;
            fprintf('[PASS] %s\n', testNames{testIndex});
        catch ME
            fprintf(2, '[FAIL] %s\n', testNames{testIndex});
            fprintf(2, '       %s\n', ME.message);
        end
    end

    fprintf('------------------------------------------------------------\n');
    fprintf('Result: %d/%d checks passed.\n', passedChecks, totalChecks);
    fprintf(['Scope: published normal-category limits, in-table VA ' ...
        'interpolation, and internal coordinated-level-turn equation ' ...
        'consistency. This is not an independently identified gust ' ...
        'envelope or flight-test validation.\n']);

    summary = struct( ...
        'passedChecks', passedChecks, ...
        'totalChecks', totalChecks, ...
        'status', ternary(passedChecks == totalChecks, 'PASS', 'FAIL'));
    if passedChecks ~= totalChecks
        error('runTurnPerformanceValidation:ChecksFailed', ...
            '%d of %d turn-performance checks failed.', ...
            totalChecks - passedChecks, totalChecks);
    end
end

function assertEnvelopeErrors(aircraft)
    assertError(@() turnPerformance( ...
        aircraft, 12001, 0, 2550, 95, 45), ...
        'turnPerformance:AltitudeOutsideModel');
    assertError(@() turnPerformance( ...
        aircraft, 0, 20.1, 2550, 95, 45), ...
        'turnPerformance:TemperatureOutsideModel');
end

function assertNear(actual, expected, tolerance)
    if ~(isfinite(actual) && abs(actual - expected) <= tolerance)
        error('runTurnPerformanceValidation:NotNear', ...
            'Expected %.15g +/- %.3g, received %.15g.', ...
            expected, tolerance, actual);
    end
end

function assertVectorNear(actual, expected, tolerance)
    if ~isequal(size(actual), size(expected)) || ...
            any(~isfinite(actual)) || ...
            any(abs(actual - expected) > tolerance)
        error('runTurnPerformanceValidation:VectorNotNear', ...
            'Vector values differ by more than %.3g.', tolerance);
    end
end

function assertTrue(condition)
    if ~isscalar(condition) || ~condition
        error('runTurnPerformanceValidation:AssertionFailed', ...
            'Expected condition to be true.');
    end
end

function assertError(functionHandle, expectedIdentifier)
    try
        functionHandle();
    catch ME
        if strcmp(ME.identifier, expectedIdentifier)
            return
        end
        error('runTurnPerformanceValidation:WrongError', ...
            'Expected %s, received %s.', expectedIdentifier, ME.identifier);
    end
    error('runTurnPerformanceValidation:MissingError', ...
        'Expected error %s was not raised.', expectedIdentifier);
end

function value = ternary(condition, trueValue, falseValue)
    if condition
        value = trueValue;
    else
        value = falseValue;
    end
end
