function runValidation()
%RUNVALIDATION Execute numerical checks for the C172S performance tool.

    KT_TO_MPS = 0.514444;
    aircraft = cessna172();
    atmSL = atmosphereAtPressureAltitude(0, 0);

    testNames = {};
    passed = [];
    details = {};

    [testNames, passed, details] = addCheck(testNames, passed, details, ...
        'ISA sea-level temperature', atmSL.T, 288.15, 1e-10, 'K');
    [testNames, passed, details] = addCheck(testNames, passed, details, ...
        'ISA sea-level pressure', atmSL.P, 101325, 1e-6, 'Pa');
    [testNames, passed, details] = addCheck(testNames, passed, details, ...
        'ISA sea-level density', atmSL.rho, 1.2250, 5e-4, 'kg/m^3');
    [testNames, passed, details] = addCheck(testNames, passed, details, ...
        'C172 aspect ratio', aircraft.AR, 7.4691, 5e-4, '-');

    stall_kt = stallSpeed(aircraft, atmSL) / KT_TO_MPS;
    [testNames, passed, details] = addCheck(testNames, passed, details, ...
        'Flaps-up stall speed at 2550 lb', stall_kt, 53.0, 1.0, 'kt');

    [testNames, passed, details] = addCheck(testNames, passed, details, ...
        'FAA 172S static-RPM lower limit', ...
        aircraft.propRPMstaticRange(1), 2300, 1e-10, 'RPM');
    [testNames, passed, details] = addCheck(testNames, passed, details, ...
        'FAA 172S static-RPM upper limit', ...
        aircraft.propRPMstaticRange(2), 2400, 1e-10, 'RPM');
    [testNames, passed, details] = addCheck(testNames, passed, details, ...
        'JHA7660 pitch at 75-percent radius', ...
        aircraft.propPitchAt75Radius / 0.0254, 60, 1e-10, 'in');

    speeds = characteristicSpeeds(aircraft, atmSL);
    speedRatio = speeds.minimumDragTheory_mps / ...
        speeds.minimumPowerTheory_mps;
    [testNames, passed, details] = addCheck(testNames, passed, details, ...
        'Vmd/Vmp parabolic-polar relation', ...
        speedRatio, 3^(1/4), 1e-10, '-');

    [~, cruiseInfo] = enginePowerAvailable(4000, 2400, 0);
    cruiseLookup = pohCruiseTableLookup(4000, 2400, 0);
    [testNames, passed, details] = addCheck(testNames, passed, details, ...
        'POH cruise grid point: 4000 ft, 2400 RPM, ISA', ...
        cruiseInfo.percentMCP, 61, 1e-10, '%MCP');

    [testNames, passed, details] = addCheck(testNames, passed, details, ...
        'POH cruise KTAS grid point: 4000 ft, 2400 RPM, ISA', ...
        cruiseLookup.trueAirspeed_KTAS, 109, 1e-10, 'KTAS');
    [testNames, passed, details] = addCheck(testNames, passed, details, ...
        'POH cruise fuel-flow grid point: 4000 ft, 2400 RPM, ISA', ...
        cruiseLookup.fuelFlow_GPH, 8.5, 1e-10, 'US gal/h');

    cruiseInterior = pohCruiseTableLookup(5000, 2400, 10);
    [testNames, passed, details] = addCheck(testNames, passed, details, ...
        'Interior cruise interpolation percent MCP', ...
        cruiseInterior.percentMCP, 57.25, 1e-10, '%MCP');
    [testNames, passed, details] = addCheck(testNames, passed, details, ...
        'Interior cruise interpolation true airspeed', ...
        cruiseInterior.trueAirspeed_KTAS, 107.5, 1e-10, 'KTAS');
    [testNames, passed, details] = addCheck(testNames, passed, details, ...
        'Interior cruise interpolation fuel flow', ...
        cruiseInterior.fuelFlow_GPH, 8.125, 1e-10, 'US gal/h');

    cruiseData = pohCruiseData();

    cruisePointCount = ...
        sum(cellfun(@numel, cruiseData.rpmGrid)) * ...
        numel(cruiseData.deltaISAColumns_C);
    [testNames, passed, details] = addCheck(testNames, passed, details, ...
        'Complete POH Figure 5-8 audit-point count', ...
        cruisePointCount, 111, 1e-10, 'points');

    cruiseGridErrors = maximumCruiseGridErrors(cruiseData);
    [testNames, passed, details] = addCheck(testNames, passed, details, ...
        'All POH cruise percent-MCP grid points reproduce exactly', ...
        cruiseGridErrors.percentMCP, 0, 1e-10, '%MCP');
    [testNames, passed, details] = addCheck(testNames, passed, details, ...
        'All POH cruise KTAS grid points reproduce exactly', ...
        cruiseGridErrors.trueAirspeed_KTAS, 0, 1e-10, 'KTAS');
    [testNames, passed, details] = addCheck(testNames, passed, details, ...
        'All POH cruise fuel-flow grid points reproduce exactly', ...
        cruiseGridErrors.fuelFlow_GPH, 0, 1e-10, 'US gal/h');

    noFairings = pohCruisePerformance(4000, 2400, 0, 2550, false);
    [testNames, passed, details] = addCheck(testNames, passed, details, ...
        'POH no-fairing cruise correction', ...
        noFairings.selectedConfigurationKTAS, 107, 1e-10, 'KTAS');

    upperPowerWeight = pohCruisePerformance( ...
        4000, 2500, 0, 2400, true);
    [testNames, passed, details] = addCheck(testNames, passed, details, ...
        'POH reduced-weight correction in 65-to-75-percent band', ...
        upperPowerWeight.selectedConfigurationKTAS, ...
        116, 1e-10, 'KTAS');

    lowerPowerWeight = pohCruisePerformance( ...
        4000, 2300, 0, 2425, true);
    [testNames, passed, details] = addCheck(testNames, passed, details, ...
        'POH reduced-weight correction below 55 percent MCP', ...
        lowerPowerWeight.selectedConfigurationKTAS, ...
        103, 1e-10, 'KTAS');

    ambiguousWeight = pohCruisePerformance( ...
        4000, 2400, 0, 2400, true);
    testNames{end + 1} = ...
        'Cruise tool does not guess within overlapping POH weight rules';
    passed(end + 1) = ...
        ~ambiguousWeight.weightCorrectionAvailable && ...
        isnan(ambiguousWeight.selectedConfigurationKTAS);
    details{end + 1} = ...
        'Expected unavailable result in the published 55-to-below-65-percent overlap';

    above75Weight = pohCruisePerformance( ...
        8000, 2700, 0, 2400, true);
    testNames{end + 1} = ...
        'Cruise tool does not extrapolate weight correction above 75 percent MCP';
    passed(end + 1) = ...
        ~above75Weight.weightCorrectionAvailable && ...
        isnan(above75Weight.selectedConfigurationKTAS);
    details{end + 1} = ...
        'Expected unavailable result outside published reduced-weight correction';

    climbExact = pohClimbPerformance(0, -15);
    [testNames, passed, details] = addCheck(testNames, passed, details, ...
        'POH climb grid point: sea level, 0 C OAT', ...
        climbExact.rateOfClimb_fpm, 785, 1e-10, 'ft/min');

    climbStandard = pohClimbPerformance(4000, 0);
    [testNames, passed, details] = addCheck(testNames, passed, details, ...
        'Standard-day climb cross-check at 4000 ft', ...
        climbStandard.rateOfClimb_fpm, 600, 5, 'ft/min');

    climbSweep = climbAltitudeSweep(1000);
    index8000 = find(climbSweep.altitude_ft == 8000, 1);
    index12000 = find(climbSweep.altitude_ft == 12000, 1);
    column20C = find(climbSweep.oatColumns_C == 20, 1);
    column40C = find(climbSweep.oatColumns_C == 40, 1);

    [testNames, passed, details] = addCheck(testNames, passed, details, ...
        'Standard-day climb sweep at 8000 ft', ...
        climbSweep.standardDayRateOfClimb_fpm(index8000), ...
        410, 5, 'ft/min');
    [testNames, passed, details] = addCheck(testNames, passed, details, ...
        'POH climb sweep: 12000 ft and 20 C OAT', ...
        climbSweep.rateOfClimb_fpm(index12000, column20C), ...
        135, 1e-10, 'ft/min');

    missingUnpublishedClimbPoint = ...
        isnan(climbSweep.rateOfClimb_fpm(index12000, column40C));
    testNames{end + 1} = ...
        'Climb sweep does not extrapolate unpublished 12000-ft/40-C point';
    passed(end + 1) = missingUnpublishedClimbPoint;
    details{end + 1} = 'Expected NaN for unpublished POH entry';

    takeoffData = pohTakeoffData();
    takeoffPointCount = numel(takeoffData.weightGrid_lb) * ...
        numel(takeoffData.altitudeGrid_ft) * ...
        numel(takeoffData.temperatureGrid_C);
    [testNames, passed, details] = addCheck(testNames, passed, details, ...
        'Complete POH Figure 5-5 takeoff point count', ...
        takeoffPointCount, 135, 1e-10, 'points');

    takeoffGridErrors = maximumTakeoffGridErrors(takeoffData);
    [testNames, passed, details] = addCheck(testNames, passed, details, ...
        'All POH takeoff ground-roll points reproduce exactly', ...
        takeoffGridErrors.groundRoll_ft, 0, 1e-10, 'ft');
    [testNames, passed, details] = addCheck(testNames, passed, details, ...
        'All POH takeoff over-50-ft points reproduce exactly', ...
        takeoffGridErrors.totalOver50ft_ft, 0, 1e-10, 'ft');

    takeoffExact = pohTakeoffPerformance(2550, 0, 0, 0, 'paved');
    [testNames, passed, details] = addCheck(testNames, passed, details, ...
        'POH takeoff anchor: 2550 lb, sea level, 0 C ground roll', ...
        takeoffExact.interpolated.baseGroundRoll_ft, ...
        860, 1e-10, 'ft');
    [testNames, passed, details] = addCheck(testNames, passed, details, ...
        'POH takeoff anchor: 2550 lb, sea level, 0 C over 50 ft', ...
        takeoffExact.interpolated.baseTotalOver50ft_ft, ...
        1465, 1e-10, 'ft');

    takeoffInterior = pohTakeoffPerformance( ...
        2300, 1500, 15, 0, 'paved');
    [testNames, passed, details] = addCheck(testNames, passed, details, ...
        'Interior takeoff interpolation ground roll', ...
        takeoffInterior.interpolated.baseGroundRoll_ft, ...
        865, 1e-10, 'ft');
    [testNames, passed, details] = addCheck(testNames, passed, details, ...
        'Interior takeoff interpolation over 50 ft', ...
        takeoffInterior.interpolated.baseTotalOver50ft_ft, ...
        1476.875, 1e-10, 'ft');

    takeoffConservative = pohTakeoffPerformance( ...
        2550, 1500, 28, 0, 'paved');
    [testNames, passed, details] = addCheck(testNames, passed, details, ...
        'Conservative takeoff grid selects next-higher POH point', ...
        takeoffConservative.conservative.baseTotalOver50ft_ft, ...
        2190, 1e-10, 'ft');

    takeoffHeadwind = pohTakeoffPerformance( ...
        2550, 0, 0, 9, 'paved');
    [testNames, passed, details] = addCheck(testNames, passed, details, ...
        'POH takeoff 9-kt headwind correction', ...
        takeoffHeadwind.interpolated.groundRoll_ft, ...
        774, 1e-10, 'ft');

    takeoffGrass = pohTakeoffPerformance( ...
        2550, 0, 0, 0, 'dry grass');
    [testNames, passed, details] = addCheck(testNames, passed, details, ...
        'POH takeoff dry-grass correction', ...
        takeoffGrass.interpolated.totalOver50ft_ft, ...
        1594, 1e-10, 'ft');

    combinedCorrections = applyPohFieldCorrections( ...
        1000, 2000, 9, 0.15, 1, 10);
    [testNames, passed, details] = addCheck(testNames, passed, details, ...
        'Combined wind and grass corrections use tabulated ground roll', ...
        combinedCorrections.totalOver50ft_ft, ...
        1950, 1e-10, 'ft');

    rejectedTakeoffExtrapolation = false;
    try
        pohTakeoffPerformance(2100, 0, 0, 0, 'paved');
    catch
        rejectedTakeoffExtrapolation = true;
    end
    testNames{end + 1} = 'Takeoff tool rejects weight extrapolation';
    passed(end + 1) = rejectedTakeoffExtrapolation;
    details{end + 1} = 'Expected rejection below 2200-lb POH table';

    landingData = pohLandingData();
    landingPointCount = numel(landingData.groundRoll_ft);
    [testNames, passed, details] = addCheck(testNames, passed, details, ...
        'Complete POH Figure 5-11 landing point count', ...
        landingPointCount, 45, 1e-10, 'points');

    landingGridErrors = maximumLandingGridErrors(landingData);
    [testNames, passed, details] = addCheck(testNames, passed, details, ...
        'All POH landing ground-roll points reproduce exactly', ...
        landingGridErrors.groundRoll_ft, 0, 1e-10, 'ft');
    [testNames, passed, details] = addCheck(testNames, passed, details, ...
        'All POH landing over-50-ft points reproduce exactly', ...
        landingGridErrors.totalOver50ft_ft, 0, 1e-10, 'ft');

    landingExact = pohLandingPerformance(2000, 30, 0, ...
        'paved', 'full');
    [testNames, passed, details] = addCheck(testNames, passed, details, ...
        'POH landing anchor: 2000 ft, 30 C ground roll', ...
        landingExact.interpolated.baseGroundRoll_ft, ...
        650, 1e-10, 'ft');
    [testNames, passed, details] = addCheck(testNames, passed, details, ...
        'POH landing anchor: 2000 ft, 30 C over 50 ft', ...
        landingExact.interpolated.baseTotalOver50ft_ft, ...
        1455, 1e-10, 'ft');

    landingInterior = pohLandingPerformance(1500, 25, 0, ...
        'paved', 'full');
    [testNames, passed, details] = addCheck(testNames, passed, details, ...
        'Interior landing interpolation ground roll', ...
        landingInterior.interpolated.baseGroundRoll_ft, ...
        627.5, 1e-10, 'ft');
    [testNames, passed, details] = addCheck(testNames, passed, details, ...
        'Interior landing interpolation over 50 ft', ...
        landingInterior.interpolated.baseTotalOver50ft_ft, ...
        1420, 1e-10, 'ft');

    [testNames, passed, details] = addCheck(testNames, passed, details, ...
        'Conservative landing grid selects next-higher POH point', ...
        landingInterior.conservative.baseTotalOver50ft_ft, ...
        1455, 1e-10, 'ft');

    landingGrass = pohLandingPerformance(2000, 30, 0, ...
        'dry grass', 'full');
    [testNames, passed, details] = addCheck(testNames, passed, details, ...
        'POH landing dry-grass correction', ...
        landingGrass.interpolated.totalOver50ft_ft, ...
        1747.5, 1e-10, 'ft');

    landingFlapsUp = pohLandingPerformance(2000, 30, 0, ...
        'paved', 'up');
    [testNames, passed, details] = addCheck(testNames, passed, details, ...
        'POH landing flaps-up distance correction', ...
        landingFlapsUp.interpolated.totalOver50ft_ft, ...
        1964.25, 1e-10, 'ft');
    [testNames, passed, details] = addCheck(testNames, passed, details, ...
        'POH landing flaps-up speed correction', ...
        landingFlapsUp.interpolated.speedAt50ft_KIAS, ...
        70, 1e-10, 'KIAS');

    rejectedTailwindOutsidePOH = false;
    try
        pohLandingPerformance(0, 0, -11, 'paved', 'full');
    catch ME
        rejectedTailwindOutsidePOH = strcmp(ME.identifier, ...
            'applyPohFieldCorrections:TailwindOutsidePOH');
    end
    testNames{end + 1} = ...
        'Landing tool rejects tailwind beyond POH correction limit';
    passed(end + 1) = rejectedTailwindOutsidePOH;
    details{end + 1} = 'Expected rejection above 10-kt tailwind';

    rejectedOutsideCruiseData = false;
    try
        enginePowerAvailable(1000, 2400, 0);
    catch ME
        rejectedOutsideCruiseData = startsWith( ...
            ME.identifier, 'enginePowerAvailable:');
    end
    testNames{end + 1} = 'Cruise model rejects altitude outside POH data';
    passed(end + 1) = rejectedOutsideCruiseData;
    details{end + 1} = 'Expected a model-envelope error';

    accuracyAudit = cruiseAccuracyAudit();
    accuracyGateDetectsKnownMismatch = ...
        ~accuracyAudit.currentProxy.passesRMSClosure;
    testNames{end + 1} = ...
        'Accuracy gate flags current drag-plus-propeller cruise mismatch';
    passed(end + 1) = accuracyGateDetectsKnownMismatch;
    details{end + 1} = sprintf( ...
        'RMS closure error %.3f kW; provisional limit %.3f kW', ...
        accuracyAudit.currentProxy.rmsPowerMargin_kW, ...
        accuracyAudit.currentProxy.closureTolerance_kW);

    fprintf('==================================================\n');
    fprintf('C172 PERFORMANCE TOOL VALIDATION\n');
    fprintf('==================================================\n');
    for k = 1:numel(testNames)
        if passed(k)
            status = 'PASS';
        else
            status = 'FAIL';
        end
        fprintf('[%s] %s - %s\n', status, testNames{k}, details{k});
    end

    numberPassed = sum(passed);
    fprintf('\nResult: %d/%d checks passed.\n', ...
        numberPassed, numel(passed));

    if numberPassed ~= numel(passed)
        error('runValidation:Failed', ...
            '%d validation checks failed.', numel(passed) - numberPassed);
    end
end

function maximumErrors = maximumTakeoffGridErrors(takeoffData)
%MAXIMUMTAKEOFFGRIDERRORS Check every digitized Figure 5-5 distance.

    maximumErrors = struct('groundRoll_ft', 0, ...
        'totalOver50ft_ft', 0);
    for weightIndex = 1:numel(takeoffData.weightGrid_lb)
        for altitudeIndex = 1:numel(takeoffData.altitudeGrid_ft)
            for temperatureIndex = 1:numel(takeoffData.temperatureGrid_C)
                point = pohTakeoffPerformance( ...
                    takeoffData.weightGrid_lb(weightIndex), ...
                    takeoffData.altitudeGrid_ft(altitudeIndex), ...
                    takeoffData.temperatureGrid_C(temperatureIndex), ...
                    0, 'paved');
                maximumErrors.groundRoll_ft = max( ...
                    maximumErrors.groundRoll_ft, ...
                    abs(point.interpolated.baseGroundRoll_ft - ...
                    takeoffData.groundRoll_ft{weightIndex}( ...
                    altitudeIndex, temperatureIndex)));
                maximumErrors.totalOver50ft_ft = max( ...
                    maximumErrors.totalOver50ft_ft, ...
                    abs(point.interpolated.baseTotalOver50ft_ft - ...
                    takeoffData.totalOver50ft_ft{weightIndex}( ...
                    altitudeIndex, temperatureIndex)));
            end
        end
    end
end

function maximumErrors = maximumLandingGridErrors(landingData)
%MAXIMUMLANDINGGRIDERRORS Check every digitized Figure 5-11 distance.

    maximumErrors = struct('groundRoll_ft', 0, ...
        'totalOver50ft_ft', 0);
    for altitudeIndex = 1:numel(landingData.altitudeGrid_ft)
        for temperatureIndex = 1:numel(landingData.temperatureGrid_C)
            point = pohLandingPerformance( ...
                landingData.altitudeGrid_ft(altitudeIndex), ...
                landingData.temperatureGrid_C(temperatureIndex), ...
                0, 'paved', 'full');
            maximumErrors.groundRoll_ft = max( ...
                maximumErrors.groundRoll_ft, ...
                abs(point.interpolated.baseGroundRoll_ft - ...
                landingData.groundRoll_ft( ...
                altitudeIndex, temperatureIndex)));
            maximumErrors.totalOver50ft_ft = max( ...
                maximumErrors.totalOver50ft_ft, ...
                abs(point.interpolated.baseTotalOver50ft_ft - ...
                landingData.totalOver50ft_ft( ...
                altitudeIndex, temperatureIndex)));
        end
    end
end

function maximumErrors = maximumCruiseGridErrors(cruiseData)
%MAXIMUMCRUISEGRIDERRORS Check all digitized MCP, KTAS, and GPH points.

    mcpTables = { ...
        cruiseData.mcpCold_pct, ...
        cruiseData.mcpISA_pct, ...
        cruiseData.mcpHot_pct};
    ktasTables = { ...
        cruiseData.ktasCold, ...
        cruiseData.ktasISA, ...
        cruiseData.ktasHot};
    gphTables = { ...
        cruiseData.gphCold, ...
        cruiseData.gphISA, ...
        cruiseData.gphHot};
    maximumErrors = struct( ...
        'percentMCP', 0, ...
        'trueAirspeed_KTAS', 0, ...
        'fuelFlow_GPH', 0);

    for temperatureIndex = 1:numel(cruiseData.deltaISAColumns_C)
        temperatureOffset_C = ...
            cruiseData.deltaISAColumns_C(temperatureIndex);
        mcpTable = mcpTables{temperatureIndex};
        ktasTable = ktasTables{temperatureIndex};
        gphTable = gphTables{temperatureIndex};

        for altitudeIndex = 1:numel(cruiseData.altitudeGrid_ft)
            for rpmIndex = 1:numel(cruiseData.rpmGrid{altitudeIndex})
                point = pohCruiseTableLookup( ...
                    cruiseData.altitudeGrid_ft(altitudeIndex), ...
                    cruiseData.rpmGrid{altitudeIndex}(rpmIndex), ...
                    temperatureOffset_C);
                maximumErrors.percentMCP = max( ...
                    maximumErrors.percentMCP, ...
                    abs(point.percentMCP - ...
                    mcpTable{altitudeIndex}(rpmIndex)));
                maximumErrors.trueAirspeed_KTAS = max( ...
                    maximumErrors.trueAirspeed_KTAS, ...
                    abs(point.trueAirspeed_KTAS - ...
                    ktasTable{altitudeIndex}(rpmIndex)));
                maximumErrors.fuelFlow_GPH = max( ...
                    maximumErrors.fuelFlow_GPH, ...
                    abs(point.fuelFlow_GPH - ...
                    gphTable{altitudeIndex}(rpmIndex)));
            end
        end
    end
end

function [names, passed, details] = addCheck( ...
        names, passed, details, name, actual, expected, tolerance, unit)

    names{end + 1} = name;
    passed(end + 1) = isfinite(actual) && ...
        abs(actual - expected) <= tolerance;
    details{end + 1} = sprintf( ...
        'actual %.6g %s, expected %.6g +/- %.3g %s', ...
        actual, unit, expected, tolerance, unit);
end
