function result = turnPerformance(aircraft, pressureAltitude_ft, ...
        deltaISA_C, weight_lb, airspeed_KCAS, bankAngle_deg)
%TURNPERFORMANCE Evaluate a steady coordinated level turn for a C172S.
%
%   RESULT = TURNPERFORMANCE(AIRCRAFT, PA_FT, DELTAISA_C, WEIGHT_LB,
%   AIRSPEED_KCAS, BANK_DEG) combines published POH normal-category limits
%   with analytical steady-level-turn equations. KCAS is approximated as
%   KEAS only to derive TAS from density. No gust envelope is inferred.

    requiredFields = {'referenceStallSpeedFlapsUp_KCAS', ...
        'maxGrossWeight_lb'};
    for fieldIndex = 1:numel(requiredFields)
        if ~isfield(aircraft, requiredFields{fieldIndex})
            error('turnPerformance:MissingAircraftField', ...
                'aircraft.%s is required.', requiredFields{fieldIndex});
        end
    end

    validateattributes(pressureAltitude_ft, {'numeric'}, ...
        {'real', 'finite', 'nonnegative', 'scalar'}, mfilename, ...
        'pressureAltitude_ft', 2);
    validateattributes(deltaISA_C, {'numeric'}, ...
        {'real', 'finite', 'scalar'}, mfilename, 'deltaISA_C', 3);
    validateattributes(weight_lb, {'numeric'}, ...
        {'real', 'finite', 'positive', 'scalar'}, mfilename, ...
        'weight_lb', 4);
    validateattributes(airspeed_KCAS, {'numeric'}, ...
        {'real', 'finite', 'positive', 'scalar'}, mfilename, ...
        'airspeed_KCAS', 5);
    validateattributes(bankAngle_deg, {'numeric'}, ...
        {'real', 'finite', 'nonnegative', 'scalar'}, mfilename, ...
        'bankAngle_deg', 6);

    maximumAltitude_ft = 12000;
    if isfield(aircraft, 'pohMaximumAltitude_ft')
        maximumAltitude_ft = aircraft.pohMaximumAltitude_ft;
    end
    if pressureAltitude_ft > maximumAltitude_ft
        error('turnPerformance:AltitudeOutsideModel', ...
            'Pressure altitude must not exceed %.0f ft.', ...
            maximumAltitude_ft);
    end
    if deltaISA_C < -20 || deltaISA_C > 20
        error('turnPerformance:TemperatureOutsideModel', ...
            'ISA temperature offset must be between -20 and +20 deg C.');
    end
    if weight_lb > aircraft.maxGrossWeight_lb
        error('turnPerformance:WeightAboveMaximum', ...
            'Weight must not exceed the %.0f-lb maximum gross weight.', ...
            aircraft.maxGrossWeight_lb);
    end

    pohLimits = pohManeuverLimits(weight_lb);
    if bankAngle_deg > pohLimits.maximumNormalCategoryBankAngle_deg
        error('turnPerformance:BankAngleOutsideNormalCategory', ...
            ['Bank angle must not exceed the POH normal-category limit ' ...
             'of %.0f degrees.'], ...
            pohLimits.maximumNormalCategoryBankAngle_deg);
    end
    if airspeed_KCAS > pohLimits.neverExceedSpeed_KCAS
        error('turnPerformance:AirspeedAboveVNE', ...
            'Airspeed must not exceed VNE = %.0f KCAS.', ...
            pohLimits.neverExceedSpeed_KCAS);
    end

    KT_TO_MPS = 0.514444;
    RHO0 = 1.2250;
    G_MPS2 = 9.80665;

    atmosphere = atmosphereAtPressureAltitude( ...
        pressureAltitude_ft, deltaISA_C);
    loadFactor_g = 1 / cosd(bankAngle_deg);
    levelStallSpeed_KCAS = ...
        aircraft.referenceStallSpeedFlapsUp_KCAS * ...
        sqrt(weight_lb / aircraft.maxGrossWeight_lb);
    acceleratedStallSpeed_KCAS = ...
        levelStallSpeed_KCAS * sqrt(loadFactor_g);
    stallSpeedMargin_KCAS = airspeed_KCAS - acceleratedStallSpeed_KCAS;

    equivalentAirspeed_mps = airspeed_KCAS * KT_TO_MPS;
    trueAirspeed_mps = equivalentAirspeed_mps * ...
        sqrt(RHO0 / atmosphere.rho);
    trueAirspeed_KTAS = trueAirspeed_mps / KT_TO_MPS;

    if bankAngle_deg == 0
        turnRadius_m = Inf;
        turnRate_degps = 0;
        timeFor360_s = Inf;
    else
        turnRadius_m = trueAirspeed_mps^2 / ...
            (G_MPS2 * tand(bankAngle_deg));
        turnRate_radps = G_MPS2 * tand(bankAngle_deg) / ...
            trueAirspeed_mps;
        turnRate_degps = rad2deg(turnRate_radps);
        timeFor360_s = 2 * pi / turnRate_radps;
    end

    stallLimitedLoadFactor_g = ...
        (airspeed_KCAS / levelStallSpeed_KCAS)^2;
    structuralLimitLoadFactor_g = pohLimits.positiveLoadFactorLimit_g;
    availableLoadFactor_g = min( ...
        stallLimitedLoadFactor_g, structuralLimitLoadFactor_g);
    if stallLimitedLoadFactor_g <= 1
        stallLimitedBankAngle_deg = 0;
    else
        stallLimitedBankAngle_deg = ...
            acosd(1 / stallLimitedLoadFactor_g);
    end
    structuralLimitBankAngle_deg = ...
        acosd(1 / structuralLimitLoadFactor_g);
    maximumPermittedBankAngle_deg = min([ ...
        stallLimitedBankAngle_deg, ...
        structuralLimitBankAngle_deg, ...
        pohLimits.maximumNormalCategoryBankAngle_deg]);

    numericalTolerance = 100 * eps(max(1, stallLimitedLoadFactor_g));
    turnFeasible = loadFactor_g <= ...
        stallLimitedLoadFactor_g + numericalTolerance && ...
        loadFactor_g <= structuralLimitLoadFactor_g + numericalTolerance;

    aboveManeuveringSpeed = ...
        airspeed_KCAS > pohLimits.maneuveringSpeed_KCAS;
    aboveMaximumStructuralCruisingSpeed = airspeed_KCAS > ...
        pohLimits.maximumStructuralCruisingSpeed_KCAS;
    if aboveMaximumStructuralCruisingSpeed
        airspeedRegion = ...
            'ABOVE VNO; POH CAUTION RANGE FOR SMOOTH AIR ONLY';
    elseif aboveManeuveringSpeed
        airspeedRegion = ...
            'ABOVE VA; FULL OR ABRUPT CONTROL INPUTS NOT SUPPORTED';
    else
        airspeedRegion = 'AT OR BELOW WEIGHT-ADJUSTED VA';
    end

    result = struct( ...
        'pressureAltitude_ft', pressureAltitude_ft, ...
        'deltaISA_C', deltaISA_C, ...
        'weight_lb', weight_lb, ...
        'airspeed_KCAS', airspeed_KCAS, ...
        'bankAngle_deg', bankAngle_deg, ...
        'atmosphere', atmosphere, ...
        'pohLimits', pohLimits, ...
        'loadFactor_g', loadFactor_g, ...
        'levelStallSpeed_KCAS', levelStallSpeed_KCAS, ...
        'acceleratedStallSpeed_KCAS', acceleratedStallSpeed_KCAS, ...
        'stallSpeedMargin_KCAS', stallSpeedMargin_KCAS, ...
        'equivalentAirspeed_mps', equivalentAirspeed_mps, ...
        'trueAirspeed_mps', trueAirspeed_mps, ...
        'trueAirspeed_KTAS', trueAirspeed_KTAS, ...
        'turnRadius_m', turnRadius_m, ...
        'turnRate_degps', turnRate_degps, ...
        'timeFor360_s', timeFor360_s, ...
        'stallLimitedLoadFactor_g', stallLimitedLoadFactor_g, ...
        'structuralLimitLoadFactor_g', structuralLimitLoadFactor_g, ...
        'availableLoadFactor_g', availableLoadFactor_g, ...
        'stallLimitedBankAngle_deg', stallLimitedBankAngle_deg, ...
        'structuralLimitBankAngle_deg', structuralLimitBankAngle_deg, ...
        'maximumPermittedBankAngle_deg', ...
            maximumPermittedBankAngle_deg, ...
        'turnFeasible', turnFeasible, ...
        'aboveManeuveringSpeed', aboveManeuveringSpeed, ...
        'aboveMaximumStructuralCruisingSpeed', ...
            aboveMaximumStructuralCruisingSpeed, ...
        'airspeedRegion', airspeedRegion, ...
        'classification', ...
            'HYBRID: POH LIMITS + ANALYTICAL COORDINATED-TURN MODEL', ...
        'analyticalSource', ['Standard point-mass steady coordinated ' ...
            'level-turn equations; no POH numerical calibration'], ...
        'assumptions', {{ ...
            'steady coordinated constant-altitude turn', ...
            'still air', ...
            'flaps up', ...
            'KCAS approximated as KEAS only for TAS conversion', ...
            'no gust-envelope construction', ...
            'normal category only'}});
end
